; item ids
; indexes for:
; - ItemNames (see data/items/names.asm)
; - ItemDescriptions (see data/items/descriptions.asm)
; - ItemAttributes (see data/items/attributes.asm)
; - ItemEffects (see engine/items/item_effects.asm)
	const_def
	const NO_ITEM
	const BRIGHTPOWDER
	const MOON_STONE
	const ANTIDOTE
	const BURN_HEAL
	const ICE_HEAL
	const AWAKENING
	const PARLYZ_HEAL
	const FULL_RESTORE
	const MAX_POTION
	const HYPER_POTION
	const SUPER_POTION
	const POTION
	const ESCAPE_ROPE
	const REPEL
	const MAX_ELIXER
	const FIRE_STONE
	const THUNDERSTONE
	const WATER_STONE
	const HP_UP
	const PROTEIN
	const IRON
	const CARBOS
	const LUCKY_PUNCH
	const CALCIUM
	const RARE_CANDY
	const X_ACCURACY
	const LEAF_STONE
	const METAL_POWDER
	const NUGGET
	const POKE_DOLL
	const FULL_HEAL
	const REVIVE
	const MAX_REVIVE
	const GUARD_SPEC
	const SUPER_REPEL
	const MAX_REPEL
	const DIRE_HIT
	const FRESH_WATER
	const SODA_POP
	const LEMONADE
	const X_ATTACK
	const SNAKESKIN
	const X_DEFEND
	const X_SPEED
	const X_SPECIAL
	const EXP_SHARE
	const SILVER_LEAF
	const PP_UP
	const ETHER
	const MAX_ETHER
	const ELIXER
	const MOOMOO_MILK
	const QUICK_CLAW
	const PSNCUREBERRY
	const GOLD_LEAF
	const SOFT_SAND
	const BLACK_FEATHER
	const PRZCUREBERRY
	const BURNT_BERRY
	const ICE_BERRY
	const TOXIC_NEEDLE
	const KINGS_ROCK
	const BITTER_BERRY
	const MINT_BERRY
	const RED_APRICORN
	const CORDYCEPS
	const BIG_MUSHROOM
	const SILVERPOWDER
	const BLU_APRICORN
	const EARTHEN_CLAY
	const AMULET_COIN
	const YLW_APRICORN
	const GRN_APRICORN
	const CLEANSE_TAG
	const AQUA_HORN
	const MIGRAINE_SEED
	const WHT_APRICORN
	const BLACKBELT
	const BLK_APRICORN
	const DIGGING_CLAW
	const PNK_APRICORN
	const BLACKGLASSES
	const SLOWPOKETAIL
	const PINK_BOW
	const STICK
	const ICE_FANG
	const THUNDER_FANG
	const MIRACLEBERRY
	const PEARL
	const BIG_PEARL
	const EVERSTONE
	const SPELL_TAG
	const RAGECANDYBAR
	const MIRACLE_SEED
	const THICK_CLUB
	const FOCUS_ORB
	const MYSTIC_PETAL
	const ENERGYPOWDER
	const ENERGY_ROOT
	const HEAL_POWDER
	const REVIVAL_HERB
	const HARD_STONE
	const LUCKY_EGG
	const STARDUST
	const STAR_PIECE
	const WHITE_FEATHER
	const ELECTRIC_POUCH
	const CHARCOAL
	const BERRY_JUICE
	const SHARP_SCYTHE
	const FIRE_MANE
	const METAL_COAT
	const DRAGON_FANG
	const TWISTED_SPOON
	const LEFTOVERS
	const FOSSIL_SHARD
	const GROSS_GARBAGE
	const CHAMPIONBELT
	const MYSTERYBERRY
	const DRAGON_SCALE
	const BERSERK_GENE
	const TAG
	const GUARD_THREAD
	const ICE_BIKINI
	const SACRED_ASH
	const FLOWER_MAIL
	const WISDOM_ORB
	const NORMAL_BOX
	const GORGEOUS_BOX
	const SUN_STONE
	const POLKADOT_BOW
	const ODD_THREAD
	const UP_GRADE
	const BERRY
	const APPLE
	const WATER_TAIL
	const COUNTERCUFF
	const BRICK_PIECE
	const SURF_MAIL
	const LITEBLUEMAIL
	const PORTRAITMAIL
	const LOVELY_MAIL
	const EON_MAIL
	const MORPH_MAIL
	const BLUESKY_MAIL
	const MUSIC_MAIL
	const MIRAGE_MAIL
	const PRETTY_TAIL
	const BURST_ORB
	const HIDDEN_NEEDLE
	const SHARP_HORN
	const HEART_STONE
	const POISON_STONE
	const DETECT_ORB
	const LONG_TONGUE
	const LONG_VINE
	const ICE_WING
	const THUNDER_WING
	const FIRE_WING
	const FIRE_TAIL
	const THUNDER_TAIL
	const CALM_SEED
	const SPOON
	const PEBBLE
	const BIG_STONE
	const TORN_COLLAR
	const CRUSHED_TIRE
	const TINY_SCALES
	const STEEL_SCALES
	const MYSTIC_TAG
	const FLEE_FEATHER
	const CRANIDOS_FOSSIL
	const MYSTIC_WATER
	const CONFUSE_CLAW
	const STEEL_SHELL
	const FIVE_YEN_COIN
	const LIFE_TAG
	const STRANGE_POWDER
	const BUG_FLYING_FOSSIL
	const SKELEBRO_FOSSIL
	const INVISIBLE_WALL
	const SKATEBOARD
	const MOMS_LOVE
	const MYSTIC_THREAD
	const MYSTIC_NEEDLE
	const FUJIS_LETTER
	const WOBBLY_BLOON
NUM_ITEM_POCKET EQU const_value - 1

; Key items assume the value of HIGH(FIRST_KEY_ITEM) when storing in bag
	const_align 8 
FIRST_KEY_ITEM EQU const_value
	const TOWN_MAP
	const BICYCLE
	const HONEY_POT
	const OAKS_PARCEL
	const COIN_CASE
	const ITEMFINDER
	const POKE_FLUTE
	const OLD_ROD
	const GOOD_ROD
	const SUPER_ROD
	const RED_SCALE
	const SECRETPOTION
	const S_S_TICKET
	const ELMS_EGG
	const CLEAR_BELL
	const SILVER_WING
	const GS_BALL
	const BLUE_CARD
	const CARD_KEY
	const MACHINE_PART
	const EGG_TICKET
	const LOST_ITEM
	const BASEMENT_KEY
	const PASS
	const SQUIRTBOTTLE
	const RAINBOW_WING
	const VOUCHER
	const TICKLE_STICK
	const HEAVY_AMBER
	const TOXIC_AMBER
	const OLD_AMBER
	const DOME_FOSSIL
	const HELIX_FOSSIL
NUM_KEY_ITEM_POCKET EQU const_value - FIRST_KEY_ITEM

; Ball items assume the value of HIGH(FIRST_BALL_ITEM) when storing in bag
	const_align 8 
FIRST_BALL_ITEM EQU const_value
	const MASTER_BALL
	const ULTRA_BALL
	const GREAT_BALL
	const POKE_BALL
	const SAFARI_BALL
	const DIRECT_BALL
	const NIGHT_BALL
	const PARK_BALL
	const SMOKE_BALL
	const HEAVY_BALL
	const LEVEL_BALL
	const LURE_BALL
	const FAST_BALL
	const LIGHT_BALL
	const FRIEND_BALL
	const MOON_BALL
	const LOVE_BALL
NUM_BALL_ITEM_POCKET EQU const_value - FIRST_KEY_ITEM

NUM_ITEMS EQU const_value - 1

USE_SCRIPT_VAR EQU 0
ITEM_FROM_MEM  EQU -1

