Debug_CalleeNames::
	db "Nobody@@@@@@@@@@@@"
	db "Mom@@@@@@@@@@@@@@@"
	db "Bike Shop@@@@@@@@@"
	db "Bill@@@@@@@@@@@@@@"
	db "Prof. Elm@@@@@@@@@"
	db "Beverly (N. Park)@"
	db "Huey (Lighthouse)@"
	db "MissingNo.@@@@@@@@"
	db "MissingNo.@@@@@@@@"
	db "MissingNo.@@@@@@@@"
	db "Gaven (Route 26)@@"
	db "Beth (Route 26)@@@"
	db "Jose (Route 27)@@@"
	db "Reena (Route 27)@@"
	db "Joey (Route 29)@@@"
	db "Stanley (Route31)@"
	db "Ralph (Route 32N)@"
	db "Liz (Route 32N)@@@"
	db "Anthony (Route33)@"
	db "Todd (Route 34)@@@"
	db "Gina (Route 34)@@@"
	db "Irwin (Route 35)@@"
	db "Arnie (Route 35)@@"
	db "MissingNo.@@@@@@@@"
	db "Dana (Route 38)@@@"
	db "Chad (Route 38)@@@"
	db "Derek (Route 39)@@"
	db "Tully (Route 42)@@"
	db "Brent (Route 43)@@"
	db "Tiffany (Route43)@"
	db "Vance (Route 44)@@"
	db "Wilton (Route 44)@"
	db "Kenji (Route 45)@@"
	db "Parry (Route 45)@@"
	db "NieNie (Route 46)@"
	db "Buena (Roof)@@@@@@"
