Debug_MusicNames::
	db "None@@@@@@@@@@@@@@"
	db "Title@@@@@@@@@@@@@"
	db "Route 1@@@@@@@@@@@"
	db "Route 3@@@@@@@@@@@"
	db "Route 12@@@@@@@@@@"
	db "Magnet Train@@@@@@"
	db "Kanto Gym@@@@@@@@@"
	db "Kanto Trainer@@@@@"
	db "Kanto Wild@@@@@@@@"
	db "Pokemon Center@@@@"
	db "Enc. Hiker@@@@@@@@"
	db "Enc. Lass@@@@@@@@@"
	db "Enc. Officer@@@@@@"
	db "Heal Pokemon@@@@@@"
	db "Lavender Town@@@@@"
	db "Route 2@@@@@@@@@@@"
	db "Mt. Moon@@@@@@@@@@"
	db "Follow Me!@@@@@@@@"
	db "Game Corner@@@@@@@"
	db "Bicycle@@@@@@@@@@@"
	db "Hall of Fame@@@@@@"
	db "Viridian City@@@@@"
	db "Celadon City@@@@@@"
	db "Victory, Trainer@@"
	db "Victory, Wild@@@@@"
	db "Victory, Leader@@@"
	db "Mt. Moon Square@@@"
	db "Gym@@@@@@@@@@@@@@@"
	db "Pallet Town@@@@@@@"
	db "Pokemon Talk@@@@@@"
	db "Oak Theme@@@@@@@@@"
	db "Rival Theme@@@@@@@"
	db "Rival After Batt.@"
	db "Surfing@@@@@@@@@@@"
	db "Evolution@@@@@@@@@"
	db "National Park@@@@@"
	db "Credits@@@@@@@@@@@"
	db "Azalea@@@@@@@@@@@@"
	db "Cherrygrove@@@@@@@"
	db "Enc. Kimono Girl@@"
	db "Union Cave@@@@@@@@"
	db "Johto Wild@@@@@@@@"
	db "Johto Trainer@@@@@"
	db "Route 30@@@@@@@@@@"
	db "Ecruteak City@@@@@"
	db "Violet City@@@@@@@"
	db "Johto Leader@@@@@@"
	db "Champion Battle@@@"
	db "Rival Battle@@@@@@"
	db "Rocket Battle@@@@@"
	db "Elm's Lab@@@@@@@@@@"
	db "Ice Path@@@@@@@@@@"
	db "Route 29@@@@@@@@@@"
	db "Route 36@@@@@@@@@@"
	db "S.S. Aqua@@@@@@@@@"
	db "Enc. Youngster@@@@"
	db "Enc. Beauty@@@@@@@"
	db "Enc. Rocket@@@@@@@"
	db "Enc. PokeManiac@@@"
	db "Enc. Sage@@@@@@@@@"
	db "New Bark Town@@@@@"
	db "Goldenrod City@@@@"
	db "Vermilion City@@@@"
	db "Pokemon Channel@@@"
	db "Poke Flute@@@@@@@@"
	db "Tin Tower@@@@@@@@@"
	db "Sprout Tower@@@@@@"
	db "Burned Tower@@@@@@"
	db "Lighthouse@@@@@@@@"
	db "Route 42@@@@@@@@@@"
	db "Indigo Plateau@@@@"
	db "Route 38@@@@@@@@@@"
	db "Rocket Hideout@@@@"
	db "Dragon's Den@@@@@@@"
	db "Johto Wild Night@@"
	db "Unown Radio@@@@@@@"
	db "Fanfare, Capture@@"
	db "Route 27@@@@@@@@@@"
	db "Mom Notice@@@@@@@@"
	db "Victory Road@@@@@@"
	db "Lullaby@@@@@@@@@@@"
	db "Pokemon March@@@@@"
	db "G/S Intro Part 1@@"
	db "G/S Intro Part 2@@"
	db "Main Menu@@@@@@@@@"
	db "Ruins of Alph@@@@@"
	db "Rocket Overture@@@"
	db "Dance Hall@@@@@@@@"
	db "Bug Contest Resu.@"
	db "Bug Results 2@@@@@"
	db "Rocket Radio@@@@@@"
	db "Printer Error@@@@@"
	db "The End@@@@@@@@@@@"
	db "Clair Theme@@@@@@@"
	db "Mobile Menu@@@@@@@"
	db "Mobile Adapter@@@@"
	db "Buena's Password@@@"
	db "Eusine Theme@@@@@@"
	db "Crystal Intro@@@@@"
	db "Battle Tower@@@@@@"
	db "Battle Legendary@@"
	db "Battle Tower Int.@"
	db "PokeCom Center@@@@"
	db "Diglett's Cave@@@@@"
	db "Cerulean City@@@@@"
	db "Cinnabar Island@@@"
	db "Routes 24, 25@@@@@"
	db "Battle! Oak, Elm@@"
	db "Pokemon Tower@@@@@"
	db "Alder Town@@@@@@@@"
	db "Route 32@@@@@@@@@@"
	db "Giovanni@@@@@@@@@@"
	db "Citrine Inn Rest@@"
	db "Blue Battle@@@@@@@"
	db "Dread Woods@@@@@@@"
	db "Cinnabar Mansion@@"
	db "Pokemart@@@@@@@@@@"