; pinch
; by Zumi

; from b2/w2

; generated by mml2pret.py on 2022-06-01 12:32:37

Music_Pinch:
	channel_count 3
	channel 1, Music_GymLeaderPinch_Ch1
	channel 2, Music_GymLeaderPinch_Ch2
	channel 3, Music_GymLeaderPinch_Ch3

Music_GymLeaderPinch_Ch1:
	tempo 118
	octave 3
	duty_cycle 3
	pitch_offset 3
	vibrato 12, 3, 4
	volume 7, 7
	octave 2
	note_type 12, 9, 0
	note A#, 1
	note A#, 5
	note G_, 8
	octave 3
	note F#, 8
	octave 4
	note E_, 4
	octave 3
	note_type 8, 11, 3
	note B_, 4
	octave 4
	note E_, 4
	note A_, 4
	octave 3
	note_type 12, 13, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note G#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note G#, 1
	note A#, 1
	octave 4
	note C_, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note C_, 1
	octave 3
	note A#, 1
	note G#, 1
	note G_, 1
	note F_, 1
	note D#, 1
	note C#, 1
	note C_, 1
	octave 2
	note A#, 1
	octave 3
	note C_, 1
	octave 2
	note A#, 1
	octave 3
	note C_, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note G#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note D#, 1
	note G#, 1
	note A#, 1
	octave 4
	note C_, 1
	note C#, 1
	note D#, 1
	note C#, 1
	note C_, 1
	octave 3
	note A#, 1
	note G#, 1
	note G_, 1
	note F_, 1
	note D#, 1
	duty_cycle 3
.loop0:
	note_type 8, 13, 1
	note D#, 2
	sound_loop 5, .loop0
	note F_, 2
.main_loop:
	sound_call .sub_0
	note G_, 4
	note F#, 2
	note F_, 1
	note E_, 1
	note D#, 4
	octave 4
	note C#, 6
	note C_, 1
	octave 3
	note B_, 1
	note A#, 6
	note D#, 1
	note D_, 1
	note C#, 2
	note D#, 2
	note_type 12, 11, 3
	note E_, 4
	note_type 12, 11, 6
	note E_, 6
	note_type 12, 11, 1
	note E_, 1
	note E_, 1
	note F#, 2
	note F#, 2
	note_type 8, 11, 1
	note A#, 2
	note A#, 2
	note A#, 2
	sound_call .sub_0
	note C#, 4
	note C_, 2
	octave 2
	note G#, 6
	octave 3
	note_type 8, 11, 6
	note G#, 4
	note F_, 4
	note G#, 4
	note_type 12, 11, 6
	note A#, 4
	note E_, 4
	note_type 8, 11, 6
	note G#, 4
	note E_, 4
	note C#, 4
	note_type 12, 11, 6
	note A#, 6
	note_type 12, 11, 1
	note A#, 1
	note A#, 1
	note G#, 1
	octave 4
	note C#, 1
	octave 3
	note E_, 1
	note G#, 1
	note E_, 1
	note G_, 1
	note G#, 1
	note A#, 1
	note_type 12, 11, 6
	note C_, 6
	note D#, 2
	note G#, 16
	rest 2
	octave 4
	note C#, 4
	note C_, 1
	octave 3
	note B_, 1
	octave 4
	note G#, 6
	note_type 12, 11, 1
	note G_, 1
	note F#, 1
	note_type 12, 11, 6
	note F_, 4
	note C#, 1
	note G#, 1
	octave 3
	note A#, 1
	octave 4
	note C#, 1
	note E_, 6
	note C#, 1
	note D#, 1
	note E_, 6
	note E_, 1
	note F#, 1
	octave 3
	note C_, 6
	note D#, 2
	octave 4
	note C_, 4
	octave 3
	note A#, 4
	note G#, 4
	note D#, 2
	note F#, 2
	note_type 8, 11, 6
	note A#, 4
	note G#, 4
	note A#, 4
	note_type 12, 11, 6
	note B_, 6
	octave 4
	note E_, 2
	octave 3
	note B_, 4
	octave 2
	note B_, 2
	octave 3
	note C#, 1
	note D#, 1
	note G#, 4
	note_type 12, 11, 1
	note G#, 1
	note A#, 1
	octave 4
	note C#, 1
	note C#, 1
	note D#, 1
	note D_, 1
	note D#, 4
	note D#, 2
	octave 3
	note_type 12, 13, 1
	note F_, 2
	note C#, 2
	note F_, 2
	note G#, 2
	note F_, 2
	note C#, 2
	note F_, 2
	note G#, 2
	note A#, 2
	note G_, 2
	note A#, 2
	octave 4
	note C_, 2
	octave 3
	note A#, 1
	octave 4
	note C_, 1
	octave 3
	note G_, 1
	note G#, 1
	note A#, 2
	octave 4
	note C_, 2
	octave 3
	note G_, 2
	note D#, 2
	note G_, 2
	note A#, 2
	note G_, 2
	note D#, 2
	note G_, 2
	note A#, 2
	octave 2
	note F_, 1
	octave 3
	note C_, 1
	note F_, 1
	note G#, 1
	octave 2
	note E_, 1
	octave 3
	note C_, 1
	note F_, 1
	note G_, 1
	octave 2
	note D#, 1
	octave 3
	note C_, 1
	note F_, 1
	note G_, 1
	note G#, 1
	note A#, 1
	octave 4
	note C_, 1
	note C#, 1
	duty_cycle 2
	note_type 12, 11, 1
	note F_, 3
	note C#, 1
	note_type 12, 11, 2
	note F_, 2
	note C#, 2
	note F_, 2
	note C#, 2
	note F_, 2
	note G#, 2
	note_type 12, 11, 1
	note G_, 3
	note G#, 1
	note_type 12, 11, 2
	note G_, 4
	note_type 12, 11, 1
	note G_, 1
	note G_, 1
	note F#, 1
	note G_, 1
	octave 5
	note C_, 2
	octave 4
	note G_, 2
	note_type 12, 11, 2
	note D#, 2
	note C_, 4
	octave 3
	note G_, 2
	note G_, 2
	note G_, 2
	note A#, 4
	note_type 12, 11, 1
	note A_, 2
	octave 4
	note C_, 2
	note F_, 2
	note C_, 2
	octave 3
	note F_, 2
	octave 4
	note C_, 2
	note D#, 2
	note C_, 2
	duty_cycle 3
	note F_, 3
	note D#, 1
	note_type 12, 11, 6
	note C#, 8
	octave 3
	note_type 12, 11, 1
	note G_, 1
	note G#, 1
	note A#, 1
	octave 4
	note C_, 1
	note F_, 3
	note E_, 1
	note_type 12, 11, 6
	note D_, 10
	note_type 12, 11, 1
	note D_, 1
	note D_, 1
	note_type 12, 11, 7
	note D#, 16
	rest 2
	octave 3
	octave 2
	note_type 12, 11, 6
	note G#, 6
	octave 3
	note B_, 4
	octave 4
	note A_, 2
	octave 5
	note D_, 2
	octave 4
	octave 3
	sound_jump .main_loop
	sound_ret
.sub_0
	note_type 12, 11, 6
	note C_, 6
	note D#, 2
	note G#, 4
	sound_ret

Music_GymLeaderPinch_Ch2:
	octave 3
	duty_cycle 3
	pitch_offset 1
	note_type 12, 10, 1
	note D#, 1
	note D#, 1
	octave 2
	note_type 12, 9, 0
	note D#, 8
	octave 3
	note C#, 8
	note B_, 8
	octave 4
	note_type 8, 12, 4
	note A_, 4
	octave 5
	note D_, 4
	note G_, 4
	vibrato 16, 4, 6
	note_type 12, 13, 4
	note C#, 6
	note_type 12, 13, 3
	note C#, 4
	note C#, 2
	note_type 12, 12, 1
	note C#, 1
	note C#, 1
	note_type 12, 13, 3
	note C#, 2
	note_type 12, 13, 4
	note C_, 6
	note_type 12, 13, 3
	note C_, 4
	note C_, 2
	note_type 12, 12, 1
	note C_, 1
	note C_, 1
	note_type 12, 13, 3
	note C_, 2
	note_type 12, 13, 4
	note C#, 6
	note_type 12, 13, 3
	note C#, 4
	note C#, 2
	note_type 12, 12, 1
	note C#, 1
	note C#, 1
	note_type 12, 13, 3
	note C#, 2
	octave 4
	note_type 12, 13, 1
	note G#, 1
	note G_, 1
	note G#, 6
	octave 3
.loop1:
	note_type 8, 13, 1
	note F#, 2
	sound_loop 5, .loop1
	note G_, 2
.main_loop:
	sound_call .sub_0
	note F#, 6
	note F_, 1
	note E_, 1
	note D#, 6
	note_type 12, 13, 1
	note D_, 1
	note C#, 1
	octave 3
	note_type 12, 13, 2
	note G#, 4
	note A#, 4
	note_type 12, 13, 6
	note G#, 6
	note_type 12, 13, 1
	note G#, 1
	note G#, 1
	note A#, 2
	note A#, 2
	octave 4
	note_type 8, 13, 1
	note C#, 2
	note C#, 2
	note C#, 2
	sound_call .sub_0
	note_type 8, 13, 6
	note C#, 4
	octave 3
	note A#, 4
	octave 4
	note C#, 4
	note_type 12, 13, 6
	note D#, 4
	octave 3
	note G#, 4
	octave 4
	note_type 8, 13, 6
	note C#, 4
	octave 3
	note A#, 4
	note G#, 4
	octave 4
	note_type 12, 13, 6
	note D#, 6
	note_type 12, 13, 1
	note D#, 1
	note D#, 1
	note_type 12, 13, 3
	note D#, 4
	octave 3
	note_type 12, 13, 1
	note G_, 1
	note A#, 1
	octave 4
	note C#, 1
	note D#, 1
	sound_call .sub_0
	rest 2
	note_type 12, 13, 4
	note F#, 4
	note F_, 1
	note E_, 1
	octave 5
	note D#, 6
	note C#, 1
	note C_, 1
	note C#, 4
	octave 4
	note_type 12, 13, 1
	note G#, 1
	octave 5
	note C#, 1
	octave 4
	note F_, 1
	note G_, 1
	note_type 12, 13, 4
	note B_, 6
	note A#, 1
	note B_, 1
	octave 5
	note C#, 6
	octave 4
	note B_, 1
	octave 5
	note C#, 1
	octave 4
	octave 3
	sound_call .sub_0
	note_type 8, 13, 6
	note F#, 4
	note F_, 4
	note F#, 4
	note_type 12, 13, 6
	note G#, 6
	note B_, 2
	note G#, 8
	note_type 12, 13, 4
	note C#, 4
	note_type 12, 13, 1
	note C#, 1
	note D#, 1
	note F_, 1
	note G_, 1
	note A#, 1
	note A_, 1
	note A#, 4
	note A#, 2
	duty_cycle 2
	note F_, 3
	note G_, 1
	note_type 12, 13, 4
	note G#, 5
	note_type 12, 13, 1
	note G_, 1
	note F_, 1
	note G_, 1
	note_type 12, 13, 4
	note G#, 2
	octave 5
	note C_, 2
	octave 4
	note_type 12, 13, 1
	note A#, 3
	note_type 12, 13, 4
	note G_, 1
	note D#, 8
	note_type 12, 13, 1
	note C_, 1
	note C#, 1
	note C_, 1
	note C#, 1
	note D#, 3
	note F_, 1
	note_type 12, 13, 4
	note G_, 8
	note_type 12, 13, 1
	note D#, 1
	note G_, 1
	note_type 12, 13, 4
	note A#, 2
	note_type 12, 13, 1
	note G#, 3
	note A#, 1
	octave 5
	note_type 12, 13, 4
	note C_, 12
	duty_cycle 3
	octave 4
	note_type 12, 13, 1
	note G#, 3
	note F_, 1
	note_type 12, 13, 4
	note G#, 6
	note F_, 2
	note G#, 2
	octave 5
	note C_, 2
	octave 4
	note_type 12, 13, 1
	note A#, 3
	octave 5
	note C_, 1
	octave 4
	note_type 12, 13, 4
	note A#, 8
	note_type 12, 13, 1
	note D#, 1
	note C#, 1
	note C_, 1
	note C#, 1
	note D#, 3
	note F_, 1
	note_type 12, 13, 4
	note G_, 6
	note_type 12, 13, 2
	note D#, 1
	note G_, 1
	note_type 12, 13, 4
	note A#, 4
	note_type 12, 13, 1
	note A_, 3
	note A#, 1
	octave 5
	note_type 12, 13, 4
	note C_, 10
	octave 4
	note_type 12, 13, 1
	note G#, 1
	octave 5
	note C_, 1
	note C#, 3
	note C_, 1
	octave 4
	note_type 12, 13, 4
	note A#, 8
	note G_, 1
	note G#, 1
	note A#, 1
	octave 5
	note C_, 1
	note_type 12, 13, 1
	note C#, 3
	note C_, 1
	octave 4
	note_type 12, 13, 4
	note A#, 10
	note_type 12, 13, 1
	note G#, 1
	note A#, 1
	note_type 12, 13, 7
	note A#, 16
	octave 3
	octave 2
	note_type 12, 13, 6
	note D#, 6
	octave 3
	note F#, 4
	octave 4
	note E_, 6
	octave 3
	sound_jump .main_loop
	sound_ret
.sub_0
	octave 3
	note_type 12, 13, 6
	note G#, 6
	octave 4
	note C_, 2
	note D#, 16
	sound_ret

Music_GymLeaderPinch_Ch3:
	octave 3
	note_type 6, 1, 9
	note D#, 1
	rest 1
	note D#, 1
	rest 1
	octave 2
	note_type 12, 1, 9
	note D#, 16
	note D#, 8
	; tied with previous note
	octave 3
.loop2:
	note_type 6, 1, 9
	note D#, 1
	rest 1
	sound_loop 8, .loop2
	note_type 12, 1, 9
	note G#, 4
	octave 4
	note D#, 1
	rest 1
	octave 3
	note G#, 4
	note D#, 2
	note G#, 2
	note D#, 2
	note G#, 4
	note D#, 1
	rest 1
	note G#, 4
	note_type 6, 1, 9
	note D#, 1
	rest 1
	note D#, 1
	rest 1
	note_type 12, 1, 9
	note G#, 4
	note G#, 4
	note_type 6, 1, 9
	note D#, 1
	rest 1
	note D#, 1
	rest 1
	note_type 12, 1, 9
	note G#, 4
	note D#, 2
	note G#, 2
	note D#, 2
	note D#, 1
	note D_, 1
	note_type 1, 1, 9
	note D#, 13
	note_type 12, 1, 9
	rest 1
	note G#, 1
	rest 1
	note D#, 1
	rest 1
.loop3:
	note_type 8, 1, 9
	note D#, 1
	rest 1
	sound_loop 6, .loop3
.main_loop:
	note_type 12, 1, 9
	sound_call .sub_0
	octave 2
	note A#, 4
	note E_, 2
	note A#, 2
	octave 3
	note C#, 4
	note D#, 2
	rest 2
	note E_, 6
	note_type 6, 1, 9
	note C#, 1
	rest 1
	note C#, 1
	rest 1
	note_type 12, 1, 9
	note F#, 1
	rest 1
	note F#, 1
	rest 1
	note_type 8, 1, 9
	note F#, 1
	rest 1
	note F#, 1
	rest 1
	note E_, 1
	rest 1
	note_type 12, 1, 9
	sound_call .sub_0
	note E_, 4
	note C#, 2
	note E_, 4
	note C#, 2
	note E_, 2
	note C#, 2
	note F#, 4
	octave 2
	note A#, 2
	octave 3
	note F#, 6
	note E_, 4
	sound_call .sub_0
	note D#, 8
	note D#, 4
	note D#, 1
	note F#, 1
	note C#, 1
	note D#, 1
	note E_, 6
	note D#, 1
	note E_, 1
	note F#, 1
	rest 1
	note F#, 1
	rest 1
	note_type 8, 1, 9
	note F#, 2
	note D#, 2
	note A#, 2
	note_type 12, 1, 9
	sound_call .sub_0
	note G#, 4
	note D#, 2
	note G#, 4
	note D#, 2
	note G#, 2
	note D#, 2
	note E_, 4
	note G#, 1
	note A#, 1
	note F_, 1
	note G_, 1
	note F#, 1
	note F_, 1
	note F#, 2
	rest 2
	note F#, 2
	note C#, 4
	octave 2
	note G#, 1
	rest 1
	octave 3
	note C#, 4
	octave 2
	note G#, 1
	rest 1
	octave 3
	note C#, 2
	octave 2
	note G#, 2
	sound_call .sub_1
	octave 3
	note F_, 4
	note E_, 4
	note D#, 4
	note D_, 4
	octave 3
	note C#, 4
	octave 2
	note G#, 1
	rest 1
	octave 3
	note C#, 4
	octave 2
	note G#, 2
	octave 3
	note C#, 2
	octave 2
	note G#, 2
	sound_call .sub_1
	octave 3
	note F_, 4
	note C_, 4
	note A_, 4
	octave 4
	note C_, 4
	octave 3
	note C#, 4
	octave 2
	note G#, 1
	rest 1
	octave 3
	note C#, 4
	octave 2
	note G#, 2
	octave 3
	note G#, 2
	octave 2
	note G#, 2
	note A#, 4
	note F_, 1
	rest 1
	octave 3
	note F_, 4
	note D_, 2
	note G#, 2
	octave 2
	note A#, 2
	octave 3
	note D#, 4
	octave 2
	note A#, 2
	octave 3
	note D#, 4
	octave 2
	note A#, 2
	octave 3
	note G_, 2
	note_type 6, 1, 9
	note D#, 1
	rest 1
	note D#, 1
	rest 1
	note_type 12, 1, 9
	note D#, 12
	note_type 6, 1, 9
	note D#, 1
	rest 1
	note D#, 1
	rest 1
	note D#, 1
	rest 1
	note D#, 1
	rest 1
	sound_jump .main_loop
	sound_ret
.sub_0
	note G#, 4
	note D#, 2
	note G#, 4
	note D#, 2
	note G#, 2
	note D#, 2
	note F#, 4
	note C#, 2
	note F#, 4
	note C#, 2
	note F#, 2
	note C#, 2
	sound_ret
.sub_1
	octave 3
	note D#, 4
	octave 2
	note A#, 1
	rest 1
	octave 3
	note D#, 4
	octave 2
	note A#, 1
	rest 1
	octave 3
	note D#, 2
	octave 2
	note A#, 2
	octave 3
	note C_, 4
	octave 2
	note G_, 1
	rest 1
	octave 3
	note C_, 4
	octave 2
	note G_, 1
	rest 1
	octave 3
	note C_, 2
	octave 2
	note G_, 2
	sound_ret
