	tilepal 0, BROWN, YELLOW, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, RED, RED, RED, RED
	tilepal 0, GRAY, YELLOW, GRAY, GRAY, GREEN, GREEN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, GREEN, GREEN, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, GRAY, GRAY
