	tilepal 0, GRAY, BROWN, BROWN, RED, GRAY, GRAY, GRAY, RED
	tilepal 0, RED, RED, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, WATER, ROOF, BROWN, BROWN
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, RED, RED, BROWN, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, ROOF, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, RED, RED, RED, RED, RED
	tilepal 1, BROWN, BROWN, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN
