'''
Tools used in configure.py
'''

import shutil
from pathlib import Path
import sys
import subprocess
import shlex

def find_sys_tool(name: str) -> str:
  found = shutil.which(name)
  if found and len(found) > 0:
    return found
  return None

def find_tool(tools_dir: Path, name: str) -> str:
  candidate = tools_dir / name
  if candidate.exists():
    return candidate
  # Fall back to PATH
  return find_sys_tool(name)

def scan_file(scan_includes: str, path: Path, source_root: Path) -> list[str]:
  result = subprocess.run(
    [scan_includes, str(path)],
    capture_output=True, text=True, check=True,
    cwd=source_root,)
  deps = result.stdout.strip().split()
  return [d for d in deps if d]

NINJA_HEADER = '''\
# generated by utils/configure.py, do not edit
ninja_required_version = 1.5

'''

def Rule(name: str, command: str, description: str = '', generator: bool = False) -> str:
  lines = [f'rule {name}', f'  command = {command}']
  if description:
    lines.append(f'  description = {description}')
  if generator:
      lines.append(f'  generator = 1')
  return '\n'.join(lines) + '\n'

def Target(output: list[str], rule: str, inputs: list[str],
        implicit: list[str] = None, implicit_out: list[str] = None,
        order_only: list[str] = None, variables: dict = None) -> str:
  outs = ' '.join(shlex.quote(str(i)) for i in output)
  if implicit_out:
    outs += ' | ' + ' '.join(shlex.quote(i) for i in implicit_out)
  ins = ' '.join(shlex.quote(str(i)) for i in inputs)
  line = f'build {outs}: {rule} {ins}'
  if implicit:
    line += ' | ' + ' '.join(shlex.quote(i) for i in implicit)
  elif order_only:
    line += ' || ' + ' '.join(shlex.quote(i) for i in order_only)
  lines = [line]
  if variables:
    for k, v in variables.items():
      lines.append(f'  {k} = {v}')
  return '\n'.join(lines) + '\n'

def scan_sources(scan_includes, source_dir, sources):
  per_deps = {}
  all_deps = []
  for asm in sources:
    deps = scan_file(scan_includes, source_dir / asm, source_dir)
    per_deps[asm] = deps
    for d in deps:
      if d not in all_deps:
        all_deps.append(d)
  return per_deps, all_deps

def resolve_implicit(deps, targets, build_dir, source_dir):
  implicit = []
  for dep in deps:
    if dep in targets:
      if targets[dep] != {} or dep == 'git_version.asm':
        implicit.append(str(build_dir / dep))
      else:
        implicit.append(str(source_dir / dep))
  return implicit

def emit_asm_objects(ln, source_dir, build_dir, per_deps, targets, variants):
  """
  variants: list of (suffix, rgbasm_flags)
  e.g. [('', None), ('_debug', '-D_DEBUG'), ('_gbs', '-D_GBS')]
  Returns one list of outputs per variant.
  """
  all_objects = [[] for _ in variants]
  for asm in per_deps:
    stem     = Path(asm).stem
    source   = str(source_dir / asm)
    implicit = resolve_implicit(per_deps[asm], targets, build_dir, source_dir) or None
    for idx, (suffix, flags) in enumerate(variants):
      output = str(build_dir / f'{stem}{suffix}.o')
      variables = {'rgbasm': flags} if flags else None
      ln += [Target([output], 'ASM', [source], implicit=implicit, variables=variables)]
      all_objects[idx].append(output)
  return all_objects

def write_ninja(
  build_dir: Path, source_root: Path, tools_dir: Path,
  tools: dict[str, str], targets: dict[str, dict],
  per_asm_deps: dict[str, list[str]],
  per_gbs_deps: dict[str, list[str]],
):
  build_dir.mkdir(parents=True, exist_ok=True)
  ninja_path = build_dir / 'build.ninja'

  ln = [NINJA_HEADER]

  # variables
  ln += ['source_root = %s\n' % (source_root)]
  ln += ['build_root = %s\n' % (build_dir)]

  # generation rules
  ln += [Rule('2BPP',
    '%s $rgbgfx -o $out $in' % (tools['rgbgfx']),
    description='2BPP $out',)]
  
  ln += [Rule('2BPP_GFX',
    '%s $rgbgfx -o $out $in && %s $tools_gfx -o $out $out' % (tools['rgbgfx'],tools['gfx']),
    description='2BPP+ $out',)]
  
  ln += [Rule('1BPP',
    '%s $rgbgfx -d1 -o $out $in' % (tools['rgbgfx']),
    description='1BPP $out',)]
  
  ln += [Rule('1BPP_GFX',
    '%s $rgbgfx -d1 -o $out $in && %s $tools_gfx -d1 -o $out $out' % (tools['rgbgfx'],tools['gfx']),
    description='1BPP+ $out',)]
  
  ln += [Rule('GBCPAL',
    '%s -p $out $in' % (tools['rgbgfx']),
    description='GBCPAL $out',)]
  
  ln += [Rule('LZ',
    '%s -- $in $out' % (tools['lzcomp']),
    description='LZ $out',)]
  
  ln += [Rule('DIMENSIONS',
    '%s $in $out' % (tools['png_dimensions']),
    description='DIMENSIONS $out',)]
  
  ln += [Rule('PKMN_ANIM_TMAP',
    '%s -t $out $in' % (tools['pokemon_animation_graphics']),
    description='PKMN_ANIM_TMAP $out',)]
  
  ln += [Rule('PKMN_STATIC',
    '%s -s $out $in' % (tools['pokemon_animation_graphics']),
    description='PKMN_STATIC $out',)]
  
  ln += [Rule('PKMN_ANIMATED',
    '%s -a $out $in' % (tools['pokemon_animation_graphics']),
    description='PKMN_ANIMATED $out',)]
  
  ln += [Rule('PKMN_BITMASK',
    '%s -b $in > $out' % (tools['pokemon_animation']),
    description='PKMN_BITMASK $out',)]
  
  ln += [Rule('PKMN_FRAMES',
    '%s -f $in > $out' % (tools['pokemon_animation']),
    description='PKMN_FRAMES $out',)]
  
  ln += [Rule('CAT',
    'cat $in > $out',
    description='$in -> $out',)]
  
  ln += [Rule('ASM',
    '%s $rgbasm '
    '-i $source_root '
    '-i $build_root '
    '-L '
    '-o $out $in' % (tools['rgbasm']),
    description='ASM $out',)]
  
  ln += [Rule('LINK',
    '%s '
    '-n $symfile '
    '-m $mapfile '
    '-l $linkfile '
    '-o $out $in'
    ' && '
    '%s -Cjv -i BETA -k 01 -l 0x33 '
    '-m 0x10 -p 0 -r 3 -t PM_OCTOBER $out' % (
      tools['rgblink'],tools['rgbfix']),
    description='LINK $out',)]

  ln += [Rule('LINKGBS',
    '%s '
    '-n $symfile '
    '-m $mapfile '
    '-l $linkfile '
    '-o $out $in'
    ' && '
    '%s $out ' % (
      tools['rgblink'],tools['gbstrim']),
    description='LINKGBS $out',)]

  # keep rebuilding self
  ln += [Rule(
    'REGENERATE',
    f'python3 {source_root}/utils/configure.py '
    f'--tools-dir {tools_dir} '
    f'--source-dir {source_root} '
    f'--build-dir {build_dir}',
    description='Reconfiguring',
    generator=True
  )]
  ln += [Target(['build.ninja'], 'REGENERATE', [
    str(source_root / 'utils/configure.py'),
    str(source_root / 'utils/configure_targets.py'),
    str(source_root / 'utils/configure_utils.py'),
  ], implicit=[str(source_root / asm) for asm in per_asm_deps]+
  [str(source_root / asm) for asm in per_gbs_deps])]
  

  # special git version target, see `resolve_implict` for the effects
  ln += [Rule('GIT_INFO',
    'python3 $source_root/utils/git_version.py $out',
    description='GIT_INFO $out',)]
  ln += [Target(['always'], 'phony', [])]
  ln += [Target([str(build_dir /'git_version.asm')], 'GIT_INFO', [], implicit=['always'])]

  # generated asset build statements
  for dep, info in targets.items():
    if info != {}:
      # emulate the original makefile rule of
      # having `tools/gfx` run conditionally
      rule = info['rule']
      if rule in ['2BPP', '1BPP']:
        if info['flags'].get('tools_gfx', None):
          rule += '_GFX'
      (build_dir / dep / '..').resolve().mkdir(parents=True, exist_ok=True)
      # any non-absolute input is treated as part of the build dir
      tr_inputs = []
      for i in info['inputs']:
        ii = str(i)
        if ii[0] != '/':
          tr_inputs.append(str(build_dir / i))
        else:
          tr_inputs.append(ii)
      ln += [Target([str(build_dir / dep)], rule, tr_inputs, variables=info['flags'])]

  objects, objects_debug = emit_asm_objects(ln,
    source_root, build_dir,
    per_asm_deps, targets,
    variants=[('', None), ('_debug', '-D_DEBUG')])

  objects_gbs, = emit_asm_objects(ln,
    source_root, build_dir,
    per_gbs_deps, targets,
    variants=[('_gbs', '-D_GBS')])

  # link
  ln += [Target(['pokeoctober.gbc'], 'LINK', objects,
    implicit_out=[
    'pokeoctober.sym',
    'pokeoctober.map'],
    variables={
      'symfile': 'pokeoctober.sym',
      'mapfile': 'pokeoctober.map',
      'linkfile': str(source_root / 'pokeoctober.link')})]
  
  ln += [Target(['pokeoctober_debug.gbc'], 'LINK', objects_debug,
    implicit_out=[
    'pokeoctober_debug.sym',
    'pokeoctober_debug.map'],
    variables={
      'symfile': 'pokeoctober_debug.sym',
      'mapfile': 'pokeoctober_debug.map',
      'linkfile': str(source_root / 'pokeoctober.link')})]
  
  ln += [Target(['pokeoctober.gbs'], 'LINKGBS', objects_gbs,
    implicit_out=[
    'pokeoctober.gbs.sym',
    'pokeoctober.gbs.map'],
    variables={
      'symfile': 'pokeoctober.gbs.sym',
      'mapfile': 'pokeoctober.gbs.map',
      'linkfile': str(source_root / 'gbs.link')})]

  ln += ['default %s\n' % (shlex.quote('pokeoctober.gbc'))]

  ninja_path.write_text(''.join(ln))
  print(f'wrote {ninja_path}')

max_target_passes = 1000
def resolve_targets(all_deps: list[str], source_root: Path, match_fn) -> dict[str, dict]:
  '''
  Returns a dict: dep_path -> {rule, inputs (list of dep_path or source path), flags}
  Iterates until no new targets can be resolved (fixed point).
  Inputs that are themselves generated are resolved recursively.
  '''
  targets = {}
  unresolved = list(all_deps)

  for pp in range(max_target_passes):
    print(f'Pass {pp}: {len(targets)} resolved, {len(unresolved)} remaining', file=sys.stderr)
    if not unresolved:
      break
    newly_resolved = []

    for dep in unresolved:
      r, new_inputs = match_fn(str(dep), targets, source_root)
      if r is None:
        if new_inputs:
          for i in new_inputs:
            if i not in targets and not Path(i).exists() and i not in unresolved:
              unresolved.append(i)
      else:
        targets[dep] = r
        newly_resolved.append(dep)
    
    for dep in newly_resolved:
      unresolved.remove(dep)
    
    if not newly_resolved:
      break
  
  for dep in unresolved:
    print(f'ERROR: Could not resolve inputs for: {dep}')

  return targets

def make(source_root: Path, targets: dict, rule, *inputs, flags: dict=None):
  # Return None if any input not yet resolved
  for i in inputs:
    ready = i in targets or Path(i).exists()
    if not ready:
      return None
  return {'rule': rule, 'inputs': list(inputs), 'flags': flags or {}}