'''
Tools used in configure.py
'''

import shutil
from pathlib import Path
import sys
import subprocess
import shlex

def find_sys_tool(name: str) -> str:
  found = shutil.which(name)
  if found and len(found) > 0:
    return found
  return None

def find_tool(tools_dir: Path, name: str) -> str:
  candidate = tools_dir / name
  if candidate.exists():
    return candidate
  # Fall back to PATH
  return find_sys_tool(name)

def scan_file(scan_includes: str, path: Path) -> list[str]:
  result = subprocess.run(
    [scan_includes, str(path)],
    capture_output=True, text=True, check=True,)
  deps = result.stdout.strip().split()
  return [d for d in deps if d]

NINJA_HEADER = '''\
# generated by utils/configure.py, do not edit
ninja_required_version = 1.5

'''

def Rule(out: list[str], name: str, command: str, description: str = '', generator: bool = False) -> str:
  lines = [f'rule {name}', f'  command = {command}']
  if description:
    lines.append(f'  description = {description}')
  if generator:
      lines.append(f'  generator = 1')
  out.append('\n'.join(lines) + '\n')

def Target(out: list[str], output: list[str], rule: str, inputs: list[str],
        implicit: list[str] = None, implicit_out: list[str] = None,
        order_only: list[str] = None, variables: dict = None) -> str:
  outs = ' '.join(shlex.quote(str(i)) for i in output)
  if implicit_out:
    outs += ' | ' + ' '.join(shlex.quote(i) for i in implicit_out)
  ins = ' '.join(shlex.quote(str(i)) for i in inputs)
  line = f'build {outs}: {rule} {ins}'
  if implicit:
    line += ' | ' + ' '.join(shlex.quote(i) for i in implicit)
  elif order_only:
    line += ' || ' + ' '.join(shlex.quote(i) for i in order_only)
  lines = [line]
  if variables:
    for k, v in variables.items():
      lines.append(f'  {k} = {v}')
  out.append('\n'.join(lines) + '\n')

def write_ninja(
  build_dir: Path,
  source_root: Path,
  tools_dir: Path,
  tools: dict[str, str],
  targets: dict[str, dict],
  per_asm_deps: dict[str, list[str]],
  asm_sources: list[str],
):
  build_dir.mkdir(parents=True, exist_ok=True)
  ninja_path = build_dir / 'build.ninja'

  ln = [NINJA_HEADER]

  # variables
  ln.append(f'source_root = {source_root}\n')
  ln.append(f'build_root = {build_dir}\n\n')

  # generation rules
  Rule(ln, '2BPP',
    '%s $rgbgfx -o $out $in' % (tools['rgbgfx']),
    description='2BPP $out',)
  
  Rule(ln, '2BPP_GFX',
    '%s $rgbgfx -o $out $in && %s $tools_gfx -o $out $out' % (tools['rgbgfx'],tools['gfx']),
    description='2BPP+ $out',)
  
  Rule(ln, '1BPP',
    '%s $rgbgfx -d1 -o $out $in' % (tools['rgbgfx']),
    description='1BPP $out',)
  
  Rule(ln, '1BPP_GFX',
    '%s $rgbgfx -d1 -o $out $in && %s $tools_gfx -d1 -o $out $out' % (tools['rgbgfx'],tools['gfx']),
    description='1BPP+ $out',)
  
  Rule(ln, 'GBCPAL',
    '%s -p $out $in' % (tools['rgbgfx']),
    description='GBCPAL $out',)
  
  Rule(ln, 'LZ',
    '%s -- $in $out' % (tools['lzcomp']),
    description='LZ $out',)
  
  Rule(ln, 'DIMENSIONS',
    '%s $in $out' % (tools['png_dimensions']),
    description='DIMENSIONS $out',)
  
  Rule(ln, 'PKMN_ANIM_TMAP',
    '%s -t $out $in' % (tools['pokemon_animation_graphics']),
    description='PKMN_ANIM_TMAP $out',)
  
  Rule(ln, 'PKMN_STATIC',
    '%s -s $out $in' % (tools['pokemon_animation_graphics']),
    description='PKMN_STATIC $out',)
  
  Rule(ln, 'PKMN_ANIMATED',
    '%s -a $out $in' % (tools['pokemon_animation_graphics']),
    description='PKMN_ANIMATED $out',)
  
  Rule(ln, 'PKMN_BITMASK',
    '%s -b $in > $out' % (tools['pokemon_animation']),
    description='PKMN_BITMASK $out',)
  
  Rule(ln, 'PKMN_FRAMES',
    '%s -f $in > $out' % (tools['pokemon_animation']),
    description='PKMN_FRAMES $out',)
  
  Rule(ln, 'CAT',
    'cat $in > $out',
    description='$in -> $out',)
  
  Rule(ln, 'ASM',
    '%s $rgbasm '
    '-i $source_root '
    '-i $build_root '
    '-L '
    '-o $out $in' % (tools['rgbasm']),
    description='ASM $out',)
  
  Rule(ln, 'LINK',
    '%s '
    '-n $symfile '
    '-m $mapfile '
    '-l $linkfile '
    '-o $out $in'
    ' && '
    '%s -Cjv -i BETA -k 01 -l 0x33 '
    '-m 0x10 -p 0 -r 3 -t PM_OCTOBER $out' % (
      tools['rgblink'],tools['rgbfix']),
    description='LINK $out',)

  # keep rebuilding self
  # Rule(ln, 
  #   'REGENERATE',
  #   f'python3 {source_root}/utils/configure.py '
  #   f'--tools-dir {tools_dir} '
  #   f'--source-dir {source_root} '
  #   f'--build-dir {build_dir}',
  #   description='Reconfiguring',
  #   generator=True
  # ))
  # Target(ln, ['build.ninja'], 'REGENERATE', [
  #   str(source_root / 'utils/configure.py'),
  #   str(source_root / 'utils/configure_targets.py'),
  #   str(source_root / 'utils/configure_utils.py'),
  # ]))
  

  # special git version target
  Rule(ln, 'GIT_INFO',
    'python3 $source_root/utils/git_version.py $out',
    description='GIT_INFO $out',)
  Target(ln, ['always'], 'phony', [])
  Target(ln, [str(build_dir /'git_version.asm')], 'GIT_INFO', [], implicit=['always'])

  # generated asset build statements
  for dep, info in targets.items():
    if info != {}:
      # emulate the original makefile rule of
      # having `tools/gfx` run conditionally
      rule = info['rule']
      if rule in ['2BPP', '1BPP']:
        if info['flags'].get('tools_gfx', None):
          rule += '_GFX'
      (build_dir / dep / '..').resolve().mkdir(parents=True, exist_ok=True)
      # any non-absolute input is treated as part of the build dir
      tr_inputs = []
      for i in info['inputs']:
        ii = str(i)
        if ii[0] != '/':
          tr_inputs.append(str(build_dir / i))
        else:
          tr_inputs.append(ii)
      Target(ln, [str(build_dir / dep)], rule, tr_inputs, variables=info['flags'])

  # -- ASM object files
  objects = []
  for asm in asm_sources:
    stem   = Path(asm).stem
    output = str(build_dir / f'{stem}.o')
    source = str(source_root / asm)
    implicit = []
    for dep in per_asm_deps.get(asm, []):
      if dep in targets:
        if targets[dep] != {}:
          implicit.append(str(build_dir / dep))
        else:
          # part of the above exception
          if dep == 'git_version.asm':
            implicit.append(str(build_dir / dep))
          else:
            implicit.append(str(source_root / dep))
    Target(ln, [output], 'ASM', [source], implicit=implicit or None)
    objects.append(output)

  # link
  rom = ['pokeoctober.gbc']
  symfile = str(build_dir / 'pokeoctober.sym')
  mapfile = str(build_dir / 'pokeoctober.map')
  linkfile = str(source_root / 'pokeoctober.link')
  Target(ln, rom, 'LINK', objects,
    implicit_out=[
    'pokeoctober.sym',
    'pokeoctober.map'],
    variables={
      'symfile': symfile,
      'mapfile': mapfile,
      'linkfile': linkfile})

  ln.append(f'\ndefault {shlex.quote('pokeoctober.gbc')}\n')

  ninja_path.write_text(''.join(ln))
  print(f'wrote {ninja_path}')

max_target_passes = 1000
def resolve_targets(all_deps: list[str], source_root: Path, match_fn) -> dict[str, dict]:
  '''
  Returns a dict: dep_path -> {rule, inputs (list of dep_path or source path), flags}
  Iterates until no new targets can be resolved (fixed point).
  Inputs that are themselves generated are resolved recursively.
  '''
  targets = {}
  unresolved = list(all_deps)

  for pp in range(max_target_passes):
    print(f'Pass {pp}: {len(targets)} resolved, {len(unresolved)} remaining', file=sys.stderr)
    if not unresolved:
      break
    newly_resolved = []

    for dep in unresolved:
      r = match_fn(str(dep), targets, source_root)[0]
      if r is not None:
        targets[dep] = r
        newly_resolved.append(dep)
      elif r is None:
        info = match_fn(dep, targets, source_root)[1]
        if info:
          for i in info:
            if i not in targets and not Path(i).exists() and i not in unresolved:
              unresolved.append(i)
    
    for dep in newly_resolved:
      unresolved.remove(dep)
    
    if not newly_resolved:
      break
  
  for dep in unresolved:
    print(f'ERROR: Could not resolve inputs for: {dep}')

  return targets

def input_ready(source_root: Path, targets: dict, path: str) -> bool:
  if path in targets:
    return True
  return Path(i).exists()

def make(source_root: Path, targets: dict, rule, *inputs, flags: dict=None):
  # Return None if any input not yet resolved
  for i in inputs:
    ready = i in targets or Path(i).exists()
    if not ready:
      return None
  return {'rule': rule, 'inputs': list(inputs), 'flags': flags or {}}