INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in pokecrystal.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"

INCLUDE "checks/pokemon_pics.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "sheets/generated/trainer/pic_pointers.gen.asm"



SECTION "_HoOhFrontpic", ROMX
HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.static.2bpp.lz"
SECTION "_MachampFrontpic", ROMX
MachampFrontpic:     INCBIN "gfx/pokemon/machamp/front.static.2bpp.lz"
SECTION "_NinetalesFrontpic", ROMX
NinetalesFrontpic:   INCBIN "gfx/pokemon/ninetales/front.static.2bpp.lz"
SECTION "_FeraligatrFrontpic", ROMX
FeraligatrFrontpic:  INCBIN "gfx/pokemon/feraligatr/front.static.2bpp.lz"
SECTION "_NidokingFrontpic", ROMX
NidokingFrontpic:    INCBIN "gfx/pokemon/nidoking/front.static.2bpp.lz"
SECTION "_RaikouFrontpic", ROMX
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.static.2bpp.lz"
SECTION "_LugiaFrontpic", ROMX
LugiaFrontpic:       INCBIN "gfx/pokemon/lugia/front.static.2bpp.lz"
SECTION "_ArticunoFrontpic", ROMX
ArticunoFrontpic:    INCBIN "gfx/pokemon/articuno/front.static.2bpp.lz"
SECTION "_TaurosFrontpic", ROMX
TaurosFrontpic:      INCBIN "gfx/pokemon/tauros/front.static.2bpp.lz"
SECTION "_VenusaurFrontpic", ROMX
VenusaurFrontpic:    INCBIN "gfx/pokemon/venusaur/front.static.2bpp.lz"
SECTION "_EnteiFrontpic", ROMX
EnteiFrontpic:       INCBIN "gfx/pokemon/entei/front.static.2bpp.lz"
SECTION "_SuicuneFrontpic", ROMX
SuicuneFrontpic:     INCBIN "gfx/pokemon/suicune/front.static.2bpp.lz"
SECTION "_TyphlosionFrontpic", ROMX
TyphlosionFrontpic:  INCBIN "gfx/pokemon/typhlosion/front.static.2bpp.lz"



SECTION "_BlastoiseFrontpic", ROMX
BlastoiseFrontpic:   INCBIN "gfx/pokemon/blastoise/front.static.2bpp.lz"
SECTION "_RapidashFrontpic", ROMX
RapidashFrontpic:    INCBIN "gfx/pokemon/rapidash/front.static.2bpp.lz"
SECTION "_MeganiumFrontpic", ROMX
MeganiumFrontpic:    INCBIN "gfx/pokemon/meganium/front.static.2bpp.lz"
SECTION "_NidoqueenFrontpic", ROMX
NidoqueenFrontpic:   INCBIN "gfx/pokemon/nidoqueen/front.static.2bpp.lz"
SECTION "_HitmonleeFrontpic", ROMX
HitmonleeFrontpic:   INCBIN "gfx/pokemon/hitmonlee/front.static.2bpp.lz"
SECTION "_ScizorFrontpic", ROMX
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.static.2bpp.lz"
SECTION "_BeedrillFrontpic", ROMX
BeedrillFrontpic:    INCBIN "gfx/pokemon/beedrill/front.static.2bpp.lz"
SECTION "_ArcanineFrontpic", ROMX
ArcanineFrontpic:    INCBIN "gfx/pokemon/arcanine/front.static.2bpp.lz"
SECTION "_TyranitarFrontpic", ROMX
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.static.2bpp.lz"
SECTION "_MoltresFrontpic", ROMX
MoltresFrontpic:     INCBIN "gfx/pokemon/moltres/front.static.2bpp.lz"
SECTION "_ZapdosFrontpic", ROMX
ZapdosFrontpic:      INCBIN "gfx/pokemon/zapdos/front.static.2bpp.lz"
SECTION "_ArbokFrontpic", ROMX
ArbokFrontpic:       INCBIN "gfx/pokemon/arbok/front.static.2bpp.lz"
SECTION "_MewtwoFrontpic", ROMX
MewtwoFrontpic:      INCBIN "gfx/pokemon/mewtwo/front.static.2bpp.lz"
SECTION "_FearowFrontpic", ROMX
FearowFrontpic:      INCBIN "gfx/pokemon/fearow/front.static.2bpp.lz"
SECTION "_CharizardFrontpic", ROMX
CharizardFrontpic:   INCBIN "gfx/pokemon/charizard/front.static.2bpp.lz"
SECTION "_QuilavaFrontpic", ROMX
QuilavaFrontpic:     INCBIN "gfx/pokemon/quilava/front.static.2bpp.lz"



SECTION "_SteelixFrontpic", ROMX
SteelixFrontpic:     INCBIN "gfx/pokemon/steelix/front.static.2bpp.lz"
SECTION "_AlakazamFrontpic", ROMX
AlakazamFrontpic:    INCBIN "gfx/pokemon/alakazam/front.static.2bpp.lz"
SECTION "_GyaradosFrontpic", ROMX
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.static.2bpp.lz"
SECTION "_KangaskhanFrontpic", ROMX
KangaskhanFrontpic:  INCBIN "gfx/pokemon/kangaskhan/front.static.2bpp.lz"
SECTION "_RhydonFrontpic", ROMX
RhydonFrontpic:      INCBIN "gfx/pokemon/rhydon/front.static.2bpp.lz"
SECTION "_GolduckFrontpic", ROMX
GolduckFrontpic:     INCBIN "gfx/pokemon/golduck/front.static.2bpp.lz"
SECTION "_RhyhornFrontpic", ROMX
RhyhornFrontpic:     INCBIN "gfx/pokemon/rhyhorn/front.static.2bpp.lz"
SECTION "_PidgeotFrontpic", ROMX
PidgeotFrontpic:     INCBIN "gfx/pokemon/pidgeot/front.static.2bpp.lz"
SECTION "_SlowbroFrontpic", ROMX
SlowbroFrontpic:     INCBIN "gfx/pokemon/slowbro/front.static.2bpp.lz"
SECTION "_ButterfreeFrontpic", ROMX
ButterfreeFrontpic:  INCBIN "gfx/pokemon/butterfree/front.static.2bpp.lz"
SECTION "_WeezingFrontpic", ROMX
WeezingFrontpic:     INCBIN "gfx/pokemon/weezing/front.static.2bpp.lz"
SECTION "_CloysterFrontpic", ROMX
CloysterFrontpic:    INCBIN "gfx/pokemon/cloyster/front.static.2bpp.lz"
SECTION "_AirmorFrontpic", ROMX
AirmorFrontpic:      INCBIN "gfx/pokemon/airmor/front.static.2bpp.lz"
SECTION "_DewgongFrontpic", ROMX
DewgongFrontpic:     INCBIN "gfx/pokemon/dewgong/front.static.2bpp.lz"
SECTION "_VictreebelFrontpic", ROMX
VictreebelFrontpic:  INCBIN "gfx/pokemon/victreebel/front.static.2bpp.lz"
SECTION "_RaichuFrontpic", ROMX
RaichuFrontpic:      INCBIN "gfx/pokemon/raichu/front.static.2bpp.lz"
SECTION "_PrimeapeFrontpic", ROMX
PrimeapeFrontpic:    INCBIN "gfx/pokemon/primeape/front.static.2bpp.lz"
SECTION "_OmastarBackpic", ROMX
OmastarBackpic:      INCBIN "gfx/pokemon/omastar/back.2bpp.lz"



SECTION "_DodrioFrontpic", ROMX
DodrioFrontpic:      INCBIN "gfx/pokemon/dodrio/front.static.2bpp.lz"
SECTION "_SlowkingFrontpic", ROMX
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.static.2bpp.lz"
SECTION "_OnixFrontpic", ROMX
OnixFrontpic:        INCBIN "gfx/pokemon/onix/front.static.2bpp.lz"
SECTION "_BlisseyFrontpic", ROMX
BlisseyFrontpic:     INCBIN "gfx/pokemon/blissey/front.static.2bpp.lz"
SECTION "_MachokeFrontpic", ROMX
MachokeFrontpic:     INCBIN "gfx/pokemon/machoke/front.static.2bpp.lz"
SECTION "_DragoniteFrontpic", ROMX
DragoniteFrontpic:   INCBIN "gfx/pokemon/dragonite/front.static.2bpp.lz"
SECTION "_PoliwrathFrontpic", ROMX
PoliwrathFrontpic:   INCBIN "gfx/pokemon/poliwrath/front.static.2bpp.lz"
SECTION "_ScytherFrontpic", ROMX
ScytherFrontpic:     INCBIN "gfx/pokemon/scyther/front.static.2bpp.lz"
SECTION "_AerodactylFrontpic", ROMX
AerodactylFrontpic:  INCBIN "gfx/pokemon/aerodactyl/front.static.2bpp.lz"
SECTION "_SeakingFrontpic", ROMX
SeakingFrontpic:     INCBIN "gfx/pokemon/seaking/front.static.2bpp.lz"
SECTION "_MukFrontpic", ROMX
MukFrontpic:         INCBIN "gfx/pokemon/muk/front.static.2bpp.lz"
SECTION "_CroconawFrontpic", ROMX
CroconawFrontpic:    INCBIN "gfx/pokemon/croconaw/front.static.2bpp.lz"
SECTION "_HypnoFrontpic", ROMX
HypnoFrontpic:       INCBIN "gfx/pokemon/hypno/front.static.2bpp.lz"
SECTION "_NidorinoFrontpic", ROMX
NidorinoFrontpic:    INCBIN "gfx/pokemon/nidorino/front.static.2bpp.lz"
SECTION "_SandslashFrontpic", ROMX
SandslashFrontpic:   INCBIN "gfx/pokemon/sandslash/front.static.2bpp.lz"
SECTION "_JolteonFrontpic", ROMX
JolteonFrontpic:     INCBIN "gfx/pokemon/jolteon/front.static.2bpp.lz"
SECTION "_DonphanFrontpic", ROMX
DonphanFrontpic:     INCBIN "gfx/pokemon/donphan/front.static.2bpp.lz"
SECTION "_PinsirFrontpic", ROMX
PinsirFrontpic:      INCBIN "gfx/pokemon/pinsir/front.static.2bpp.lz"
SECTION "_UnownEFrontpic", ROMX
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.static.2bpp.lz"



SECTION "_GolbatFrontpic", ROMX
GolbatFrontpic:      INCBIN "gfx/pokemon/golbat/front.static.2bpp.lz"
SECTION "_KinglerFrontpic", ROMX
KinglerFrontpic:     INCBIN "gfx/pokemon/kingler/front.static.2bpp.lz"
SECTION "_ExeggcuteFrontpic", ROMX
ExeggcuteFrontpic:   INCBIN "gfx/pokemon/exeggcute/front.static.2bpp.lz"
SECTION "_MagcargoFrontpic", ROMX
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.static.2bpp.lz"
SECTION "_PersianFrontpic", ROMX
PersianFrontpic:     INCBIN "gfx/pokemon/persian/front.static.2bpp.lz"
SECTION "_StantlerFrontpic", ROMX
StantlerFrontpic:    INCBIN "gfx/pokemon/stantler/front.static.2bpp.lz"
SECTION "_RaticateFrontpic", ROMX
RaticateFrontpic:    INCBIN "gfx/pokemon/raticate/front.static.2bpp.lz"
SECTION "_VenomothFrontpic", ROMX
VenomothFrontpic:    INCBIN "gfx/pokemon/venomoth/front.static.2bpp.lz"
SECTION "_PolitoedFrontpic", ROMX
PolitoedFrontpic:    INCBIN "gfx/pokemon/politoed/front.static.2bpp.lz"
SECTION "_ElectabuzzFrontpic", ROMX
ElectabuzzFrontpic:  INCBIN "gfx/pokemon/electabuzz/front.static.2bpp.lz"
SECTION "_MantineFrontpic", ROMX
MantineFrontpic:     INCBIN "gfx/pokemon/mantine/front.static.2bpp.lz"
SECTION "_LickitungFrontpic", ROMX
LickitungFrontpic:   INCBIN "gfx/pokemon/lickitung/front.static.2bpp.lz"
SECTION "_KingdraFrontpic", ROMX
KingdraFrontpic:     INCBIN "gfx/pokemon/kingdra/front.static.2bpp.lz"
SECTION "_CharmeleonFrontpic", ROMX
CharmeleonFrontpic:  INCBIN "gfx/pokemon/charmeleon/front.static.2bpp.lz"
SECTION "_KadabraFrontpic", ROMX
KadabraFrontpic:     INCBIN "gfx/pokemon/kadabra/front.static.2bpp.lz"
SECTION "_ExeggutorFrontpic", ROMX
ExeggutorFrontpic:   INCBIN "gfx/pokemon/exeggutor/front.static.2bpp.lz"
SECTION "_GastlyFrontpic", ROMX
GastlyFrontpic:      INCBIN "gfx/pokemon/gastly/front.static.2bpp.lz"
SECTION "_AzumarillFrontpic", ROMX
AzumarillFrontpic:   INCBIN "gfx/pokemon/azumarill/front.static.2bpp.lz"
SECTION "_ParasectFrontpic", ROMX
ParasectFrontpic:    INCBIN "gfx/pokemon/parasect/front.static.2bpp.lz"
SECTION "_MrMimeFrontpic", ROMX
MrMimeFrontpic:      INCBIN "gfx/pokemon/mr__mime/front.static.2bpp.lz"
SECTION "_HeracrossFrontpic", ROMX
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.static.2bpp.lz"



SECTION "_AriadosFrontpic", ROMX
AriadosFrontpic:     INCBIN "gfx/pokemon/ariados/front.static.2bpp.lz"
SECTION "_NoctowlFrontpic", ROMX
NoctowlFrontpic:     INCBIN "gfx/pokemon/noctowl/front.static.2bpp.lz"
SECTION "_WartortleFrontpic", ROMX
WartortleFrontpic:   INCBIN "gfx/pokemon/wartortle/front.static.2bpp.lz"
SECTION "_LaprasFrontpic", ROMX
LaprasFrontpic:      INCBIN "gfx/pokemon/lapras/front.static.2bpp.lz"
SECTION "_GolemFrontpic", ROMX
GolemFrontpic:       INCBIN "gfx/pokemon/golem/front.static.2bpp.lz"
SECTION "_PoliwhirlFrontpic", ROMX
PoliwhirlFrontpic:   INCBIN "gfx/pokemon/poliwhirl/front.static.2bpp.lz"
SECTION "_UrsaringFrontpic", ROMX
UrsaringFrontpic:    INCBIN "gfx/pokemon/ursaring/front.static.2bpp.lz"
SECTION "_HoundoomFrontpic", ROMX
HoundoomFrontpic:    INCBIN "gfx/pokemon/houndoom/front.static.2bpp.lz"
SECTION "_KabutopsFrontpic", ROMX
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.static.2bpp.lz"
SECTION "_AmpharosFrontpic", ROMX
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.static.2bpp.lz"
SECTION "_NidorinaFrontpic", ROMX
NidorinaFrontpic:    INCBIN "gfx/pokemon/nidorina/front.static.2bpp.lz"
SECTION "_FlareonFrontpic", ROMX
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.static.2bpp.lz"
SECTION "_VileplumeFrontpic", ROMX
VileplumeFrontpic:   INCBIN "gfx/pokemon/vileplume/front.static.2bpp.lz"
SECTION "_BayleefFrontpic", ROMX
BayleefFrontpic:     INCBIN "gfx/pokemon/bayleef/front.static.2bpp.lz"
SECTION "_MagmarFrontpic", ROMX
MagmarFrontpic:      INCBIN "gfx/pokemon/magmar/front.static.2bpp.lz"
SECTION "_TentacruelFrontpic", ROMX
TentacruelFrontpic:  INCBIN "gfx/pokemon/tentacruel/front.static.2bpp.lz"
SECTION "_ElekidFrontpic", ROMX
ElekidFrontpic:      INCBIN "gfx/pokemon/elekid/front.static.2bpp.lz"
SECTION "_JumpluffFrontpic", ROMX
JumpluffFrontpic:    INCBIN "gfx/pokemon/jumpluff/front.static.2bpp.lz"
SECTION "_MarowakFrontpic", ROMX
MarowakFrontpic:     INCBIN "gfx/pokemon/marowak/front.static.2bpp.lz"
SECTION "_VulpixFrontpic", ROMX
VulpixFrontpic:      INCBIN "gfx/pokemon/vulpix/front.static.2bpp.lz"
SECTION "_GligarFrontpic", ROMX
GligarFrontpic:      INCBIN "gfx/pokemon/gligar/front.static.2bpp.lz"
SECTION "_DunsparceFrontpic", ROMX
DunsparceFrontpic:   INCBIN "gfx/pokemon/dunsparce/front.static.2bpp.lz"



SECTION "_VaporeonFrontpic", ROMX
VaporeonFrontpic:    INCBIN "gfx/pokemon/vaporeon/front.static.2bpp.lz"
SECTION "_GirafarigFrontpic", ROMX
GirafarigFrontpic:   INCBIN "gfx/pokemon/girafarig/front.static.2bpp.lz"
SECTION "_DrowzeeFrontpic", ROMX
DrowzeeFrontpic:     INCBIN "gfx/pokemon/drowzee/front.static.2bpp.lz"
SECTION "_SneaselFrontpic", ROMX
SneaselFrontpic:     INCBIN "gfx/pokemon/sneasel/front.static.2bpp.lz"
SECTION "_BellossomFrontpic", ROMX
BellossomFrontpic:   INCBIN "gfx/pokemon/bellossom/front.static.2bpp.lz"
SECTION "_SnorlaxFrontpic", ROMX
SnorlaxFrontpic:     INCBIN "gfx/pokemon/snorlax/front.static.2bpp.lz"
SECTION "_WigglytuffFrontpic", ROMX
WigglytuffFrontpic:  INCBIN "gfx/pokemon/wigglytuff/front.static.2bpp.lz"
SECTION "_YanmaFrontpic", ROMX
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.static.2bpp.lz"
SECTION "_SmeargleFrontpic", ROMX
SmeargleFrontpic:    INCBIN "gfx/pokemon/smeargle/front.static.2bpp.lz"
SECTION "_ClefableFrontpic", ROMX
ClefableFrontpic:    INCBIN "gfx/pokemon/clefable/front.static.2bpp.lz"
SECTION "_PonytaFrontpic", ROMX
PonytaFrontpic:      INCBIN "gfx/pokemon/ponyta/front.static.2bpp.lz"
SECTION "_MurkrowFrontpic", ROMX
MurkrowFrontpic:     INCBIN "gfx/pokemon/murkrow/front.static.2bpp.lz"
SECTION "_GravelerFrontpic", ROMX
GravelerFrontpic:    INCBIN "gfx/pokemon/graveler/front.static.2bpp.lz"
SECTION "_StarmieFrontpic", ROMX
StarmieFrontpic:     INCBIN "gfx/pokemon/starmie/front.static.2bpp.lz"
SECTION "_PidgeottoFrontpic", ROMX
PidgeottoFrontpic:   INCBIN "gfx/pokemon/pidgeotto/front.static.2bpp.lz"
SECTION "_LedybaFrontpic", ROMX
LedybaFrontpic:      INCBIN "gfx/pokemon/ledyba/front.static.2bpp.lz"
SECTION "_GengarFrontpic", ROMX
GengarFrontpic:      INCBIN "gfx/pokemon/gengar/front.static.2bpp.lz"
SECTION "_OmastarFrontpic", ROMX
OmastarFrontpic:     INCBIN "gfx/pokemon/omastar/front.static.2bpp.lz"
SECTION "_PiloswineFrontpic", ROMX
PiloswineFrontpic:   INCBIN "gfx/pokemon/piloswine/front.static.2bpp.lz"
SECTION "_DugtrioFrontpic", ROMX
DugtrioFrontpic:     INCBIN "gfx/pokemon/dugtrio/front.static.2bpp.lz"
SECTION "_MagnetonFrontpic", ROMX
MagnetonFrontpic:    INCBIN "gfx/pokemon/magneton/front.static.2bpp.lz"
SECTION "_DragonairFrontpic", ROMX
DragonairFrontpic:   INCBIN "gfx/pokemon/dragonair/front.static.2bpp.lz"
SECTION "_ForretressFrontpic", ROMX
ForretressFrontpic:  INCBIN "gfx/pokemon/forretress/front.static.2bpp.lz"
SECTION "_TogeticFrontpic", ROMX
TogeticFrontpic:     INCBIN "gfx/pokemon/togetic/front.static.2bpp.lz"
SECTION "_KangaskhanBackpic", ROMX
KangaskhanBackpic:   INCBIN "gfx/pokemon/kangaskhan/back.2bpp.lz"



SECTION "_SeelFrontpic", ROMX
SeelFrontpic:        INCBIN "gfx/pokemon/seel/front.static.2bpp.lz"
SECTION "_CrobatFrontpic", ROMX
CrobatFrontpic:      INCBIN "gfx/pokemon/crobat/front.static.2bpp.lz"
SECTION "_ChanseyFrontpic", ROMX
ChanseyFrontpic:     INCBIN "gfx/pokemon/chansey/front.static.2bpp.lz"
SECTION "_TangelaFrontpic", ROMX
TangelaFrontpic:     INCBIN "gfx/pokemon/tangela/front.static.2bpp.lz"
SECTION "_SnubbullFrontpic", ROMX
SnubbullFrontpic:    INCBIN "gfx/pokemon/snubbull/front.static.2bpp.lz"
SECTION "_GranbullFrontpic", ROMX
GranbullFrontpic:    INCBIN "gfx/pokemon/granbull/front.static.2bpp.lz"
SECTION "_MiltankFrontpic", ROMX
MiltankFrontpic:     INCBIN "gfx/pokemon/miltank/front.static.2bpp.lz"
SECTION "_HaunterFrontpic", ROMX
HaunterFrontpic:     INCBIN "gfx/pokemon/haunter/front.static.2bpp.lz"
SECTION "_SunfloraFrontpic", ROMX
SunfloraFrontpic:    INCBIN "gfx/pokemon/sunflora/front.static.2bpp.lz"
SECTION "_UmbreonFrontpic", ROMX
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.static.2bpp.lz"
SECTION "_ChikoritaFrontpic", ROMX
ChikoritaFrontpic:   INCBIN "gfx/pokemon/chikorita/front.static.2bpp.lz"
SECTION "_GoldeenFrontpic", ROMX
GoldeenFrontpic:     INCBIN "gfx/pokemon/goldeen/front.static.2bpp.lz"
SECTION "_EspeonFrontpic", ROMX
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.static.2bpp.lz"
SECTION "_XatuFrontpic", ROMX
XatuFrontpic:        INCBIN "gfx/pokemon/xatu/front.static.2bpp.lz"
SECTION "_MewFrontpic", ROMX
MewFrontpic:         INCBIN "gfx/pokemon/mew/front.static.2bpp.lz"
SECTION "_OctilleryFrontpic", ROMX
OctilleryFrontpic:   INCBIN "gfx/pokemon/octillery/front.static.2bpp.lz"
SECTION "_JynxFrontpic", ROMX
JynxFrontpic:        INCBIN "gfx/pokemon/jynx/front.static.2bpp.lz"
SECTION "_WobbuffetFrontpic", ROMX
WobbuffetFrontpic:   INCBIN "gfx/pokemon/wobbuffet/front.static.2bpp.lz"
SECTION "_DelibirdFrontpic", ROMX
DelibirdFrontpic:    INCBIN "gfx/pokemon/delibird/front.static.2bpp.lz"
SECTION "_LedianFrontpic", ROMX
LedianFrontpic:      INCBIN "gfx/pokemon/ledian/front.static.2bpp.lz"
SECTION "_GloomFrontpic", ROMX
GloomFrontpic:       INCBIN "gfx/pokemon/gloom/front.static.2bpp.lz"
SECTION "_FlaaffyFrontpic", ROMX
FlaaffyFrontpic:     INCBIN "gfx/pokemon/flaaffy/front.static.2bpp.lz"
SECTION "_IvysaurFrontpic", ROMX
IvysaurFrontpic:     INCBIN "gfx/pokemon/ivysaur/front.static.2bpp.lz"
SECTION "_CyndaquilFrontpic", ROMX
CyndaquilFrontpic:   INCBIN "gfx/pokemon/cyndaquil/front.static.2bpp.lz"
SECTION "_HitmonchanFrontpic", ROMX
HitmonchanFrontpic:  INCBIN "gfx/pokemon/hitmonchan/front.static.2bpp.lz"
SECTION "_QuagsireFrontpic", ROMX
QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.static.2bpp.lz"



SECTION "_EkansFrontpic", ROMX
EkansFrontpic:       INCBIN "gfx/pokemon/ekans/front.static.2bpp.lz"
SECTION "_SudowoodoFrontpic", ROMX
SudowoodoFrontpic:   INCBIN "gfx/pokemon/sudowoodo/front.static.2bpp.lz"
SECTION "_PikachuFrontpic", ROMX
PikachuFrontpic:     INCBIN "gfx/pokemon/pikachu/front.static.2bpp.lz"
SECTION "_SeadraFrontpic", ROMX
SeadraFrontpic:      INCBIN "gfx/pokemon/seadra/front.static.2bpp.lz"
SECTION "_MagbyFrontpic", ROMX
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.static.2bpp.lz"
SECTION "_WeepinbellFrontpic", ROMX
WeepinbellFrontpic:  INCBIN "gfx/pokemon/weepinbell/front.static.2bpp.lz"
SECTION "_TotodileFrontpic", ROMX
TotodileFrontpic:    INCBIN "gfx/pokemon/totodile/front.static.2bpp.lz"
SECTION "_CorsolaFrontpic", ROMX
CorsolaFrontpic:     INCBIN "gfx/pokemon/corsola/front.static.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
SECTION "_MachopFrontpic", ROMX
MachopFrontpic:      INCBIN "gfx/pokemon/machop/front.static.2bpp.lz"
SECTION "_ChinchouFrontpic", ROMX
ChinchouFrontpic:    INCBIN "gfx/pokemon/chinchou/front.static.2bpp.lz"
SECTION "_RattataFrontpic", ROMX
RattataFrontpic:     INCBIN "gfx/pokemon/rattata/front.static.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
SECTION "_SpearowFrontpic", ROMX
SpearowFrontpic:     INCBIN "gfx/pokemon/spearow/front.static.2bpp.lz"
SECTION "_MagikarpFrontpic", ROMX
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.static.2bpp.lz"
SECTION "_CharmanderFrontpic", ROMX
CharmanderFrontpic:  INCBIN "gfx/pokemon/charmander/front.static.2bpp.lz"
SECTION "_CuboneFrontpic", ROMX
CuboneFrontpic:      INCBIN "gfx/pokemon/cubone/front.static.2bpp.lz"
BlackbeltPic:        INCBIN "gfx/trainers/blackbelt.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
SECTION "_NidoranMFrontpic", ROMX
NidoranMFrontpic:    INCBIN "gfx/pokemon/nidoran_m/front.static.2bpp.lz"
SECTION "_PorygonFrontpic", ROMX
PorygonFrontpic:     INCBIN "gfx/pokemon/porygon/front.static.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
SECTION "_GrimerFrontpic", ROMX
GrimerFrontpic:      INCBIN "gfx/pokemon/grimer/front.static.2bpp.lz"
SECTION "_StaryuFrontpic", ROMX
StaryuFrontpic:      INCBIN "gfx/pokemon/staryu/front.static.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
SECTION "_MeowthFrontpic", ROMX
MeowthFrontpic:      INCBIN "gfx/pokemon/meowth/front.static.2bpp.lz"
SECTION "_Porygon2Frontpic", ROMX
Porygon2Frontpic:    INCBIN "gfx/pokemon/porygon2/front.static.2bpp.lz"
SECTION "_SandshrewFrontpic", ROMX
SandshrewFrontpic:   INCBIN "gfx/pokemon/sandshrew/front.static.2bpp.lz"
SECTION "_NidoranFFrontpic", ROMX
NidoranFFrontpic:    INCBIN "gfx/pokemon/nidoran_f/front.static.2bpp.lz"
SECTION "_PidgeyFrontpic", ROMX
PidgeyFrontpic:      INCBIN "gfx/pokemon/pidgey/front.static.2bpp.lz"
SECTION "_ParasectBackpic", ROMX
ParasectBackpic:     INCBIN "gfx/pokemon/parasect/back.2bpp.lz"



SECTION "_MisdreavusFrontpic", ROMX
MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.static.2bpp.lz"
SECTION "_HoundourFrontpic", ROMX
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.static.2bpp.lz"
SECTION "_MankeyFrontpic", ROMX
MankeyFrontpic:      INCBIN "gfx/pokemon/mankey/front.static.2bpp.lz"
SECTION "_CelebiFrontpic", ROMX
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.static.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
SECTION "_PinecoFrontpic", ROMX
PinecoFrontpic:      INCBIN "gfx/pokemon/pineco/front.static.2bpp.lz"
SECTION "_KrabbyFrontpic", ROMX
KrabbyFrontpic:      INCBIN "gfx/pokemon/krabby/front.static.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
SECTION "_JigglypuffFrontpic", ROMX
JigglypuffFrontpic:  INCBIN "gfx/pokemon/jigglypuff/front.static.2bpp.lz"
SECTION "_ParasFrontpic", ROMX
ParasFrontpic:       INCBIN "gfx/pokemon/paras/front.static.2bpp.lz"
SECTION "_NidokingBackpic", ROMX
NidokingBackpic:     INCBIN "gfx/pokemon/nidoking/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
SECTION "_PsyduckFrontpic", ROMX
PsyduckFrontpic:     INCBIN "gfx/pokemon/psyduck/front.static.2bpp.lz"
SECTION "_SquirtleFrontpic", ROMX
SquirtleFrontpic:    INCBIN "gfx/pokemon/squirtle/front.static.2bpp.lz"
SECTION "_MachampBackpic", ROMX
MachampBackpic:      INCBIN "gfx/pokemon/machamp/back.2bpp.lz"
SECTION "_KoffingFrontpic", ROMX
KoffingFrontpic:     INCBIN "gfx/pokemon/koffing/front.static.2bpp.lz"
SECTION "_VenonatFrontpic", ROMX
VenonatFrontpic:     INCBIN "gfx/pokemon/venonat/front.static.2bpp.lz"
SECTION "_ExeggutorBackpic", ROMX
ExeggutorBackpic:    INCBIN "gfx/pokemon/exeggutor/back.2bpp.lz"
SECTION "_LanturnFrontpic", ROMX
LanturnFrontpic:     INCBIN "gfx/pokemon/lanturn/front.static.2bpp.lz"
SECTION "_TyrogueFrontpic", ROMX
TyrogueFrontpic:     INCBIN "gfx/pokemon/tyrogue/front.static.2bpp.lz"
SECTION "_MareepFrontpic", ROMX
MareepFrontpic:      INCBIN "gfx/pokemon/mareep/front.static.2bpp.lz"
FergusPic:           INCBIN "gfx/trainers/fergus.2bpp.lz"
SECTION "_EeveeFrontpic", ROMX
EeveeFrontpic:       INCBIN "gfx/pokemon/eevee/front.static.2bpp.lz"
SECTION "_ButterfreeBackpic", ROMX
ButterfreeBackpic:   INCBIN "gfx/pokemon/butterfree/back.2bpp.lz"
SECTION "_ZubatFrontpic", ROMX
ZubatFrontpic:       INCBIN "gfx/pokemon/zubat/front.static.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
SECTION "_AlakazamBackpic", ROMX
AlakazamBackpic:     INCBIN "gfx/pokemon/alakazam/back.2bpp.lz"
SECTION "_AipomFrontpic", ROMX
AipomFrontpic:       INCBIN "gfx/pokemon/aipom/front.static.2bpp.lz"
SECTION "_AbraFrontpic", ROMX
AbraFrontpic:        INCBIN "gfx/pokemon/abra/front.static.2bpp.lz"
SECTION "_CloysterBackpic", ROMX
CloysterBackpic:     INCBIN "gfx/pokemon/cloyster/back.2bpp.lz"
SECTION "_HoothootFrontpic", ROMX
HoothootFrontpic:    INCBIN "gfx/pokemon/hoothoot/front.static.2bpp.lz"
SECTION "_UnownFBackpic", ROMX
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"



SECTION "_DodrioBackpic", ROMX
DodrioBackpic:       INCBIN "gfx/pokemon/dodrio/back.2bpp.lz"
SECTION "_ClefairyFrontpic", ROMX
ClefairyFrontpic:    INCBIN "gfx/pokemon/clefairy/front.static.2bpp.lz"
SECTION "_SlugmaFrontpic", ROMX
SlugmaFrontpic:      INCBIN "gfx/pokemon/slugma/front.static.2bpp.lz"
SECTION "_GrowlitheFrontpic", ROMX
GrowlitheFrontpic:   INCBIN "gfx/pokemon/growlithe/front.static.2bpp.lz"
SECTION "_SlowpokeFrontpic", ROMX
SlowpokeFrontpic:    INCBIN "gfx/pokemon/slowpoke/front.static.2bpp.lz"
SECTION "_SmoochumFrontpic", ROMX
SmoochumFrontpic:    INCBIN "gfx/pokemon/smoochum/front.static.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
SECTION "_MarillFrontpic", ROMX
MarillFrontpic:      INCBIN "gfx/pokemon/marill/front.static.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
SECTION "_VenomothBackpic", ROMX
VenomothBackpic:     INCBIN "gfx/pokemon/venomoth/back.2bpp.lz"
SandraPic:           INCBIN "gfx/trainers/sandra.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
SECTION "_OmanyteFrontpic", ROMX
OmanyteFrontpic:     INCBIN "gfx/pokemon/omanyte/front.static.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
SECTION "_PupitarFrontpic", ROMX
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.static.2bpp.lz"
SECTION "_BellsproutFrontpic", ROMX
BellsproutFrontpic:  INCBIN "gfx/pokemon/bellsprout/front.static.2bpp.lz"
SECTION "_ShellderFrontpic", ROMX
ShellderFrontpic:    INCBIN "gfx/pokemon/shellder/front.static.2bpp.lz"
SECTION "_TentacoolFrontpic", ROMX
TentacoolFrontpic:   INCBIN "gfx/pokemon/tentacool/front.static.2bpp.lz"
SECTION "_CleffaFrontpic", ROMX
CleffaFrontpic:      INCBIN "gfx/pokemon/cleffa/front.static.2bpp.lz"
SECTION "_GyaradosBackpic", ROMX
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
SECTION "_NinetalesBackpic", ROMX
NinetalesBackpic:    INCBIN "gfx/pokemon/ninetales/back.2bpp.lz"
SECTION "_YanmaBackpic", ROMX
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
SECTION "_PinsirBackpic", ROMX
PinsirBackpic:       INCBIN "gfx/pokemon/pinsir/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
SECTION "_ClefableBackpic", ROMX
ClefableBackpic:     INCBIN "gfx/pokemon/clefable/back.2bpp.lz"
SECTION "_DoduoFrontpic", ROMX
DoduoFrontpic:       INCBIN "gfx/pokemon/doduo/front.static.2bpp.lz"
SECTION "_FeraligatrBackpic", ROMX
FeraligatrBackpic:   INCBIN "gfx/pokemon/feraligatr/back.2bpp.lz"
SECTION "_DratiniFrontpic", ROMX
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.static.2bpp.lz"
SECTION "_MagnetonBackpic", ROMX
MagnetonBackpic:     INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
SECTION "_QwilfishFrontpic", ROMX
QwilfishFrontpic:    INCBIN "gfx/pokemon/qwilfish/front.static.2bpp.lz"
SECTION "_SuicuneBackpic", ROMX
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
SECTION "_SlowkingBackpic", ROMX
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
SECTION "_ElekidBackpic", ROMX
ElekidBackpic:       INCBIN "gfx/pokemon/elekid/back.2bpp.lz"
SECTION "_CelebiBackpic", ROMX
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
SECTION "_KrabbyBackpic", ROMX
KrabbyBackpic:       INCBIN "gfx/pokemon/krabby/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
SECTION "_SnorlaxBackpic", ROMX
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"



SECTION "_VenusaurBackpic", ROMX
VenusaurBackpic:     INCBIN "gfx/pokemon/venusaur/back.2bpp.lz"
SECTION "_MoltresBackpic", ROMX
MoltresBackpic:      INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
SECTION "_SunfloraBackpic", ROMX
SunfloraBackpic:     INCBIN "gfx/pokemon/sunflora/back.2bpp.lz"
SECTION "_RhydonBackpic", ROMX
RhydonBackpic:       INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
SECTION "_LarvitarFrontpic", ROMX
LarvitarFrontpic:    INCBIN "gfx/pokemon/larvitar/front.static.2bpp.lz"
SECTION "_TyranitarBackpic", ROMX
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
SECTION "_SandslashBackpic", ROMX
SandslashBackpic:    INCBIN "gfx/pokemon/sandslash/back.2bpp.lz"
SECTION "_SeadraBackpic", ROMX
SeadraBackpic:       INCBIN "gfx/pokemon/seadra/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
SECTION "_FarfetchDBackpic", ROMX
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
SECTION "_NidoranMBackpic", ROMX
NidoranMBackpic:     INCBIN "gfx/pokemon/nidoran_m/back.2bpp.lz"
SECTION "_LedybaBackpic", ROMX
LedybaBackpic:       INCBIN "gfx/pokemon/ledyba/back.2bpp.lz"
SECTION "_CyndaquilBackpic", ROMX
CyndaquilBackpic:    INCBIN "gfx/pokemon/cyndaquil/back.2bpp.lz"
SECTION "_BayleefBackpic", ROMX
BayleefBackpic:      INCBIN "gfx/pokemon/bayleef/back.2bpp.lz"
SECTION "_OddishFrontpic", ROMX
OddishFrontpic:      INCBIN "gfx/pokemon/oddish/front.static.2bpp.lz"
SECTION "_RapidashBackpic", ROMX
RapidashBackpic:     INCBIN "gfx/pokemon/rapidash/back.2bpp.lz"
SECTION "_DoduoBackpic", ROMX
DoduoBackpic:        INCBIN "gfx/pokemon/doduo/back.2bpp.lz"
SECTION "_MankeyBackpic", ROMX
MankeyBackpic:       INCBIN "gfx/pokemon/mankey/back.2bpp.lz"
SECTION "_MagmarBackpic", ROMX
MagmarBackpic:       INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
SECTION "_HypnoBackpic", ROMX
HypnoBackpic:        INCBIN "gfx/pokemon/hypno/back.2bpp.lz"
SECTION "_QuilavaBackpic", ROMX
QuilavaBackpic:      INCBIN "gfx/pokemon/quilava/back.2bpp.lz"
SECTION "_CroconawBackpic", ROMX
CroconawBackpic:     INCBIN "gfx/pokemon/croconaw/back.2bpp.lz"
SECTION "_SandshrewBackpic", ROMX
SandshrewBackpic:    INCBIN "gfx/pokemon/sandshrew/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
SECTION "_ShellderBackpic", ROMX
ShellderBackpic:     INCBIN "gfx/pokemon/shellder/back.2bpp.lz"
SECTION "_ZubatBackpic", ROMX
ZubatBackpic:        INCBIN "gfx/pokemon/zubat/back.2bpp.lz"
SECTION "_TeddiursaFrontpic", ROMX
TeddiursaFrontpic:   INCBIN "gfx/pokemon/teddiursa/front.static.2bpp.lz"
SECTION "_CuboneBackpic", ROMX
CuboneBackpic:       INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
GruntMPic:           INCBIN "gfx/trainers/gruntm.2bpp.lz"
SECTION "_GloomBackpic", ROMX
GloomBackpic:        INCBIN "gfx/pokemon/gloom/back.2bpp.lz"
SECTION "_MagcargoBackpic", ROMX
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
SECTION "_KabutopsBackpic", ROMX
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
SECTION "_BeedrillBackpic", ROMX
BeedrillBackpic:     INCBIN "gfx/pokemon/beedrill/back.2bpp.lz"
SECTION "_ArcanineBackpic", ROMX
ArcanineBackpic:     INCBIN "gfx/pokemon/arcanine/back.2bpp.lz"
SECTION "_FlareonBackpic", ROMX
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
SECTION "_GoldeenBackpic", ROMX
GoldeenBackpic:      INCBIN "gfx/pokemon/goldeen/back.2bpp.lz"
SECTION "_BulbasaurFrontpic", ROMX
BulbasaurFrontpic:   INCBIN "gfx/pokemon/bulbasaur/front.static.2bpp.lz"
SECTION "_StarmieBackpic", ROMX
StarmieBackpic:      INCBIN "gfx/pokemon/starmie/back.2bpp.lz"



SECTION "_OmanyteBackpic", ROMX
OmanyteBackpic:      INCBIN "gfx/pokemon/omanyte/back.2bpp.lz"
SECTION "_PidgeyBackpic", ROMX
PidgeyBackpic:       INCBIN "gfx/pokemon/pidgey/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
SECTION "_QwilfishBackpic", ROMX
QwilfishBackpic:     INCBIN "gfx/pokemon/qwilfish/back.2bpp.lz"
SECTION "_GligarBackpic", ROMX
GligarBackpic:       INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
SECTION "_TyphlosionBackpic", ROMX
TyphlosionBackpic:   INCBIN "gfx/pokemon/typhlosion/back.2bpp.lz"
SECTION "_CharmeleonBackpic", ROMX
CharmeleonBackpic:   INCBIN "gfx/pokemon/charmeleon/back.2bpp.lz"
SECTION "_NidoqueenBackpic", ROMX
NidoqueenBackpic:    INCBIN "gfx/pokemon/nidoqueen/back.2bpp.lz"
SECTION "_PichuFrontpic", ROMX
PichuFrontpic:       INCBIN "gfx/pokemon/pichu/front.static.2bpp.lz"
SECTION "_ElectabuzzBackpic", ROMX
ElectabuzzBackpic:   INCBIN "gfx/pokemon/electabuzz/back.2bpp.lz"
SECTION "_LedianBackpic", ROMX
LedianBackpic:       INCBIN "gfx/pokemon/ledian/back.2bpp.lz"
SECTION "_PupitarBackpic", ROMX
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
SECTION "_HeracrossBackpic", ROMX
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
SECTION "_UnownDFrontpic", ROMX
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.static.2bpp.lz"
SECTION "_MiltankBackpic", ROMX
MiltankBackpic:      INCBIN "gfx/pokemon/miltank/back.2bpp.lz"
SECTION "_SteelixBackpic", ROMX
SteelixBackpic:      INCBIN "gfx/pokemon/steelix/back.2bpp.lz"
SECTION "_PersianBackpic", ROMX
PersianBackpic:      INCBIN "gfx/pokemon/persian/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.static.2bpp.lz"
SECTION "_EeveeBackpic", ROMX
EeveeBackpic:        INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
SECTION "_PonytaBackpic", ROMX
PonytaBackpic:       INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
SECTION "_RemoraidFrontpic", ROMX
RemoraidFrontpic:    INCBIN "gfx/pokemon/remoraid/front.static.2bpp.lz"
SECTION "_PoliwagFrontpic", ROMX
PoliwagFrontpic:     INCBIN "gfx/pokemon/poliwag/front.static.2bpp.lz"
SECTION "_OnixBackpic", ROMX
OnixBackpic:         INCBIN "gfx/pokemon/onix/back.2bpp.lz"
SECTION "_KoffingBackpic", ROMX
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
E4KarenPic:
RocketKarenPic:      INCBIN "gfx/trainers/rocketkaren.2bpp.lz"
SECTION "_NidorinaBackpic", ROMX
NidorinaBackpic:     INCBIN "gfx/pokemon/nidorina/back.2bpp.lz"
SECTION "_TentacruelBackpic", ROMX
TentacruelBackpic:   INCBIN "gfx/pokemon/tentacruel/back.2bpp.lz"
SECTION "_GrowlitheBackpic", ROMX
GrowlitheBackpic:    INCBIN "gfx/pokemon/growlithe/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
SECTION "_MachokeBackpic", ROMX
MachokeBackpic:      INCBIN "gfx/pokemon/machoke/back.2bpp.lz"
SECTION "_RaichuBackpic", ROMX
RaichuBackpic:       INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
SECTION "_PoliwrathBackpic", ROMX
PoliwrathBackpic:    INCBIN "gfx/pokemon/poliwrath/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SECTION "_SunkernFrontpic", ROMX
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.static.2bpp.lz"
SECTION "_NidorinoBackpic", ROMX
NidorinoBackpic:     INCBIN "gfx/pokemon/nidorino/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
SECTION "_ElectrodeFrontpic", ROMX
ElectrodeFrontpic:   INCBIN "gfx/pokemon/electrode/front.static.2bpp.lz"



SECTION "_SudowoodoBackpic", ROMX
SudowoodoBackpic:    INCBIN "gfx/pokemon/sudowoodo/back.2bpp.lz"
SECTION "_FlaaffyBackpic", ROMX
FlaaffyBackpic:      INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
SECTION "_SentretFrontpic", ROMX
SentretFrontpic:     INCBIN "gfx/pokemon/sentret/front.static.2bpp.lz"
SECTION "_TogeticBackpic", ROMX
TogeticBackpic:      INCBIN "gfx/pokemon/togetic/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
SECTION "_MarowakBackpic", ROMX
MarowakBackpic:      INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
SECTION "_GeodudeBackpic", ROMX
GeodudeBackpic:      INCBIN "gfx/pokemon/geodude/back.2bpp.lz"
SECTION "_ScytherBackpic", ROMX
ScytherBackpic:      INCBIN "gfx/pokemon/scyther/back.2bpp.lz"
SECTION "_VileplumeBackpic", ROMX
VileplumeBackpic:    INCBIN "gfx/pokemon/vileplume/back.2bpp.lz"
SECTION "_HitmonchanBackpic", ROMX
HitmonchanBackpic:   INCBIN "gfx/pokemon/hitmonchan/back.2bpp.lz"
SECTION "_JumpluffBackpic", ROMX
JumpluffBackpic:     INCBIN "gfx/pokemon/jumpluff/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
SECTION "_BlastoiseBackpic", ROMX
BlastoiseBackpic:    INCBIN "gfx/pokemon/blastoise/back.2bpp.lz"
SECTION "_MisdreavusBackpic", ROMX
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
SECTION "_TyrogueBackpic", ROMX
TyrogueBackpic:      INCBIN "gfx/pokemon/tyrogue/back.2bpp.lz"
SECTION "_GeodudeFrontpic", ROMX
GeodudeFrontpic:     INCBIN "gfx/pokemon/geodude/front.static.2bpp.lz"
SECTION "_ScizorBackpic", ROMX
ScizorBackpic:       INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
SECTION "_GirafarigBackpic", ROMX
GirafarigBackpic:    INCBIN "gfx/pokemon/girafarig/back.2bpp.lz"
SECTION "_StantlerBackpic", ROMX
StantlerBackpic:     INCBIN "gfx/pokemon/stantler/back.2bpp.lz"
SECTION "_SmeargleBackpic", ROMX
SmeargleBackpic:     INCBIN "gfx/pokemon/smeargle/back.2bpp.lz"
SECTION "_CharizardBackpic", ROMX
CharizardBackpic:    INCBIN "gfx/pokemon/charizard/back.2bpp.lz"
SECTION "_KadabraBackpic", ROMX
KadabraBackpic:      INCBIN "gfx/pokemon/kadabra/back.2bpp.lz"
SECTION "_PrimeapeBackpic", ROMX
PrimeapeBackpic:     INCBIN "gfx/pokemon/primeape/back.2bpp.lz"
SECTION "_FurretBackpic", ROMX
FurretBackpic:       INCBIN "gfx/pokemon/furret/back.2bpp.lz"
SECTION "_WartortleBackpic", ROMX
WartortleBackpic:    INCBIN "gfx/pokemon/wartortle/back.2bpp.lz"
SECTION "_ExeggcuteBackpic", ROMX
ExeggcuteBackpic:    INCBIN "gfx/pokemon/exeggcute/back.2bpp.lz"



SECTION "_MewtwoBackpic", ROMX
MewtwoBackpic:       INCBIN "gfx/pokemon/mewtwo/back.2bpp.lz"
ElmPic:              INCBIN "gfx/trainers/elm.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
SECTION "_DiglettFrontpic", ROMX
DiglettFrontpic:     INCBIN "gfx/pokemon/diglett/front.static.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
SECTION "_MukBackpic", ROMX
MukBackpic:          INCBIN "gfx/pokemon/muk/back.2bpp.lz"
SECTION "_DelibirdBackpic", ROMX
DelibirdBackpic:     INCBIN "gfx/pokemon/delibird/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
SECTION "_MagikarpBackpic", ROMX
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
SECTION "_AriadosBackpic", ROMX
AriadosBackpic:      INCBIN "gfx/pokemon/ariados/back.2bpp.lz"
SECTION "_SneaselBackpic", ROMX
SneaselBackpic:      INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
SECTION "_UmbreonBackpic", ROMX
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
SECTION "_MurkrowBackpic", ROMX
MurkrowBackpic:      INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
SECTION "_IvysaurBackpic", ROMX
IvysaurBackpic:      INCBIN "gfx/pokemon/ivysaur/back.2bpp.lz"
SECTION "_SlowbroBackpic", ROMX
SlowbroBackpic:      INCBIN "gfx/pokemon/slowbro/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
SECTION "_GolduckBackpic", ROMX
GolduckBackpic:      INCBIN "gfx/pokemon/golduck/back.2bpp.lz"
SECTION "_WeezingBackpic", ROMX
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
SECTION "_EnteiBackpic", ROMX
EnteiBackpic:        INCBIN "gfx/pokemon/entei/back.2bpp.lz"
GruntFPic:           INCBIN "gfx/trainers/gruntf.2bpp.lz"
SECTION "_HorseaFrontpic", ROMX
HorseaFrontpic:      INCBIN "gfx/pokemon/horsea/front.static.2bpp.lz"
SECTION "_PidgeotBackpic", ROMX
PidgeotBackpic:      INCBIN "gfx/pokemon/pidgeot/back.2bpp.lz"
SECTION "_HoOhBackpic", ROMX
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
SECTION "_PoliwhirlBackpic", ROMX
PoliwhirlBackpic:    INCBIN "gfx/pokemon/poliwhirl/back.2bpp.lz"
SECTION "_MewBackpic", ROMX
MewBackpic:          INCBIN "gfx/pokemon/mew/back.2bpp.lz"
SECTION "_MachopBackpic", ROMX
MachopBackpic:       INCBIN "gfx/pokemon/machop/back.2bpp.lz"
SECTION "_AbraBackpic", ROMX
AbraBackpic:         INCBIN "gfx/pokemon/abra/back.2bpp.lz"
SECTION "_AerodactylBackpic", ROMX
AerodactylBackpic:   INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
SECTION "_KakunaFrontpic", ROMX
KakunaFrontpic:      INCBIN "gfx/pokemon/kakuna/front.static.2bpp.lz"
SECTION "_DugtrioBackpic", ROMX
DugtrioBackpic:      INCBIN "gfx/pokemon/dugtrio/back.2bpp.lz"
SECTION "_WeepinbellBackpic", ROMX
WeepinbellBackpic:   INCBIN "gfx/pokemon/weepinbell/back.2bpp.lz"
SECTION "_NidoranFBackpic", ROMX
NidoranFBackpic:     INCBIN "gfx/pokemon/nidoran_f/back.2bpp.lz"
SECTION "_GravelerBackpic", ROMX
GravelerBackpic:     INCBIN "gfx/pokemon/graveler/back.2bpp.lz"
SECTION "_AipomBackpic", ROMX
AipomBackpic:        INCBIN "gfx/pokemon/aipom/back.2bpp.lz"
SECTION "_EspeonBackpic", ROMX
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
SECTION "_WeedleFrontpic", ROMX
WeedleFrontpic:      INCBIN "gfx/pokemon/weedle/front.static.2bpp.lz"
SECTION "_TotodileBackpic", ROMX
TotodileBackpic:     INCBIN "gfx/pokemon/totodile/back.2bpp.lz"
SECTION "_SnubbullBackpic", ROMX
SnubbullBackpic:     INCBIN "gfx/pokemon/snubbull/back.2bpp.lz"
SECTION "_KinglerBackpic", ROMX
KinglerBackpic:      INCBIN "gfx/pokemon/kingler/back.2bpp.lz"
SECTION "_GengarBackpic", ROMX
GengarBackpic:       INCBIN "gfx/pokemon/gengar/back.2bpp.lz"
SECTION "_RattataBackpic", ROMX
RattataBackpic:      INCBIN "gfx/pokemon/rattata/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
RocketWillPic:       INCBIN "gfx/trainers/rocket_will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
SECTION "_MagnemiteFrontpic", ROMX
MagnemiteFrontpic:   INCBIN "gfx/pokemon/magnemite/front.static.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
SECTION "_MagnemiteBackpic", ROMX
MagnemiteBackpic:    INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"



SECTION "_HoothootBackpic", ROMX
HoothootBackpic:     INCBIN "gfx/pokemon/hoothoot/back.2bpp.lz"
SECTION "_NoctowlBackpic", ROMX
NoctowlBackpic:      INCBIN "gfx/pokemon/noctowl/back.2bpp.lz"
MortonPic:           INCBIN "gfx/trainers/morton.2bpp.lz"
SECTION "_SlugmaBackpic", ROMX
SlugmaBackpic:       INCBIN "gfx/pokemon/slugma/back.2bpp.lz"
SECTION "_KabutoBackpic", ROMX
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
SECTION "_VictreebelBackpic", ROMX
VictreebelBackpic:   INCBIN "gfx/pokemon/victreebel/back.2bpp.lz"
SECTION "_MeowthBackpic", ROMX
MeowthBackpic:       INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
SECTION "_MeganiumBackpic", ROMX
MeganiumBackpic:     INCBIN "gfx/pokemon/meganium/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
SECTION "_LickitungBackpic", ROMX
LickitungBackpic:    INCBIN "gfx/pokemon/lickitung/back.2bpp.lz"
SECTION "_TogepiFrontpic", ROMX
TogepiFrontpic:      INCBIN "gfx/pokemon/togepi/front.static.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
SECTION "_HaunterBackpic", ROMX
HaunterBackpic:      INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
SECTION "_XatuBackpic", ROMX
XatuBackpic:         INCBIN "gfx/pokemon/xatu/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
SECTION "_Porygon2Backpic", ROMX
Porygon2Backpic:     INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
SylviaPic:           INCBIN "gfx/trainers/sylvia.2bpp.lz"
SECTION "_PinecoBackpic", ROMX
PinecoBackpic:       INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
SECTION "_MetapodFrontpic", ROMX
MetapodFrontpic:     INCBIN "gfx/pokemon/metapod/front.static.2bpp.lz"
SECTION "_SeelBackpic", ROMX
SeelBackpic:         INCBIN "gfx/pokemon/seel/back.2bpp.lz"
SECTION "_QuagsireBackpic", ROMX
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
SECTION "_JolteonBackpic", ROMX
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
SECTION "_CaterpieFrontpic", ROMX
CaterpieFrontpic:    INCBIN "gfx/pokemon/caterpie/front.static.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
SECTION "_GranbullBackpic", ROMX
GranbullBackpic:     INCBIN "gfx/pokemon/granbull/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
SECTION "_SpearowBackpic", ROMX
SpearowBackpic:      INCBIN "gfx/pokemon/spearow/back.2bpp.lz"
SECTION "_SunkernBackpic", ROMX
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
SECTION "_LaprasBackpic", ROMX
LaprasBackpic:       INCBIN "gfx/pokemon/lapras/back.2bpp.lz"
SECTION "_MagbyBackpic", ROMX
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
SECTION "_DragonairBackpic", ROMX
DragonairBackpic:    INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
SECTION "_ZapdosBackpic", ROMX
ZapdosBackpic:       INCBIN "gfx/pokemon/zapdos/back.2bpp.lz"
SECTION "_ChikoritaBackpic", ROMX
ChikoritaBackpic:    INCBIN "gfx/pokemon/chikorita/back.2bpp.lz"
SECTION "_CorsolaBackpic", ROMX
CorsolaBackpic:      INCBIN "gfx/pokemon/corsola/back.2bpp.lz"
SECTION "_ChinchouBackpic", ROMX
ChinchouBackpic:     INCBIN "gfx/pokemon/chinchou/back.2bpp.lz"
SECTION "_ChanseyBackpic", ROMX
ChanseyBackpic:      INCBIN "gfx/pokemon/chansey/back.2bpp.lz"
SECTION "_SkiploomBackpic", ROMX
SkiploomBackpic:     INCBIN "gfx/pokemon/skiploom/back.2bpp.lz"
SECTION "_SpinarakFrontpic", ROMX
SpinarakFrontpic:    INCBIN "gfx/pokemon/spinarak/front.static.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
SECTION "_UnownWFrontpic", ROMX
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.static.2bpp.lz"
SECTION "_CharmanderBackpic", ROMX
CharmanderBackpic:   INCBIN "gfx/pokemon/charmander/back.2bpp.lz"
SECTION "_RhyhornBackpic", ROMX
RhyhornBackpic:      INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
SECTION "_UnownCFrontpic", ROMX
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.static.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
SECTION "_UnownZFrontpic", ROMX
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.static.2bpp.lz"
SECTION "_SwinubFrontpic", ROMX
SwinubFrontpic:      INCBIN "gfx/pokemon/swinub/front.static.2bpp.lz"
SECTION "_LarvitarBackpic", ROMX
LarvitarBackpic:     INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
SECTION "_PorygonBackpic", ROMX
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
SECTION "_UnownHBackpic", ROMX
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"



SECTION "_ParasBackpic", ROMX
ParasBackpic:        INCBIN "gfx/pokemon/paras/back.2bpp.lz"
SECTION "_VaporeonBackpic", ROMX
VaporeonBackpic:     INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
SECTION "_TentacoolBackpic", ROMX
TentacoolBackpic:    INCBIN "gfx/pokemon/tentacool/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
SECTION "_BulbasaurBackpic", ROMX
BulbasaurBackpic:    INCBIN "gfx/pokemon/bulbasaur/back.2bpp.lz"
SECTION "_SmoochumBackpic", ROMX
SmoochumBackpic:     INCBIN "gfx/pokemon/smoochum/back.2bpp.lz"
SECTION "_PichuBackpic", ROMX
PichuBackpic:        INCBIN "gfx/pokemon/pichu/back.2bpp.lz"
SECTION "_HoundoomBackpic", ROMX
HoundoomBackpic:     INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
SECTION "_BellsproutBackpic", ROMX
BellsproutBackpic:   INCBIN "gfx/pokemon/bellsprout/back.2bpp.lz"
SECTION "_GrimerBackpic", ROMX
GrimerBackpic:       INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
SECTION "_LanturnBackpic", ROMX
LanturnBackpic:      INCBIN "gfx/pokemon/lanturn/back.2bpp.lz"
SECTION "_PidgeottoBackpic", ROMX
PidgeottoBackpic:    INCBIN "gfx/pokemon/pidgeotto/back.2bpp.lz"
SECTION "_StaryuBackpic", ROMX
StaryuBackpic:       INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
SECTION "_MrMimeBackpic", ROMX
MrMimeBackpic:       INCBIN "gfx/pokemon/mr__mime/back.2bpp.lz"
SECTION "_CaterpieBackpic", ROMX
CaterpieBackpic:     INCBIN "gfx/pokemon/caterpie/back.2bpp.lz"
SECTION "_VoltorbFrontpic", ROMX
VoltorbFrontpic:     INCBIN "gfx/pokemon/voltorb/front.static.2bpp.lz"
SECTION "_LugiaBackpic", ROMX
LugiaBackpic:        INCBIN "gfx/pokemon/lugia/back.2bpp.lz"
BrycePic:            INCBIN "gfx/trainers/bryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
SECTION "_UnownGFrontpic", ROMX
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.static.2bpp.lz"
SECTION "_ArbokBackpic", ROMX
ArbokBackpic:        INCBIN "gfx/pokemon/arbok/back.2bpp.lz"
SECTION "_PolitoedBackpic", ROMX
PolitoedBackpic:     INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
SECTION "_DragoniteBackpic", ROMX
DragoniteBackpic:    INCBIN "gfx/pokemon/dragonite/back.2bpp.lz"
SECTION "_HitmonleeBackpic", ROMX
HitmonleeBackpic:    INCBIN "gfx/pokemon/hitmonlee/back.2bpp.lz"
SECTION "_NatuFrontpic", ROMX
NatuFrontpic:        INCBIN "gfx/pokemon/natu/front.static.2bpp.lz"
SECTION "_UrsaringBackpic", ROMX
UrsaringBackpic:     INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
SECTION "_TeddiursaBackpic", ROMX
TeddiursaBackpic:    INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
SECTION "_UnownVFrontpic", ROMX
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.static.2bpp.lz"
SECTION "_KakunaBackpic", ROMX
KakunaBackpic:       INCBIN "gfx/pokemon/kakuna/back.2bpp.lz"
SECTION "_WobbuffetBackpic", ROMX
WobbuffetBackpic:    INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
SECTION "_TogepiBackpic", ROMX
TogepiBackpic:       INCBIN "gfx/pokemon/togepi/back.2bpp.lz"
SECTION "_CrobatBackpic", ROMX
CrobatBackpic:       INCBIN "gfx/pokemon/crobat/back.2bpp.lz"
SECTION "_BlisseyBackpic", ROMX
BlisseyBackpic:      INCBIN "gfx/pokemon/blissey/back.2bpp.lz"
SECTION "_AmpharosBackpic", ROMX
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
SECTION "_IgglybuffBackpic", ROMX
IgglybuffBackpic:    INCBIN "gfx/pokemon/igglybuff/back.2bpp.lz"
SECTION "_AzumarillBackpic", ROMX
AzumarillBackpic:    INCBIN "gfx/pokemon/azumarill/back.2bpp.lz"
SECTION "_OctilleryBackpic", ROMX
OctilleryBackpic:    INCBIN "gfx/pokemon/octillery/back.2bpp.lz"
SECTION "_UnownSFrontpic", ROMX
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.static.2bpp.lz"
SECTION "_HorseaBackpic", ROMX
HorseaBackpic:       INCBIN "gfx/pokemon/horsea/back.2bpp.lz"
SECTION "_SentretBackpic", ROMX
SentretBackpic:      INCBIN "gfx/pokemon/sentret/back.2bpp.lz"
SECTION "_UnownOFrontpic", ROMX
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.static.2bpp.lz"
SECTION "_UnownTFrontpic", ROMX
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.static.2bpp.lz"
SECTION "_WigglytuffBackpic", ROMX
WigglytuffBackpic:   INCBIN "gfx/pokemon/wigglytuff/back.2bpp.lz"
SECTION "_ArticunoBackpic", ROMX
ArticunoBackpic:     INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
SECTION "_DittoBackpic", ROMX
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
SECTION "_WeedleBackpic", ROMX
WeedleBackpic:       INCBIN "gfx/pokemon/weedle/back.2bpp.lz"
SECTION "_UnownHFrontpic", ROMX
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.static.2bpp.lz"
SECTION "_CleffaBackpic", ROMX
CleffaBackpic:       INCBIN "gfx/pokemon/cleffa/back.2bpp.lz"
SECTION "_DrowzeeBackpic", ROMX
DrowzeeBackpic:      INCBIN "gfx/pokemon/drowzee/back.2bpp.lz"
SECTION "_GastlyBackpic", ROMX
GastlyBackpic:       INCBIN "gfx/pokemon/gastly/back.2bpp.lz"
SECTION "_FearowBackpic", ROMX
FearowBackpic:       INCBIN "gfx/pokemon/fearow/back.2bpp.lz"
SECTION "_MarillBackpic", ROMX
MarillBackpic:       INCBIN "gfx/pokemon/marill/back.2bpp.lz"
SECTION "_DratiniBackpic", ROMX
DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
SECTION "_ElectrodeBackpic", ROMX
ElectrodeBackpic:    INCBIN "gfx/pokemon/electrode/back.2bpp.lz"
SECTION "_AirmorBackpic", ROMX
AirmorBackpic:       INCBIN "gfx/pokemon/airmor/back.2bpp.lz"
SECTION "_MetapodBackpic", ROMX
MetapodBackpic:      INCBIN "gfx/pokemon/metapod/back.2bpp.lz"
SECTION "_JigglypuffBackpic", ROMX
JigglypuffBackpic:   INCBIN "gfx/pokemon/jigglypuff/back.2bpp.lz"
SECTION "_OddishBackpic", ROMX
OddishBackpic:       INCBIN "gfx/pokemon/oddish/back.2bpp.lz"
SECTION "_UnownDBackpic", ROMX
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"



SECTION "_SpinarakBackpic", ROMX
SpinarakBackpic:     INCBIN "gfx/pokemon/spinarak/back.2bpp.lz"
SECTION "_RaikouBackpic", ROMX
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
SECTION "_UnownKFrontpic", ROMX
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.static.2bpp.lz"
SECTION "_HoundourBackpic", ROMX
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
SECTION "_PoliwagBackpic", ROMX
PoliwagBackpic:      INCBIN "gfx/pokemon/poliwag/back.2bpp.lz"
SECTION "_SquirtleBackpic", ROMX
SquirtleBackpic:     INCBIN "gfx/pokemon/squirtle/back.2bpp.lz"
SECTION "_ShuckleBackpic", ROMX
ShuckleBackpic:      INCBIN "gfx/pokemon/shuckle/back.2bpp.lz"
SECTION "_DewgongBackpic", ROMX
DewgongBackpic:      INCBIN "gfx/pokemon/dewgong/back.2bpp.lz"
SECTION "_UnownBFrontpic", ROMX
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.static.2bpp.lz"
SECTION "_SlowpokeBackpic", ROMX
SlowpokeBackpic:     INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
SECTION "_DunsparceBackpic", ROMX
DunsparceBackpic:    INCBIN "gfx/pokemon/dunsparce/back.2bpp.lz"
SECTION "_DonphanBackpic", ROMX
DonphanBackpic:      INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
SECTION "_WooperBackpic", ROMX
WooperBackpic:       INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
SECTION "_TaurosBackpic", ROMX
TaurosBackpic:       INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
SECTION "_UnownXFrontpic", ROMX
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.static.2bpp.lz"
SECTION "_UnownNFrontpic", ROMX
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.static.2bpp.lz"
SECTION "_TangelaBackpic", ROMX
TangelaBackpic:      INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
SECTION "_VoltorbBackpic", ROMX
VoltorbBackpic:      INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
SECTION "_UnownJFrontpic", ROMX
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.static.2bpp.lz"
SECTION "_MantineBackpic", ROMX
MantineBackpic:      INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
SECTION "_UnownLFrontpic", ROMX
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.static.2bpp.lz"
SECTION "_PiloswineBackpic", ROMX
PiloswineBackpic:    INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
SECTION "_UnownMFrontpic", ROMX
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.static.2bpp.lz"
SECTION "_UnownFFrontpic", ROMX
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.static.2bpp.lz"
SECTION "_NatuBackpic", ROMX
NatuBackpic:         INCBIN "gfx/pokemon/natu/back.2bpp.lz"
SECTION "_UnownAFrontpic", ROMX
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.static.2bpp.lz"
SECTION "_GolemBackpic", ROMX
GolemBackpic:        INCBIN "gfx/pokemon/golem/back.2bpp.lz"
SECTION "_UnownUFrontpic", ROMX
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.static.2bpp.lz"
SECTION "_DiglettBackpic", ROMX
DiglettBackpic:      INCBIN "gfx/pokemon/diglett/back.2bpp.lz"
SECTION "_UnownQFrontpic", ROMX
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.static.2bpp.lz"
SECTION "_UnownPFrontpic", ROMX
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.static.2bpp.lz"
SECTION "_UnownCBackpic", ROMX
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
SECTION "_JynxBackpic", ROMX
JynxBackpic:         INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
SECTION "_GolbatBackpic", ROMX
GolbatBackpic:       INCBIN "gfx/pokemon/golbat/back.2bpp.lz"
SECTION "_UnownYFrontpic", ROMX
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.static.2bpp.lz"
SECTION "_UnownGBackpic", ROMX
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
SECTION "_UnownIFrontpic", ROMX
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.static.2bpp.lz"
SECTION "_UnownVBackpic", ROMX
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
SECTION "_ForretressBackpic", ROMX
ForretressBackpic:   INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
SECTION "_UnownSBackpic", ROMX
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
SECTION "_UnownRFrontpic", ROMX
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.static.2bpp.lz"
SECTION "_UnownEBackpic", ROMX
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
SECTION "_UnownJBackpic", ROMX
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
SECTION "_UnownBBackpic", ROMX
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
SECTION "_UnownOBackpic", ROMX
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
SECTION "_UnownZBackpic", ROMX
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
SECTION "_UnownWBackpic", ROMX
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
SECTION "_UnownNBackpic", ROMX
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
SECTION "_UnownABackpic", ROMX
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
SECTION "_UnownMBackpic", ROMX
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
SECTION "_UnownKBackpic", ROMX
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
SECTION "_UnownTBackpic", ROMX
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
SECTION "_UnownXBackpic", ROMX
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
SECTION "_UnownLBackpic", ROMX
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
SECTION "_UnownUBackpic", ROMX
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
SECTION "_UnownQBackpic", ROMX
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
SECTION "_UnownYBackpic", ROMX
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
SECTION "_UnownPBackpic", ROMX
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
SECTION "_UnownIBackpic", ROMX
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
SECTION "_UnownRBackpic", ROMX
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"



SECTION "_FurretFrontpic", ROMX
FurretFrontpic: INCBIN "gfx/pokemon/furret/front.static.2bpp.lz"
SECTION "_CoinpurFrontpic", ROMX
CoinpurFrontpic: INCBIN "gfx/pokemon/coinpur/front.static.2bpp.lz"
SECTION "_CoinpurBackpic", ROMX
CoinpurBackpic:  INCBIN "gfx/pokemon/coinpur/back.2bpp.lz"
SECTION "_WooperFrontpic", ROMX
WooperFrontpic: INCBIN "gfx/pokemon/wooper/front.static.2bpp.lz"
SECTION "_KatuFrontpic", ROMX
KatuFrontpic:   INCBIN "gfx/pokemon/katu/front.static.2bpp.lz"
SECTION "_KatuBackpic", ROMX
KatuBackpic:    INCBIN "gfx/pokemon/katu/back.2bpp.lz"
InstructorPic:  INCBIN "gfx/trainers/instructor.2bpp.lz"
SECTION "_AdbarstorkFrontpic", ROMX
AdbarstorkFrontpic: INCBIN "gfx/pokemon/adbarstork/front.static.2bpp.lz"
SECTION "_AdbarstorkBackpic", ROMX
AdbarstorkBackpic: INCBIN "gfx/pokemon/adbarstork/back.2bpp.lz"
ProfessorPic: INCBIN "gfx/trainers/professor.2bpp.lz"
SECTION "_PupperonFrontpic", ROMX
PupperonFrontpic: INCBIN "gfx/pokemon/pupperon/front.static.2bpp.lz"
SECTION "_PupperonBackpic", ROMX
PupperonBackpic: INCBIN "gfx/pokemon/pupperon/back.2bpp.lz"
SECTION "_BipullaFrontpic", ROMX
BipullaFrontpic: INCBIN "gfx/pokemon/bipulla/front.static.2bpp.lz"
SECTION "_BipullaBackpic", ROMX
BipullaBackpic: INCBIN "gfx/pokemon/bipulla/back.2bpp.lz"
ProdigyPic: INCBIN "gfx/trainers/prodigy.2bpp.lz"
SoldierPic:  INCBIN "gfx/trainers/soldier.2bpp.lz"
FledglingPic: INCBIN "gfx/trainers/fledgling.2bpp.lz"
BallsmithPic: INCBIN "gfx/trainers/ballsmith.2bpp.lz"
MysticPic: INCBIN "gfx/trainers/mystic.2bpp.lz"
RockClimberPic: INCBIN "gfx/trainers/rock_climber.2bpp.lz"
SECTION "_MoibelleFrontpic", ROMX
MoibelleFrontpic: INCBIN "gfx/pokemon/moibelle/front.static.2bpp.lz"
SECTION "_MoibelleBackpic", ROMX
MoibelleBackpic:  INCBIN "gfx/pokemon/moibelle/back.2bpp.lz"
SECTION "_BelledamFrontpic", ROMX
BelledamFrontpic: INCBIN "gfx/pokemon/belledam/front.static.2bpp.lz"
SECTION "_BelledamBackpic", ROMX
BelledamBackpic: INCBIN "gfx/pokemon/belledam/back.2bpp.lz"
SECTION "_CleflingFrontpic", ROMX
CleflingFrontpic: INCBIN "gfx/pokemon/clefling/front.static.2bpp.lz"
SECTION "_CleflingBackpic", ROMX
CleflingBackpic: INCBIN "gfx/pokemon/clefling/back.2bpp.lz"
SECTION "_PetamoleFrontpic", ROMX
PetamoleFrontpic: INCBIN "gfx/pokemon/petamole/front.static.2bpp.lz"
SECTION "_PetamoleBackpic", ROMX
PetamoleBackpic: INCBIN "gfx/pokemon/petamole/back.2bpp.lz"
SECTION "_HitmontopFrontpic", ROMX
HitmontopFrontpic: INCBIN "gfx/pokemon/hitmontop/front.static.2bpp.lz"
SECTION "_HitmontopBackpic", ROMX
HitmontopBackpic: INCBIN "gfx/pokemon/hitmontop/back.2bpp.lz"



SECTION "_LuxswanFrontpic", ROMX
LuxswanFrontpic: INCBIN "gfx/pokemon/luxswan/front.static.2bpp.lz"
SECTION "_LuxswanBackpic", ROMX
LuxswanBackpic: INCBIN "gfx/pokemon/luxswan/back.2bpp.lz"
SECTION "_PhanpyFrontpic", ROMX
PhanpyFrontpic: INCBIN "gfx/pokemon/phanpy/front.static.2bpp.lz"
SECTION "_PhanpyBackpic", ROMX
PhanpyBackpic:  INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
SECTION "_HoppipFrontpic", ROMX
HoppipFrontpic: INCBIN "gfx/pokemon/hoppip/front.static.2bpp.lz"
SECTION "_HoppipBackpic", ROMX
HoppipBackpic:  INCBIN "gfx/pokemon/hoppip/back.2bpp.lz"
SECTION "_TonbossFrontpic", ROMX
TonbossFrontpic: INCBIN "gfx/pokemon/tonboss/front.static.2bpp.lz"
SECTION "_TonbossBackpic", ROMX
TonbossBackpic:  INCBIN "gfx/pokemon/tonboss/back.2bpp.lz"
SECTION "_MallodyFrontpic", ROMX
MallodyFrontpic: INCBIN "gfx/pokemon/mallody/front.static.2bpp.lz"
SECTION "_MallodyBackpic", ROMX
MallodyBackpic:  INCBIN "gfx/pokemon/mallody/back.2bpp.lz"
SECTION "_CamouflakeFrontpic", ROMX
CamouflakeFrontpic: INCBIN "gfx/pokemon/camouflake/front.static.2bpp.lz"
SECTION "_CamouflakeBackpic", ROMX
CamouflakeBackpic:  INCBIN "gfx/pokemon/camouflake/back.2bpp.lz"
SECTION "_BellignanFrontpic", ROMX
BellignanFrontpic:INCBIN "gfx/pokemon/bellignan/front.static.2bpp.lz"
SECTION "_BellignanBackpic", ROMX
BellignanBackpic: INCBIN "gfx/pokemon/bellignan/back.2bpp.lz"



SportsmanPic:  INCBIN "gfx/trainers/sportsman.2bpp.lz"
ManchildPic: INCBIN "gfx/trainers/manchild.2bpp.lz"
SECTION "_CoaltaFrontpic", ROMX
CoaltaFrontpic: INCBIN "gfx/pokemon/coalta/front.static.2bpp.lz"
SECTION "_CoaltaBackpic", ROMX
CoaltaBackpic:  INCBIN "gfx/pokemon/coalta/back.2bpp.lz"
SECTION "_BurgelaFrontpic", ROMX
BurgelaFrontpic: INCBIN "gfx/pokemon/burgela/front.static.2bpp.lz"
SECTION "_BurgelaBackpic", ROMX
BurgelaBackpic:  INCBIN "gfx/pokemon/burgela/back.2bpp.lz"
SECTION "_VulpiiiFrontpic", ROMX
VulpiiiFrontpic: INCBIN "gfx/pokemon/vulpiii/front.static.2bpp.lz"
SECTION "_VulpiiiBackpic", ROMX
VulpiiiBackpic:  INCBIN "gfx/pokemon/vulpiii/back.2bpp.lz"
SECTION "_WorfursFrontpic", ROMX
WorfursFrontpic: INCBIN "gfx/pokemon/worfurs/front.static.2bpp.lz"
SECTION "_WorfursBackpic", ROMX
WorfursBackpic:  INCBIN "gfx/pokemon/worfurs/back.2bpp.lz"
SECTION "_DodaerieFrontpic", ROMX
DodaerieFrontpic: INCBIN "gfx/pokemon/dodaerie/front.static.2bpp.lz"
SECTION "_DodaerieBackpic", ROMX
DodaerieBackpic:  INCBIN "gfx/pokemon/dodaerie/back.2bpp.lz"
SECTION "_FarfetchDFrontpic", ROMX
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.static.2bpp.lz"
SECTION "_SkiploomFrontpic", ROMX
SkiploomFrontpic:    INCBIN "gfx/pokemon/skiploom/front.static.2bpp.lz"
SECTION "_TopsyspotFrontpic", ROMX
TopsyspotFrontpic: INCBIN "gfx/pokemon/topsyspot/front.static.2bpp.lz"
SECTION "_TopsyspotBackpic", ROMX
TopsyspotBackpic:  INCBIN "gfx/pokemon/topsyspot/back.2bpp.lz"
SECTION "_KabutoFrontpic", ROMX
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.static.2bpp.lz"
SECTION "_TriculesFrontpic", ROMX
TriculesFrontpic: INCBIN "gfx/pokemon/tricules/front.static.2bpp.lz"
SECTION "_TriculesBackpic", ROMX
TriculesBackpic:  INCBIN "gfx/pokemon/tricules/back.2bpp.lz"
SECTION "_ChomoswineFrontpic", ROMX
ChomoswineFrontpic: INCBIN "gfx/pokemon/chomoswine/front.static.2bpp.lz"
SECTION "_ChomoswineBackpic", ROMX
ChomoswineBackpic:  INCBIN "gfx/pokemon/chomoswine/back.2bpp.lz"
SECTION "_ShuqlourFrontpic", ROMX
ShuqlourFrontpic: INCBIN "gfx/pokemon/shuqlour/front.static.2bpp.lz"
SECTION "_ShuqlourBackpic", ROMX
ShuqlourBackpic:  INCBIN "gfx/pokemon/shuqlour/back.2bpp.lz"
SECTION "_ParasporFrontpic", ROMX
ParasporFrontpic: INCBIN "gfx/pokemon/paraspor/front.static.2bpp.lz"
SECTION "_ParasporBackpic", ROMX
ParasporBackpic:  INCBIN "gfx/pokemon/paraspor/back.2bpp.lz"
SECTION "_WearlycanFrontpic", ROMX
WearlycanFrontpic: INCBIN "gfx/pokemon/wearlycan/front.static.2bpp.lz"
SECTION "_WearlycanBackpic", ROMX
WearlycanBackpic:  INCBIN "gfx/pokemon/wearlycan/back.2bpp.lz"
SECTION "_MolambinoFrontpic", ROMX
MolambinoFrontpic: INCBIN "gfx/pokemon/molambino/front.static.2bpp.lz"
SECTION "_MolambinoBackpic", ROMX
MolambinoBackpic:  INCBIN "gfx/pokemon/molambino/back.2bpp.lz"



SECTION "_ClefairyBackpic", ROMX
ClefairyBackpic:     INCBIN "gfx/pokemon/clefairy/back.2bpp.lz"
SECTION "_VenonatBackpic", ROMX
VenonatBackpic:      INCBIN "gfx/pokemon/venonat/back.2bpp.lz"
SECTION "_BellossomBackpic", ROMX
BellossomBackpic:    INCBIN "gfx/pokemon/bellossom/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
SECTION "_SwinubBackpic", ROMX
SwinubBackpic:       INCBIN "gfx/pokemon/swinub/back.2bpp.lz"
SECTION "_IgglybuffFrontpic", ROMX
IgglybuffFrontpic:   INCBIN "gfx/pokemon/igglybuff/front.static.2bpp.lz"
SECTION "_RaticateBackpic", ROMX
RaticateBackpic:     INCBIN "gfx/pokemon/raticate/back.2bpp.lz"
SECTION "_VulpixBackpic", ROMX
VulpixBackpic:       INCBIN "gfx/pokemon/vulpix/back.2bpp.lz"
SECTION "_EkansBackpic", ROMX
EkansBackpic:        INCBIN "gfx/pokemon/ekans/back.2bpp.lz"
SECTION "_SeakingBackpic", ROMX
SeakingBackpic:      INCBIN "gfx/pokemon/seaking/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
SECTION "_PsyduckBackpic", ROMX
PsyduckBackpic:      INCBIN "gfx/pokemon/psyduck/back.2bpp.lz"
SECTION "_PikachuBackpic", ROMX
PikachuBackpic:      INCBIN "gfx/pokemon/pikachu/back.2bpp.lz"
SECTION "_MareepBackpic", ROMX
MareepBackpic:       INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
SECTION "_RemoraidBackpic", ROMX
RemoraidBackpic:     INCBIN "gfx/pokemon/remoraid/back.2bpp.lz"
SECTION "_DittoFrontpic", ROMX
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.static.2bpp.lz"
SECTION "_KingdraBackpic", ROMX
KingdraBackpic:      INCBIN "gfx/pokemon/kingdra/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
SECTION "_KiwackiFrontpic", ROMX
KiwackiFrontpic:     INCBIN "gfx/pokemon/kiwacki/front.static.2bpp.lz"
SECTION "_KiwackiBackpic", ROMX
KiwackiBackpic:      INCBIN "gfx/pokemon/kiwacki/back.2bpp.lz"
SECTION "_SilkaneFrontpic", ROMX
SilkaneFrontpic:     INCBIN "gfx/pokemon/silkane/front.static.2bpp.lz"
SECTION "_SilkaneBackpic", ROMX
SilkaneBackpic:      INCBIN "gfx/pokemon/silkane/back.2bpp.lz"
SECTION "_MorphobiaFrontpic", ROMX
MorphobiaFrontpic:   INCBIN "gfx/pokemon/morphobia/front.static.2bpp.lz"
SECTION "_MorphobiaBackpic", ROMX
MorphobiaBackpic:    INCBIN "gfx/pokemon/morphobia/back.2bpp.lz"
SECTION "_TerrachnidFrontpic", ROMX
TerrachnidFrontpic:  INCBIN "gfx/pokemon/terrachnid/front.static.2bpp.lz"
SECTION "_TerrachnidBackpic", ROMX
TerrachnidBackpic:   INCBIN "gfx/pokemon/terrachnid/back.2bpp.lz"
SECTION "_SmujjFrontpic", ROMX
SmujjFrontpic:	     INCBIN "gfx/pokemon/smujj/front.static.2bpp.lz"
SECTION "_SmujjBackpic", ROMX
SmujjBackpic:	     INCBIN "gfx/pokemon/smujj/back.2bpp.lz"
SECTION "_TykerFrontpic", ROMX
TykerFrontpic:	     INCBIN "gfx/pokemon/tyker/front.static.2bpp.lz"
SECTION "_TykerBackpic", ROMX
TykerBackpic:	     INCBIN "gfx/pokemon/tyker/back.2bpp.lz"
SECTION "_StraigarFrontpic", ROMX
StraigarFrontpic:	 INCBIN "gfx/pokemon/straigar/front.static.2bpp.lz"
SECTION "_StraigarBackpic", ROMX
StraigarBackpic:	 INCBIN "gfx/pokemon/straigar/back.2bpp.lz"
SECTION "_GorotoraFrontpic", ROMX
GorotoraFrontpic:	 INCBIN "gfx/pokemon/gorotora/front.static.2bpp.lz"
SECTION "_GorotoraBackpic", ROMX
GorotoraBackpic:	 INCBIN "gfx/pokemon/gorotora/back.2bpp.lz"
SECTION "_KoalyptusFrontpic", ROMX
KoalyptusFrontpic:	 INCBIN "gfx/pokemon/koalyptus/front.static.2bpp.lz"
SECTION "_KoalyptusBackpic", ROMX
KoalyptusBackpic:	 INCBIN "gfx/pokemon/koalyptus/back.2bpp.lz"



SECTION "_BallerineFrontpic", ROMX
BallerineFrontpic:	INCBIN "gfx/pokemon/ballerine/front.static.2bpp.lz"
SECTION "_BallerineBackpic", ROMX
BallerineBackpic:	INCBIN "gfx/pokemon/ballerine/back.2bpp.lz"
SECTION "_OrefryFrontpic", ROMX
OrefryFrontpic:	    INCBIN "gfx/pokemon/orefry/front.static.2bpp.lz"
SECTION "_OrefryBackpic", ROMX
OrefryBackpic:	    INCBIN "gfx/pokemon/orefry/back.2bpp.lz"
SECTION "_FennecurseFrontpic", ROMX
FennecurseFrontpic:	INCBIN "gfx/pokemon/fennecurse/front.static.2bpp.lz"
SECTION "_FennecurseBackpic", ROMX
FennecurseBackpic:	INCBIN "gfx/pokemon/fennecurse/back.2bpp.lz"
SECTION "_OrijoeyFrontpic", ROMX
OrijoeyFrontpic:	INCBIN "gfx/pokemon/orijoey/front.static.2bpp.lz"
SECTION "_OrijoeyBackpic", ROMX
OrijoeyBackpic:	    INCBIN "gfx/pokemon/orijoey/back.2bpp.lz"
SECTION "_AggroswineFrontpic", ROMX
AggroswineFrontpic:	INCBIN "gfx/pokemon/aggroswine/front.static.2bpp.lz"
SECTION "_AggroswineBackpic", ROMX
AggroswineBackpic:	INCBIN "gfx/pokemon/aggroswine/back.2bpp.lz"
SECTION "_ShuricornFrontpic", ROMX
ShuricornFrontpic:	INCBIN "gfx/pokemon/shuricorn/front.static.2bpp.lz"
SECTION "_ShuricornBackpic", ROMX
ShuricornBackpic:   INCBIN "gfx/pokemon/shuricorn/back.2bpp.lz"



SECTION "_GermifrostFrontpic", ROMX
GermifrostFrontpic:	INCBIN "gfx/pokemon/germifrost/front.static.2bpp.lz"
SECTION "_GermifrostBackpic", ROMX
GermifrostBackpic:	INCBIN "gfx/pokemon/germifrost/back.2bpp.lz"
SECTION "_VegelancheFrontpic", ROMX
VegelancheFrontpic:	INCBIN "gfx/pokemon/vegelanche/front.static.2bpp.lz"
SECTION "_VegelancheBackpic", ROMX
VegelancheBackpic:	INCBIN "gfx/pokemon/vegelanche/back.2bpp.lz"
SECTION "_SnouwrbunFrontpic", ROMX
SnouwrbunFrontpic:	INCBIN "gfx/pokemon/snouwrbun/front.static.2bpp.lz"
SECTION "_SnouwrbunBackpic", ROMX
SnouwrbunBackpic:	INCBIN "gfx/pokemon/snouwrbun/back.2bpp.lz"
SECTION "_NecrorexFrontpic", ROMX
NecrorexFrontpic:	INCBIN "gfx/pokemon/necrorex/front.static.2bpp.lz"
SECTION "_NecrorexBackpic", ROMX
NecrorexBackpic:	INCBIN "gfx/pokemon/necrorex/back.2bpp.lz"
LassNieNiePic:       INCBIN "gfx/trainers/lassnienie.2bpp.lz"
SECTION "_PhandarinFrontpic", ROMX
PhandarinFrontpic:	INCBIN "gfx/pokemon/phandarin/front.static.2bpp.lz"
SECTION "_PhandarinBackpic", ROMX
PhandarinBackpic:	INCBIN "gfx/pokemon/phandarin/back.2bpp.lz"
SECTION "_StromenFrontpic", ROMX
StromenFrontpic:	INCBIN "gfx/pokemon/stromen/front.static.2bpp.lz"
SECTION "_StromenBackpic", ROMX
StromenBackpic:	    INCBIN "gfx/pokemon/stromen/back.2bpp.lz"
SECTION "_CubburnFrontpic", ROMX
CubburnFrontpic:	INCBIN "gfx/pokemon/cubburn/front.static.2bpp.lz"
SECTION "_CubburnBackpic", ROMX
CubburnBackpic:	    INCBIN "gfx/pokemon/cubburn/back.2bpp.lz"
SECTION "_NurssumFrontpic", ROMX
NurssumFrontpic:	INCBIN "gfx/pokemon/nurssum/front.static.2bpp.lz"
SECTION "_NurssumBackpic", ROMX
NurssumBackpic:	    INCBIN "gfx/pokemon/nurssum/back.2bpp.lz"
SECTION "_FlambearFrontpic", ROMX
FlambearFrontpic:	INCBIN "gfx/pokemon/flambear/front.static.2bpp.lz"
SECTION "_FlambearBackpic", ROMX
FlambearBackpic:	INCBIN "gfx/pokemon/flambear/back.2bpp.lz"
SECTION "_BruinusFrontpic", ROMX
BruinusFrontpic:	INCBIN "gfx/pokemon/bruinus/front.static.2bpp.lz"
SECTION "_BruinusBackpic", ROMX
BruinusBackpic:	    INCBIN "gfx/pokemon/bruinus/back.2bpp.lz"
SECTION "_PalssioFrontpic", ROMX
PalssioFrontpic:	INCBIN "gfx/pokemon/palssio/front.static.2bpp.lz"
SECTION "_PalssioBackpic", ROMX
PalssioBackpic:	    INCBIN "gfx/pokemon/palssio/back.2bpp.lz"
SECTION "_PressioFrontpic", ROMX
PressioFrontpic:	INCBIN "gfx/pokemon/pressio/front.static.2bpp.lz"
SECTION "_PressioBackpic", ROMX
PressioBackpic:	    INCBIN "gfx/pokemon/pressio/back.2bpp.lz"
SECTION "_DonmarinFrontpic", ROMX
DonmarinFrontpic:	INCBIN "gfx/pokemon/donmarin/front.static.2bpp.lz"
SECTION "_DonmarinBackpic", ROMX
DonmarinBackpic:	INCBIN "gfx/pokemon/donmarin/back.2bpp.lz"
SECTION "_LeafeonFrontpic", ROMX
LeafeonFrontpic:	INCBIN "gfx/pokemon/leafeon/front.static.2bpp.lz"
SECTION "_LeafeonBackpic", ROMX
LeafeonBackpic:	    INCBIN "gfx/pokemon/leafeon/back.2bpp.lz"
SECTION "_KudatsubeFrontpic", ROMX
KudatsubeFrontpic:	INCBIN "gfx/pokemon/kudatsube/front.static.2bpp.lz"
SECTION "_KudatsubeBackpic", ROMX
KudatsubeBackpic:	INCBIN "gfx/pokemon/kudatsube/back.2bpp.lz"
SECTION "_LickilickyFrontpic", ROMX
LickilickyFrontpic:	INCBIN "gfx/pokemon/lickilicky/front.static.2bpp.lz"
SECTION "_LickilickyBackpic", ROMX
LickilickyBackpic:	INCBIN "gfx/pokemon/lickilicky/back.2bpp.lz"
SECTION "_BiteelFrontpic", ROMX
BiteelFrontpic:	    INCBIN "gfx/pokemon/biteel/front.static.2bpp.lz"
SECTION "_BiteelBackpic", ROMX
BiteelBackpic:	    INCBIN "gfx/pokemon/biteel/back.2bpp.lz"
SECTION "_LurreelFrontpic", ROMX
LurreelFrontpic:	INCBIN "gfx/pokemon/lurreel/front.static.2bpp.lz"
SECTION "_LurreelBackpic", ROMX
LurreelBackpic:	    INCBIN "gfx/pokemon/lurreel/back.2bpp.lz"



SECTION "_KokopelliFrontpic", ROMX
KokopelliFrontpic:	INCBIN "gfx/pokemon/kokopelli/front.static.2bpp.lz"
SECTION "_KokopelliBackpic", ROMX
KokopelliBackpic:   INCBIN "gfx/pokemon/kokopelli/back.2bpp.lz"
SECTION "_AngoreFrontpic", ROMX
AngoreFrontpic:	    INCBIN "gfx/pokemon/angore/front.static.2bpp.lz"
SECTION "_AngoreBackpic", ROMX
AngoreBackpic:      INCBIN "gfx/pokemon/angore/back.2bpp.lz"
SECTION "_AlumaidenFrontpic", ROMX
AlumaidenFrontpic:	INCBIN "gfx/pokemon/alumaiden/front.static.2bpp.lz"
SECTION "_AlumaidenBackpic", ROMX
AlumaidenBackpic:   INCBIN "gfx/pokemon/alumaiden/back.2bpp.lz"
SECTION "_ValhaldraFrontpic", ROMX
ValhaldraFrontpic:	INCBIN "gfx/pokemon/valhaldra/front.static.2bpp.lz"
SECTION "_ValhaldraBackpic", ROMX
ValhaldraBackpic:   INCBIN "gfx/pokemon/valhaldra/back.2bpp.lz"
SECTION "_KomaitiffFrontpic", ROMX
KomaitiffFrontpic:	INCBIN "gfx/pokemon/komaitiff/front.static.2bpp.lz"
SECTION "_KomaitiffBackpic", ROMX
KomaitiffBackpic:   INCBIN "gfx/pokemon/komaitiff/back.2bpp.lz"



SECTION "_AercrowFrontpic", ROMX
AercrowFrontpic:	INCBIN "gfx/pokemon/aercrow/front.static.2bpp.lz"
SECTION "_AercrowBackpic", ROMX
AercrowBackpic:     INCBIN "gfx/pokemon/aercrow/back.2bpp.lz"
SECTION "_GargraniteFrontpic", ROMX
GargraniteFrontpic:	INCBIN "gfx/pokemon/gargranite/front.static.2bpp.lz"
SECTION "_GargraniteBackpic", ROMX
GargraniteBackpic:  INCBIN "gfx/pokemon/gargranite/back.2bpp.lz"
SECTION "_GesticuteFrontpic", ROMX
GesticuteFrontpic:	INCBIN "gfx/pokemon/gesticute/front.static.2bpp.lz"
SECTION "_GesticuteBackpic", ROMX
GesticuteBackpic:   INCBIN "gfx/pokemon/gesticute/back.2bpp.lz"
SECTION "_RattlitFrontpic", ROMX
RattlitFrontpic:	INCBIN "gfx/pokemon/rattlit/front.static.2bpp.lz"
SECTION "_RattlitBackpic", ROMX
RattlitBackpic:     INCBIN "gfx/pokemon/rattlit/back.2bpp.lz"



SECTION "_AudinoFrontpic", ROMX
AudinoFrontpic:	    INCBIN "gfx/pokemon/audino/front.static.2bpp.lz"
SECTION "_AudinoBackpic", ROMX
AudinoBackpic:      INCBIN "gfx/pokemon/audino/back.2bpp.lz"
SECTION "_MunchlaxFrontpic", ROMX
MunchlaxFrontpic:	INCBIN "gfx/pokemon/munchlax/front.static.2bpp.lz"
SECTION "_MunchlaxBackpic", ROMX
MunchlaxBackpic:    INCBIN "gfx/pokemon/munchlax/back.2bpp.lz"
SECTION "_PoryginFrontpic", ROMX
PoryginFrontpic:	INCBIN "gfx/pokemon/porygin/front.static.2bpp.lz"
SECTION "_PoryginBackpic", ROMX
PoryginBackpic:     INCBIN "gfx/pokemon/porygin/back.2bpp.lz"
SECTION "_MinccinoFrontpic", ROMX
MinccinoFrontpic:	INCBIN "gfx/pokemon/minccino/front.static.2bpp.lz"
SECTION "_MinccinoBackpic", ROMX
MinccinoBackpic:    INCBIN "gfx/pokemon/minccino/back.2bpp.lz"
SECTION "_CinccinoFrontpic", ROMX
CinccinoFrontpic:	INCBIN "gfx/pokemon/cinccino/front.static.2bpp.lz"
SECTION "_CinccinoBackpic", ROMX
CinccinoBackpic:    INCBIN "gfx/pokemon/cinccino/back.2bpp.lz"
SECTION "_SphealFrontpic", ROMX
SphealFrontpic:	    INCBIN "gfx/pokemon/spheal/front.static.2bpp.lz"
SECTION "_SphealBackpic", ROMX
SphealBackpic:      INCBIN "gfx/pokemon/spheal/back.2bpp.lz"
SECTION "_KukulcanFrontpic", ROMX
KukulcanFrontpic:	INCBIN "gfx/pokemon/kukulcan/front.static.2bpp.lz"
SECTION "_KukulcanBackpic", ROMX
KukulcanBackpic:    INCBIN "gfx/pokemon/kukulcan/back.2bpp.lz"
SECTION "_PiplupFrontpic", ROMX
PiplupFrontpic:	    INCBIN "gfx/pokemon/piplup/front.static.2bpp.lz"
SECTION "_PiplupBackpic", ROMX
PiplupBackpic:      INCBIN "gfx/pokemon/piplup/back.2bpp.lz"
SECTION "_WailmerFrontpic", ROMX
WailmerFrontpic:	INCBIN "gfx/pokemon/wailmer/front.static.2bpp.lz"
SECTION "_WailmerBackpic", ROMX
WailmerBackpic:     INCBIN "gfx/pokemon/wailmer/back.2bpp.lz"
SECTION "_WailordFrontpic", ROMX
WailordFrontpic:    INCBIN "gfx/pokemon/wailord/front.static.2bpp.lz"
SECTION "_WailordBackpic", ROMX
WailordBackpic:     INCBIN "gfx/pokemon/wailord/back.2bpp.lz"
SECTION "_CorasunFrontpic", ROMX
CorasunFrontpic:	INCBIN "gfx/pokemon/corasun/front.static.2bpp.lz"
SECTION "_CorasunBackpic", ROMX
CorasunBackpic:     INCBIN "gfx/pokemon/corasun/back.2bpp.lz"
SECTION "_MambokingFrontpic", ROMX
MambokingFrontpic:  INCBIN "gfx/pokemon/mamboking/front.static.2bpp.lz"
SECTION "_MambokingBackpic", ROMX
MambokingBackpic:   INCBIN "gfx/pokemon/mamboking/back.2bpp.lz"
SECTION "_NorspruceFrontpic", ROMX
NorspruceFrontpic:  INCBIN "gfx/pokemon/norspruce/front.static.2bpp.lz"
SECTION "_NorspruceBackpic", ROMX
NorspruceBackpic:   INCBIN "gfx/pokemon/norspruce/back.2bpp.lz"


SECTION "_MagstaceanFrontpic", ROMX
MagstaceanFrontpic: INCBIN "gfx/pokemon/magstacean/front.static.2bpp.lz"
SECTION "_MagstaceanBackpic", ROMX
MagstaceanBackpic:  INCBIN "gfx/pokemon/magstacean/back.2bpp.lz"
SECTION "_RivalWaterPic", ROMX
RivalWaterPic:  INCBIN "gfx/trainers/rivalwater.2bpp.lz"

INCLUDE "gfx/pics_animated.asm"
