;pics 2

SECTION "Pics 1 Animated", ROMX

HoOhFrontpicAnim:        INCBIN "gfx/pokemon/ho_oh/front.animated.2bpp.lz"
MachampFrontpicAnim:     INCBIN "gfx/pokemon/machamp/front.animated.2bpp.lz"
NinetalesFrontpicAnim:   INCBIN "gfx/pokemon/ninetales/front.animated.2bpp.lz"
FeraligatrFrontpicAnim:  INCBIN "gfx/pokemon/feraligatr/front.animated.2bpp.lz"
NidokingFrontpicAnim:    INCBIN "gfx/pokemon/nidoking/front.animated.2bpp.lz"
RaikouFrontpicAnim:      INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
LugiaFrontpicAnim:       INCBIN "gfx/pokemon/lugia/front.animated.2bpp.lz"
ArticunoFrontpicAnim:    INCBIN "gfx/pokemon/articuno/front.animated.2bpp.lz"
TaurosFrontpicAnim:      INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
VenusaurFrontpicAnim:    INCBIN "gfx/pokemon/venusaur/front.animated.2bpp.lz"
EnteiFrontpicAnim:       INCBIN "gfx/pokemon/entei/front.animated.2bpp.lz"
SuicuneFrontpicAnim:     INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
TyphlosionFrontpicAnim:  INCBIN "gfx/pokemon/typhlosion/front.animated.2bpp.lz"

SECTION "Pics 2 Animated", ROMX

BlastoiseFrontpicAnim:   INCBIN "gfx/pokemon/blastoise/front.animated.2bpp.lz"
RapidashFrontpicAnim:    INCBIN "gfx/pokemon/rapidash/front.animated.2bpp.lz"
MeganiumFrontpicAnim:    INCBIN "gfx/pokemon/meganium/front.animated.2bpp.lz"
NidoqueenFrontpicAnim:   INCBIN "gfx/pokemon/nidoqueen/front.animated.2bpp.lz"
HitmonleeFrontpicAnim:   INCBIN "gfx/pokemon/hitmonlee/front.animated.2bpp.lz"
ScizorFrontpicAnim:      INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
BeedrillFrontpicAnim:    INCBIN "gfx/pokemon/beedrill/front.animated.2bpp.lz"
ArcanineFrontpicAnim:    INCBIN "gfx/pokemon/arcanine/front.animated.2bpp.lz"
TyranitarFrontpicAnim:   INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
MoltresFrontpicAnim:     INCBIN "gfx/pokemon/moltres/front.animated.2bpp.lz"
ZapdosFrontpicAnim:      INCBIN "gfx/pokemon/zapdos/front.animated.2bpp.lz"
ArbokFrontpicAnim:       INCBIN "gfx/pokemon/arbok/front.animated.2bpp.lz"
MewtwoFrontpicAnim:      INCBIN "gfx/pokemon/mewtwo/front.animated.2bpp.lz"
FearowFrontpicAnim:      INCBIN "gfx/pokemon/fearow/front.animated.2bpp.lz"
CharizardFrontpicAnim:   INCBIN "gfx/pokemon/charizard/front.animated.2bpp.lz"
QuilavaFrontpicAnim:     INCBIN "gfx/pokemon/quilava/front.animated.2bpp.lz"

SECTION "Pics 3 Animated", ROMX

SteelixFrontpicAnim:     INCBIN "gfx/pokemon/steelix/front.animated.2bpp.lz"
AlakazamFrontpicAnim:    INCBIN "gfx/pokemon/alakazam/front.animated.2bpp.lz"
GyaradosFrontpicAnim:    INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
KangaskhanFrontpicAnim:  INCBIN "gfx/pokemon/kangaskhan/front.animated.2bpp.lz"
RhydonFrontpicAnim:      INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
GolduckFrontpicAnim:     INCBIN "gfx/pokemon/golduck/front.animated.2bpp.lz"
RhyhornFrontpicAnim:     INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
PidgeotFrontpicAnim:     INCBIN "gfx/pokemon/pidgeot/front.animated.2bpp.lz"
SlowbroFrontpicAnim:     INCBIN "gfx/pokemon/slowbro/front.animated.2bpp.lz"
ButterfreeFrontpicAnim:  INCBIN "gfx/pokemon/butterfree/front.animated.2bpp.lz"
WeezingFrontpicAnim:     INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
CloysterFrontpicAnim:    INCBIN "gfx/pokemon/cloyster/front.animated.2bpp.lz"
SkarmoryFrontpicAnim:    INCBIN "gfx/pokemon/skarmory/front.animated.2bpp.lz"
DewgongFrontpicAnim:     INCBIN "gfx/pokemon/dewgong/front.animated.2bpp.lz"
VictreebelFrontpicAnim:  INCBIN "gfx/pokemon/victreebel/front.animated.2bpp.lz"
RaichuFrontpicAnim:      INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
PrimeapeFrontpicAnim:    INCBIN "gfx/pokemon/primeape/front.animated.2bpp.lz"

SECTION "Pics 4 Animated", ROMX

DodrioFrontpicAnim:      INCBIN "gfx/pokemon/dodrio/front.animated.2bpp.lz"
SlowkingFrontpicAnim:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
OnixFrontpicAnim:        INCBIN "gfx/pokemon/onix/front.animated.2bpp.lz"
BlisseyFrontpicAnim:     INCBIN "gfx/pokemon/blissey/front.animated.2bpp.lz"
MachokeFrontpicAnim:     INCBIN "gfx/pokemon/machoke/front.animated.2bpp.lz"
DragoniteFrontpicAnim:   INCBIN "gfx/pokemon/dragonite/front.animated.2bpp.lz"
PoliwrathFrontpicAnim:   INCBIN "gfx/pokemon/poliwrath/front.animated.2bpp.lz"
ScytherFrontpicAnim:     INCBIN "gfx/pokemon/scyther/front.animated.2bpp.lz"
AerodactylFrontpicAnim:  INCBIN "gfx/pokemon/aerodactyl/front.animated.2bpp.lz"
SeakingFrontpicAnim:     INCBIN "gfx/pokemon/seaking/front.animated.2bpp.lz"
MukFrontpicAnim:         INCBIN "gfx/pokemon/muk/front.animated.2bpp.lz"
CroconawFrontpicAnim:    INCBIN "gfx/pokemon/croconaw/front.animated.2bpp.lz"
HypnoFrontpicAnim:       INCBIN "gfx/pokemon/hypno/front.animated.2bpp.lz"
NidorinoFrontpicAnim:    INCBIN "gfx/pokemon/nidorino/front.animated.2bpp.lz"
SandslashFrontpicAnim:   INCBIN "gfx/pokemon/sandslash/front.animated.2bpp.lz"
JolteonFrontpicAnim:     INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
DonphanFrontpicAnim:     INCBIN "gfx/pokemon/donphan/front.animated.2bpp.lz"
PinsirFrontpicAnim:      INCBIN "gfx/pokemon/pinsir/front.animated.2bpp.lz"
UnownEFrontpicAnim:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"

SECTION "Pics 5 Animated", ROMX

GolbatFrontpicAnim:      INCBIN "gfx/pokemon/golbat/front.animated.2bpp.lz"
KinglerFrontpicAnim:     INCBIN "gfx/pokemon/kingler/front.animated.2bpp.lz"
ExeggcuteFrontpicAnim:   INCBIN "gfx/pokemon/exeggcute/front.animated.2bpp.lz"
MagcargoFrontpicAnim:    INCBIN "gfx/pokemon/magcargo/front.animated.2bpp.lz"
PersianFrontpicAnim:     INCBIN "gfx/pokemon/persian/front.animated.2bpp.lz"
StantlerFrontpicAnim:    INCBIN "gfx/pokemon/stantler/front.animated.2bpp.lz"
RaticateFrontpicAnim:    INCBIN "gfx/pokemon/raticate/front.animated.2bpp.lz"
VenomothFrontpicAnim:    INCBIN "gfx/pokemon/venomoth/front.animated.2bpp.lz"
PolitoedFrontpicAnim:    INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
ElectabuzzFrontpicAnim:  INCBIN "gfx/pokemon/electabuzz/front.animated.2bpp.lz"
MantineFrontpicAnim:     INCBIN "gfx/pokemon/mantine/front.animated.2bpp.lz"
LickitungFrontpicAnim:   INCBIN "gfx/pokemon/lickitung/front.animated.2bpp.lz"
KingdraFrontpicAnim:     INCBIN "gfx/pokemon/kingdra/front.animated.2bpp.lz"
CharmeleonFrontpicAnim:  INCBIN "gfx/pokemon/charmeleon/front.animated.2bpp.lz"
KadabraFrontpicAnim:     INCBIN "gfx/pokemon/kadabra/front.animated.2bpp.lz"
ExeggutorFrontpicAnim:   INCBIN "gfx/pokemon/exeggutor/front.animated.2bpp.lz"
GastlyFrontpicAnim:      INCBIN "gfx/pokemon/gastly/front.animated.2bpp.lz"
AzumarillFrontpicAnim:   INCBIN "gfx/pokemon/azumarill/front.animated.2bpp.lz"
ParasectFrontpicAnim:    INCBIN "gfx/pokemon/parasect/front.animated.2bpp.lz"
MrMimeFrontpicAnim:      INCBIN "gfx/pokemon/mr__mime/front.animated.2bpp.lz"
HeracrossFrontpicAnim:   INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"

SECTION "Pics 6 Animated", ROMX

AriadosFrontpicAnim:     INCBIN "gfx/pokemon/ariados/front.animated.2bpp.lz"
NoctowlFrontpicAnim:     INCBIN "gfx/pokemon/noctowl/front.animated.2bpp.lz"
WartortleFrontpicAnim:   INCBIN "gfx/pokemon/wartortle/front.animated.2bpp.lz"
LaprasFrontpicAnim:      INCBIN "gfx/pokemon/lapras/front.animated.2bpp.lz"
GolemFrontpicAnim:       INCBIN "gfx/pokemon/golem/front.animated.2bpp.lz"
PoliwhirlFrontpicAnim:   INCBIN "gfx/pokemon/poliwhirl/front.animated.2bpp.lz"
UrsaringFrontpicAnim:    INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
HoundoomFrontpicAnim:    INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
KabutopsFrontpicAnim:    INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
AmpharosFrontpicAnim:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
NidorinaFrontpicAnim:    INCBIN "gfx/pokemon/nidorina/front.animated.2bpp.lz"
FlareonFrontpicAnim:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
VileplumeFrontpicAnim:   INCBIN "gfx/pokemon/vileplume/front.animated.2bpp.lz"
BayleefFrontpicAnim:     INCBIN "gfx/pokemon/bayleef/front.animated.2bpp.lz"
MagmarFrontpicAnim:      INCBIN "gfx/pokemon/magmar/front.animated.2bpp.lz"
TentacruelFrontpicAnim:  INCBIN "gfx/pokemon/tentacruel/front.animated.2bpp.lz"
ElekidFrontpicAnim:      INCBIN "gfx/pokemon/elekid/front.animated.2bpp.lz"
JumpluffFrontpicAnim:    INCBIN "gfx/pokemon/jumpluff/front.animated.2bpp.lz"
MarowakFrontpicAnim:     INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
VulpixFrontpicAnim:      INCBIN "gfx/pokemon/vulpix/front.animated.2bpp.lz"
GligarFrontpicAnim:      INCBIN "gfx/pokemon/gligar/front.animated.2bpp.lz"
DunsparceFrontpicAnim:   INCBIN "gfx/pokemon/dunsparce/front.animated.2bpp.lz"

SECTION "Pics 7 Animated", ROMX

VaporeonFrontpicAnim:    INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
GirafarigFrontpicAnim:   INCBIN "gfx/pokemon/girafarig/front.animated.2bpp.lz"
DrowzeeFrontpicAnim:     INCBIN "gfx/pokemon/drowzee/front.animated.2bpp.lz"
SneaselFrontpicAnim:     INCBIN "gfx/pokemon/sneasel/front.animated.2bpp.lz"
BellossomFrontpicAnim:   INCBIN "gfx/pokemon/bellossom/front.animated.2bpp.lz"
SnorlaxFrontpicAnim:     INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
WigglytuffFrontpicAnim:  INCBIN "gfx/pokemon/wigglytuff/front.animated.2bpp.lz"
YanmaFrontpicAnim:       INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
SmeargleFrontpicAnim:    INCBIN "gfx/pokemon/smeargle/front.animated.2bpp.lz"
ClefableFrontpicAnim:    INCBIN "gfx/pokemon/clefable/front.animated.2bpp.lz"
PonytaFrontpicAnim:      INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
MurkrowFrontpicAnim:     INCBIN "gfx/pokemon/murkrow/front.animated.2bpp.lz"
GravelerFrontpicAnim:    INCBIN "gfx/pokemon/graveler/front.animated.2bpp.lz"
StarmieFrontpicAnim:     INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
PidgeottoFrontpicAnim:   INCBIN "gfx/pokemon/pidgeotto/front.animated.2bpp.lz"
LedybaFrontpicAnim:      INCBIN "gfx/pokemon/ledyba/front.animated.2bpp.lz"
GengarFrontpicAnim:      INCBIN "gfx/pokemon/gengar/front.animated.2bpp.lz"
OmastarFrontpicAnim:     INCBIN "gfx/pokemon/omastar/front.animated.2bpp.lz"
PiloswineFrontpicAnim:   INCBIN "gfx/pokemon/piloswine/front.animated.2bpp.lz"
DugtrioFrontpicAnim:     INCBIN "gfx/pokemon/dugtrio/front.animated.2bpp.lz"
MagnetonFrontpicAnim:    INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
DragonairFrontpicAnim:   INCBIN "gfx/pokemon/dragonair/front.animated.2bpp.lz"
ForretressFrontpicAnim:  INCBIN "gfx/pokemon/forretress/front.animated.2bpp.lz"
TogeticFrontpicAnim:     INCBIN "gfx/pokemon/togetic/front.animated.2bpp.lz"

SECTION "Pics 8 Animated", ROMX

SeelFrontpicAnim:        INCBIN "gfx/pokemon/seel/front.animated.2bpp.lz"
CrobatFrontpicAnim:      INCBIN "gfx/pokemon/crobat/front.animated.2bpp.lz"
ChanseyFrontpicAnim:     INCBIN "gfx/pokemon/chansey/front.animated.2bpp.lz"
TangelaFrontpicAnim:     INCBIN "gfx/pokemon/tangela/front.animated.2bpp.lz"
SnubbullFrontpicAnim:    INCBIN "gfx/pokemon/snubbull/front.animated.2bpp.lz"
GranbullFrontpicAnim:    INCBIN "gfx/pokemon/granbull/front.animated.2bpp.lz"
MiltankFrontpicAnim:     INCBIN "gfx/pokemon/miltank/front.animated.2bpp.lz"
HaunterFrontpicAnim:     INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
SunfloraFrontpicAnim:    INCBIN "gfx/pokemon/sunflora/front.animated.2bpp.lz"
UmbreonFrontpicAnim:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
ChikoritaFrontpicAnim:   INCBIN "gfx/pokemon/chikorita/front.animated.2bpp.lz"
GoldeenFrontpicAnim:     INCBIN "gfx/pokemon/goldeen/front.animated.2bpp.lz"
EspeonFrontpicAnim:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
XatuFrontpicAnim:        INCBIN "gfx/pokemon/xatu/front.animated.2bpp.lz"
MewFrontpicAnim:         INCBIN "gfx/pokemon/mew/front.animated.2bpp.lz"
OctilleryFrontpicAnim:   INCBIN "gfx/pokemon/octillery/front.animated.2bpp.lz"
JynxFrontpicAnim:        INCBIN "gfx/pokemon/jynx/front.animated.2bpp.lz"
WobbuffetFrontpicAnim:   INCBIN "gfx/pokemon/wobbuffet/front.animated.2bpp.lz"
DelibirdFrontpicAnim:    INCBIN "gfx/pokemon/delibird/front.animated.2bpp.lz"
LedianFrontpicAnim:      INCBIN "gfx/pokemon/ledian/front.animated.2bpp.lz"
GloomFrontpicAnim:       INCBIN "gfx/pokemon/gloom/front.animated.2bpp.lz"
FlaaffyFrontpicAnim:     INCBIN "gfx/pokemon/flaaffy/front.animated.2bpp.lz"
IvysaurFrontpicAnim:     INCBIN "gfx/pokemon/ivysaur/front.animated.2bpp.lz"
CyndaquilFrontpicAnim:   INCBIN "gfx/pokemon/cyndaquil/front.animated.2bpp.lz"
HitmonchanFrontpicAnim:  INCBIN "gfx/pokemon/hitmonchan/front.animated.2bpp.lz"
QuagsireFrontpicAnim:    INCBIN "gfx/pokemon/quagsire/front.animated.2bpp.lz"

SECTION "Pics 9 Animated", ROMX

EkansFrontpicAnim:       INCBIN "gfx/pokemon/ekans/front.animated.2bpp.lz"
SudowoodoFrontpicAnim:   INCBIN "gfx/pokemon/sudowoodo/front.animated.2bpp.lz"
PikachuFrontpicAnim:     INCBIN "gfx/pokemon/pikachu/front.animated.2bpp.lz"
SeadraFrontpicAnim:      INCBIN "gfx/pokemon/seadra/front.animated.2bpp.lz"
MagbyFrontpicAnim:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
WeepinbellFrontpicAnim:  INCBIN "gfx/pokemon/weepinbell/front.animated.2bpp.lz"
TotodileFrontpicAnim:    INCBIN "gfx/pokemon/totodile/front.animated.2bpp.lz"
CorsolaFrontpicAnim:     INCBIN "gfx/pokemon/corsola/front.animated.2bpp.lz"
MachopFrontpicAnim:      INCBIN "gfx/pokemon/machop/front.animated.2bpp.lz"
ChinchouFrontpicAnim:    INCBIN "gfx/pokemon/chinchou/front.animated.2bpp.lz"
RattataFrontpicAnim:     INCBIN "gfx/pokemon/rattata/front.animated.2bpp.lz"
SpearowFrontpicAnim:     INCBIN "gfx/pokemon/spearow/front.animated.2bpp.lz"
MagikarpFrontpicAnim:    INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
CharmanderFrontpicAnim:  INCBIN "gfx/pokemon/charmander/front.animated.2bpp.lz"
CuboneFrontpicAnim:      INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
NidoranMFrontpicAnim:    INCBIN "gfx/pokemon/nidoran_m/front.animated.2bpp.lz"
PorygonFrontpicAnim:     INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
GrimerFrontpicAnim:      INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
StaryuFrontpicAnim:      INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
MeowthFrontpicAnim:      INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
Porygon2FrontpicAnim:    INCBIN "gfx/pokemon/porygon2/front.animated.2bpp.lz"
SandshrewFrontpicAnim:   INCBIN "gfx/pokemon/sandshrew/front.animated.2bpp.lz"
NidoranFFrontpicAnim:    INCBIN "gfx/pokemon/nidoran_f/front.animated.2bpp.lz"
PidgeyFrontpicAnim:      INCBIN "gfx/pokemon/pidgey/front.animated.2bpp.lz"

SECTION "Pics 10 Animated", ROMX

MisdreavusFrontpicAnim:  INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
HoundourFrontpicAnim:    INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
MankeyFrontpicAnim:      INCBIN "gfx/pokemon/mankey/front.animated.2bpp.lz"
CelebiFrontpicAnim:      INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
PinecoFrontpicAnim:      INCBIN "gfx/pokemon/pineco/front.animated.2bpp.lz"
KrabbyFrontpicAnim:      INCBIN "gfx/pokemon/krabby/front.animated.2bpp.lz"
JigglypuffFrontpicAnim:  INCBIN "gfx/pokemon/jigglypuff/front.animated.2bpp.lz"
ParasFrontpicAnim:       INCBIN "gfx/pokemon/paras/front.animated.2bpp.lz"
PsyduckFrontpicAnim:     INCBIN "gfx/pokemon/psyduck/front.animated.2bpp.lz"
SquirtleFrontpicAnim:    INCBIN "gfx/pokemon/squirtle/front.animated.2bpp.lz"
KoffingFrontpicAnim:     INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
VenonatFrontpicAnim:     INCBIN "gfx/pokemon/venonat/front.animated.2bpp.lz"
LanturnFrontpicAnim:     INCBIN "gfx/pokemon/lanturn/front.animated.2bpp.lz"
TyrogueFrontpicAnim:     INCBIN "gfx/pokemon/tyrogue/front.animated.2bpp.lz"
MareepFrontpicAnim:      INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
EeveeFrontpicAnim:       INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
ZubatFrontpicAnim:       INCBIN "gfx/pokemon/zubat/front.animated.2bpp.lz"
AipomFrontpicAnim:       INCBIN "gfx/pokemon/aipom/front.animated.2bpp.lz"
AbraFrontpicAnim:        INCBIN "gfx/pokemon/abra/front.animated.2bpp.lz"
HoothootFrontpicAnim:    INCBIN "gfx/pokemon/hoothoot/front.animated.2bpp.lz"

SECTION "Pics 11 Animated", ROMX

ClefairyFrontpicAnim:    INCBIN "gfx/pokemon/clefairy/front.animated.2bpp.lz"
SlugmaFrontpicAnim:      INCBIN "gfx/pokemon/slugma/front.animated.2bpp.lz"
GrowlitheFrontpicAnim:   INCBIN "gfx/pokemon/growlithe/front.animated.2bpp.lz"
SlowpokeFrontpicAnim:    INCBIN "gfx/pokemon/slowpoke/front.animated.2bpp.lz"
SmoochumFrontpicAnim:    INCBIN "gfx/pokemon/smoochum/front.animated.2bpp.lz"
MarillFrontpicAnim:      INCBIN "gfx/pokemon/marill/front.animated.2bpp.lz"
OmanyteFrontpicAnim:     INCBIN "gfx/pokemon/omanyte/front.animated.2bpp.lz"
PupitarFrontpicAnim:     INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
BellsproutFrontpicAnim:  INCBIN "gfx/pokemon/bellsprout/front.animated.2bpp.lz"
ShellderFrontpicAnim:    INCBIN "gfx/pokemon/shellder/front.animated.2bpp.lz"
TentacoolFrontpicAnim:   INCBIN "gfx/pokemon/tentacool/front.animated.2bpp.lz"
CleffaFrontpicAnim:      INCBIN "gfx/pokemon/cleffa/front.animated.2bpp.lz"
DoduoFrontpicAnim:       INCBIN "gfx/pokemon/doduo/front.animated.2bpp.lz"
DratiniFrontpicAnim:     INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
QwilfishFrontpicAnim:    INCBIN "gfx/pokemon/qwilfish/front.animated.2bpp.lz"
ShuckleFrontpic: INCBIN "gfx/pokemon/shuckle/front.static.2bpp.lz"

SECTION "Pics 12 Animated", ROMX

LarvitarFrontpicAnim:    INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
OddishFrontpicAnim:      INCBIN "gfx/pokemon/oddish/front.animated.2bpp.lz"
TeddiursaFrontpicAnim:   INCBIN "gfx/pokemon/teddiursa/front.animated.2bpp.lz"
BulbasaurFrontpicAnim:   INCBIN "gfx/pokemon/bulbasaur/front.animated.2bpp.lz"

SECTION "Pics 13 Animated", ROMX

PichuFrontpicAnim:       INCBIN "gfx/pokemon/pichu/front.animated.2bpp.lz"
UnownDFrontpicAnim:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
RemoraidFrontpicAnim:    INCBIN "gfx/pokemon/remoraid/front.animated.2bpp.lz"
PoliwagFrontpicAnim:     INCBIN "gfx/pokemon/poliwag/front.animated.2bpp.lz"
SunkernFrontpicAnim:     INCBIN "gfx/pokemon/sunkern/front.animated.2bpp.lz"
ElectrodeFrontpicAnim:   INCBIN "gfx/pokemon/electrode/front.animated.2bpp.lz"
EggPicAnim:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"

SECTION "Pics 14 Animated", ROMX

SentretFrontpicAnim:     INCBIN "gfx/pokemon/sentret/front.animated.2bpp.lz"
GeodudeFrontpicAnim:     INCBIN "gfx/pokemon/geodude/front.animated.2bpp.lz"

SECTION "Pics 15 Animated", ROMX

DiglettFrontpicAnim:     INCBIN "gfx/pokemon/diglett/front.animated.2bpp.lz"
HorseaFrontpicAnim:      INCBIN "gfx/pokemon/horsea/front.animated.2bpp.lz"
KakunaFrontpicAnim:      INCBIN "gfx/pokemon/kakuna/front.animated.2bpp.lz"
WeedleFrontpicAnim:      INCBIN "gfx/pokemon/weedle/front.animated.2bpp.lz"
MagnemiteFrontpicAnim:   INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"

SECTION "Pics 16 Animated", ROMX

TogepiFrontpicAnim:      INCBIN "gfx/pokemon/togepi/front.animated.2bpp.lz"
MetapodFrontpicAnim:     INCBIN "gfx/pokemon/metapod/front.animated.2bpp.lz"
CaterpieFrontpicAnim:    INCBIN "gfx/pokemon/caterpie/front.animated.2bpp.lz"
SpinarakFrontpicAnim:    INCBIN "gfx/pokemon/spinarak/front.animated.2bpp.lz"
UnownWFrontpicAnim:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
UnownCFrontpicAnim:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
UnownZFrontpicAnim:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
SwinubFrontpicAnim:      INCBIN "gfx/pokemon/swinub/front.animated.2bpp.lz"

SECTION "Pics 17 Animated", ROMX

VoltorbFrontpicAnim:     INCBIN "gfx/pokemon/voltorb/front.animated.2bpp.lz"
UnownGFrontpicAnim:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
NatuFrontpicAnim:        INCBIN "gfx/pokemon/natu/front.animated.2bpp.lz"
UnownVFrontpicAnim:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
UnownSFrontpicAnim:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
UnownOFrontpicAnim:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpicAnim:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
UnownHFrontpicAnim:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"

SECTION "Pics 18 Animated", ROMX

UnownKFrontpicAnim:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
UnownBFrontpicAnim:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
UnownXFrontpicAnim:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpicAnim:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
UnownJFrontpicAnim:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
UnownLFrontpicAnim:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
UnownMFrontpicAnim:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpicAnim:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
UnownAFrontpicAnim:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
UnownUFrontpicAnim:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
UnownQFrontpicAnim:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpicAnim:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownYFrontpicAnim:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownIFrontpicAnim:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownRFrontpicAnim:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"

SECTION "Pics 19 Animated", ROMX

FurretFrontpicAnim: INCBIN "gfx/pokemon/furret/front.animated.2bpp.lz"
CoinpurFrontpicAnim: INCBIN "gfx/pokemon/coinpur/front.animated.2bpp.lz"
WooperFrontpicAnim: INCBIN "gfx/pokemon/wooper/front.animated.2bpp.lz"
KatuFrontpicAnim:   INCBIN "gfx/pokemon/katu/front.animated.2bpp.lz"
AdbarstorkFrontpicAnim: INCBIN "gfx/pokemon/adbarstork/front.animated.2bpp.lz"
PupperonFrontpicAnim: INCBIN "gfx/pokemon/pupperon/front.animated.2bpp.lz"
BipullaFrontpicAnim: INCBIN "gfx/pokemon/bipulla/front.animated.2bpp.lz"
MoibelleFrontpicAnim: INCBIN "gfx/pokemon/moibelle/front.animated.2bpp.lz"
BelledamFrontpicAnim: INCBIN "gfx/pokemon/belledam/front.animated.2bpp.lz"
CleflingFrontpicAnim: INCBIN "gfx/pokemon/clefling/front.animated.2bpp.lz"
PetamoleFrontpicAnim: INCBIN "gfx/pokemon/petamole/front.animated.2bpp.lz"
HitmontopFrontpicAnim: INCBIN "gfx/pokemon/hitmontop/front.animated.2bpp.lz"
ShuckleFrontpicAnim: INCBIN "gfx/pokemon/shuckle/front.animated.2bpp.lz"

SECTION "Pics 20 Animated", ROMX

BellignanFrontpicAnim: INCBIN "gfx/pokemon/bellignan/front.animated.2bpp.lz"
LuxswanFrontpicAnim: INCBIN "gfx/pokemon/luxswan/front.animated.2bpp.lz"
PhanpyFrontpicAnim: INCBIN "gfx/pokemon/phanpy/front.animated.2bpp.lz"
HoppipFrontpicAnim: INCBIN "gfx/pokemon/hoppip/front.animated.2bpp.lz"
TonbossFrontpicAnim: INCBIN "gfx/pokemon/tonboss/front.animated.2bpp.lz"
MallodyFrontpicAnim: INCBIN "gfx/pokemon/mallody/front.animated.2bpp.lz"
CamouflakeFrontpicAnim: INCBIN "gfx/pokemon/camouflake/front.animated.2bpp.lz"

SECTION "Pics 21 Animated", ROMX

CoaltaFrontpicAnim: INCBIN "gfx/pokemon/coalta/front.animated.2bpp.lz"
BurgelaFrontpicAnim: INCBIN "gfx/pokemon/burgela/front.animated.2bpp.lz"
VulpiiiFrontpicAnim: INCBIN "gfx/pokemon/vulpiii/front.animated.2bpp.lz"
WorfursFrontpicAnim: INCBIN "gfx/pokemon/worfurs/front.animated.2bpp.lz"
DodaerieFrontpicAnim: INCBIN "gfx/pokemon/dodaerie/front.animated.2bpp.lz"
FarfetchDFrontpicAnim:   INCBIN "gfx/pokemon/farfetch_d/front.animated.2bpp.lz"
SkiploomFrontpicAnim:    INCBIN "gfx/pokemon/skiploom/front.animated.2bpp.lz"
TopsyspotFrontpicAnim: INCBIN "gfx/pokemon/topsyspot/front.animated.2bpp.lz"
KabutoFrontpicAnim:      INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
TriculesFrontpicAnim: INCBIN "gfx/pokemon/tricules/front.animated.2bpp.lz"
ChomoswineFrontpicAnim: INCBIN "gfx/pokemon/chomoswine/front.animated.2bpp.lz"
ShuqlourFrontpicAnim: INCBIN "gfx/pokemon/shuqlour/front.animated.2bpp.lz"
ParasporFrontpicAnim: INCBIN "gfx/pokemon/paraspor/front.animated.2bpp.lz"
WearlycanFrontpicAnim: INCBIN "gfx/pokemon/wearlycan/front.animated.2bpp.lz"
MolambinoFrontpicAnim: INCBIN "gfx/pokemon/molambino/front.animated.2bpp.lz"

SECTION "Pics 22 Animated", ROMX

IgglybuffFrontpicAnim:   INCBIN "gfx/pokemon/igglybuff/front.animated.2bpp.lz"
DittoFrontpicAnim:       INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
KiwackiFrontpicAnim: INCBIN "gfx/pokemon/kiwacki/front.animated.2bpp.lz"
SilkaneFrontpicAnim: INCBIN "gfx/pokemon/silkane/front.animated.2bpp.lz"
MorphobiaFrontpicAnim: INCBIN "gfx/pokemon/morphobia/front.animated.2bpp.lz"
TerrachnidFrontpicAnim: INCBIN "gfx/pokemon/terrachnid/front.animated.2bpp.lz"
SmujjFrontpicAnim:	INCBIN "gfx/pokemon/smujj/front.animated.2bpp.lz"
KotoraFrontpicAnim:	INCBIN "gfx/pokemon/kotora/front.animated.2bpp.lz"
RaitoraFrontpicAnim:	INCBIN "gfx/pokemon/raitora/front.animated.2bpp.lz"
GorotoraFrontpicAnim:	INCBIN "gfx/pokemon/gorotora/front.animated.2bpp.lz"
KoalyptusFrontpicAnim:	INCBIN "gfx/pokemon/koalyptus/front.animated.2bpp.lz"

SECTION "Pics 23 Animated", ROMX

BallerineFrontpicAnim:	INCBIN "gfx/pokemon/ballerine/front.animated.2bpp.lz"
OrefryFrontpicAnim:	INCBIN "gfx/pokemon/orefry/front.animated.2bpp.lz"
FennecurseFrontpicAnim:	INCBIN "gfx/pokemon/fennecurse/front.animated.2bpp.lz"
OrijoeyFrontpicAnim:	INCBIN "gfx/pokemon/orijoey/front.animated.2bpp.lz"
AggroswineFrontpicAnim:	INCBIN "gfx/pokemon/aggroswine/front.animated.2bpp.lz"

SECTION "Pics 24 Animated", ROMX

GermifrostFrontpicAnim:	INCBIN "gfx/pokemon/germifrost/front.animated.2bpp.lz"
VegelancheFrontpicAnim:	INCBIN "gfx/pokemon/vegelanche/front.animated.2bpp.lz"
SnouwrbunFrontpicAnim:	INCBIN "gfx/pokemon/snouwrbun/front.animated.2bpp.lz"
NecrorexFrontpicAnim:	INCBIN "gfx/pokemon/necrorex/front.animated.2bpp.lz"
