SECTION "_ChrisSpriteGFX", ROMX
ChrisSpriteGFX::               INCBIN "gfx/sprites/chris.2bpp"
SECTION "_ChrisBikeSpriteGFX", ROMX
ChrisBikeSpriteGFX::           INCBIN "gfx/sprites/chris_bike.2bpp"
SECTION "_GameboyKidSpriteGFX", ROMX
GameboyKidSpriteGFX::          INCBIN "gfx/sprites/gameboy_kid.2bpp"
SECTION "_SilverSpriteGFX", ROMX
SilverSpriteGFX::              INCBIN "gfx/sprites/silver.2bpp"
SECTION "_OakSpriteGFX", ROMX
OakSpriteGFX::                 INCBIN "gfx/sprites/oak.2bpp"
SECTION "_RedSpriteGFX", ROMX
RedSpriteGFX::                 INCBIN "gfx/sprites/red.2bpp"
SECTION "_BlueSpriteGFX", ROMX
BlueSpriteGFX::                INCBIN "gfx/sprites/blue.2bpp"
SECTION "_BillSpriteGFX", ROMX
BillSpriteGFX::                INCBIN "gfx/sprites/bill.2bpp"
SECTION "_ElderSpriteGFX", ROMX
ElderSpriteGFX::               INCBIN "gfx/sprites/elder.2bpp"
SECTION "_JanineSpriteGFX", ROMX
JanineSpriteGFX::              INCBIN "gfx/sprites/janine.2bpp"
SECTION "_KurtSpriteGFX", ROMX
KurtSpriteGFX::                INCBIN "gfx/sprites/kurt.2bpp"
SECTION "_MomSpriteGFX", ROMX
MomSpriteGFX::                 INCBIN "gfx/sprites/mom.2bpp"
SECTION "_BlaineSpriteGFX", ROMX
BlaineSpriteGFX::              INCBIN "gfx/sprites/blaine.2bpp"
SECTION "_RedsMomSpriteGFX", ROMX
RedsMomSpriteGFX::             INCBIN "gfx/sprites/reds_mom.2bpp"
SECTION "_DaisySpriteGFX", ROMX
DaisySpriteGFX::               INCBIN "gfx/sprites/daisy.2bpp"
SECTION "_ElmSpriteGFX", ROMX
ElmSpriteGFX::                 INCBIN "gfx/sprites/elm.2bpp"
SECTION "_WillSpriteGFX", ROMX
WillSpriteGFX::                INCBIN "gfx/sprites/will.2bpp"
SECTION "_FalknerSpriteGFX", ROMX
FalknerSpriteGFX::             INCBIN "gfx/sprites/falkner.2bpp"
SECTION "_WhitneySpriteGFX", ROMX
WhitneySpriteGFX::             INCBIN "gfx/sprites/whitney.2bpp"
SECTION "_BugsySpriteGFX", ROMX
BugsySpriteGFX::               INCBIN "gfx/sprites/bugsy.2bpp"
SECTION "_MortySpriteGFX", ROMX
MortySpriteGFX::               INCBIN "gfx/sprites/morty.2bpp"
SECTION "_ChuckSpriteGFX", ROMX
ChuckSpriteGFX::               INCBIN "gfx/sprites/chuck.2bpp"
SECTION "_JasmineSpriteGFX", ROMX
JasmineSpriteGFX::             INCBIN "gfx/sprites/jasmine.2bpp"
SECTION "_PryceSpriteGFX", ROMX
PryceSpriteGFX::               INCBIN "gfx/sprites/pryce.2bpp"
SECTION "_ClairSpriteGFX", ROMX
ClairSpriteGFX::               INCBIN "gfx/sprites/clair.2bpp"
SECTION "_BrockSpriteGFX", ROMX
BrockSpriteGFX::               INCBIN "gfx/sprites/brock.2bpp"
SECTION "_BrunoSpriteGFX", ROMX
BrunoSpriteGFX::               INCBIN "gfx/sprites/bruno.2bpp"
SECTION "_MistySpriteGFX", ROMX
MistySpriteGFX::               INCBIN "gfx/sprites/misty.2bpp"
SECTION "_LanceSpriteGFX", ROMX
LanceSpriteGFX::               INCBIN "gfx/sprites/lance.2bpp"
SECTION "_SurgeSpriteGFX", ROMX
SurgeSpriteGFX::               INCBIN "gfx/sprites/surge.2bpp"
SECTION "_ErikaSpriteGFX", ROMX
ErikaSpriteGFX::               INCBIN "gfx/sprites/erika.2bpp"
SECTION "_KogaSpriteGFX", ROMX
KogaSpriteGFX::                INCBIN "gfx/sprites/koga.2bpp"
SECTION "_SabrinaSpriteGFX", ROMX
SabrinaSpriteGFX::             INCBIN "gfx/sprites/sabrina.2bpp"
SECTION "_CooltrainerMSpriteGFX", ROMX
CooltrainerMSpriteGFX::        INCBIN "gfx/sprites/cooltrainer_m.2bpp"
SECTION "_CooltrainerFSpriteGFX", ROMX
CooltrainerFSpriteGFX::        INCBIN "gfx/sprites/cooltrainer_f.2bpp"
SECTION "_BugCatcherSpriteGFX", ROMX
BugCatcherSpriteGFX::          INCBIN "gfx/sprites/bug_catcher.2bpp"
SECTION "_TwinSpriteGFX", ROMX
TwinSpriteGFX::                INCBIN "gfx/sprites/twin.2bpp"
SECTION "_YoungsterSpriteGFX", ROMX
YoungsterSpriteGFX::           INCBIN "gfx/sprites/youngster.2bpp"
SECTION "_LassSpriteGFX", ROMX
LassSpriteGFX::                INCBIN "gfx/sprites/lass.2bpp"
SECTION "_TeacherSpriteGFX", ROMX
TeacherSpriteGFX::             INCBIN "gfx/sprites/teacher.2bpp"
SECTION "_BuenaSpriteGFX", ROMX
BuenaSpriteGFX::               INCBIN "gfx/sprites/buena.2bpp"
SECTION "_SuperNerdSpriteGFX", ROMX
SuperNerdSpriteGFX::           INCBIN "gfx/sprites/super_nerd.2bpp"
SECTION "_RockerSpriteGFX", ROMX
RockerSpriteGFX::              INCBIN "gfx/sprites/rocker.2bpp"

SECTION "_PokefanMSpriteGFX", ROMX
PokefanMSpriteGFX::            INCBIN "gfx/sprites/pokefan_m.2bpp"
SECTION "_PokefanFSpriteGFX", ROMX
PokefanFSpriteGFX::            INCBIN "gfx/sprites/pokefan_f.2bpp"
SECTION "_GrampsSpriteGFX", ROMX
GrampsSpriteGFX::              INCBIN "gfx/sprites/gramps.2bpp"
SECTION "_GrannySpriteGFX", ROMX
GrannySpriteGFX::              INCBIN "gfx/sprites/granny.2bpp"
SECTION "_SwimmerGuySpriteGFX", ROMX
SwimmerGuySpriteGFX::          INCBIN "gfx/sprites/swimmer_guy.2bpp"
SECTION "_SwimmerGirlSpriteGFX", ROMX
SwimmerGirlSpriteGFX::         INCBIN "gfx/sprites/swimmer_girl.2bpp"
SECTION "_BigSnorlaxSpriteGFX", ROMX
BigSnorlaxSpriteGFX::          INCBIN "gfx/sprites/big_snorlax.2bpp"
SECTION "_SurfingPikachuSpriteGFX", ROMX
SurfingPikachuSpriteGFX::      INCBIN "gfx/sprites/surfing_pikachu.2bpp"
SECTION "_RocketSpriteGFX", ROMX
RocketSpriteGFX::              INCBIN "gfx/sprites/rocket.2bpp"
SECTION "_RocketGirlSpriteGFX", ROMX
RocketGirlSpriteGFX::          INCBIN "gfx/sprites/rocket_girl.2bpp"
SECTION "_NurseSpriteGFX", ROMX
NurseSpriteGFX::               INCBIN "gfx/sprites/nurse.2bpp"
SECTION "_LinkReceptionistSpriteGFX", ROMX
LinkReceptionistSpriteGFX::    INCBIN "gfx/sprites/link_receptionist.2bpp"
SECTION "_ClerkSpriteGFX", ROMX
ClerkSpriteGFX::               INCBIN "gfx/sprites/clerk.2bpp"
SECTION "_FisherSpriteGFX", ROMX
FisherSpriteGFX::              INCBIN "gfx/sprites/fisher.2bpp"
SECTION "_FishingGuruSpriteGFX", ROMX
FishingGuruSpriteGFX::         INCBIN "gfx/sprites/fishing_guru.2bpp"
SECTION "_ScientistSpriteGFX", ROMX
ScientistSpriteGFX::           INCBIN "gfx/sprites/scientist.2bpp"
SECTION "_KimonoGirlSpriteGFX", ROMX
KimonoGirlSpriteGFX::          INCBIN "gfx/sprites/kimono_girl.2bpp"
SECTION "_SageSpriteGFX", ROMX
SageSpriteGFX::                INCBIN "gfx/sprites/sage.2bpp"
SECTION "_UnusedGuySpriteGFX", ROMX
UnusedGuySpriteGFX::           INCBIN "gfx/sprites/unused_guy.2bpp"
SECTION "_GentlemanSpriteGFX", ROMX
GentlemanSpriteGFX::           INCBIN "gfx/sprites/gentleman.2bpp"
SECTION "_BlackBeltSpriteGFX", ROMX
BlackBeltSpriteGFX::           INCBIN "gfx/sprites/black_belt.2bpp"
SECTION "_ReceptionistSpriteGFX", ROMX
ReceptionistSpriteGFX::        INCBIN "gfx/sprites/receptionist.2bpp"
SECTION "_OfficerSpriteGFX", ROMX
OfficerSpriteGFX::             INCBIN "gfx/sprites/officer.2bpp"
SECTION "_CalSpriteGFX", ROMX
CalSpriteGFX::                 INCBIN "gfx/sprites/cal.2bpp"
SECTION "_SlowpokeSpriteGFX", ROMX
SlowpokeSpriteGFX::            INCBIN "gfx/sprites/slowpoke.2bpp"
SECTION "_CaptainSpriteGFX", ROMX
CaptainSpriteGFX::             INCBIN "gfx/sprites/captain.2bpp"
SECTION "_BigLaprasSpriteGFX", ROMX
BigLaprasSpriteGFX::           INCBIN "gfx/sprites/big_lapras.2bpp"
SECTION "_GymGuySpriteGFX", ROMX
GymGuySpriteGFX::              INCBIN "gfx/sprites/gym_guy.2bpp"
SECTION "_SailorSpriteGFX", ROMX
SailorSpriteGFX::              INCBIN "gfx/sprites/sailor.2bpp"
SECTION "_BikerSpriteGFX", ROMX
BikerSpriteGFX::               INCBIN "gfx/sprites/biker.2bpp"
SECTION "_PharmacistSpriteGFX", ROMX
PharmacistSpriteGFX::          INCBIN "gfx/sprites/pharmacist.2bpp"
SECTION "_MonsterSpriteGFX", ROMX
MonsterSpriteGFX::             INCBIN "gfx/sprites/monster.2bpp"
SECTION "_FairySpriteGFX", ROMX
FairySpriteGFX::               INCBIN "gfx/sprites/fairy.2bpp"
SECTION "_BirdSpriteGFX", ROMX
BirdSpriteGFX::                INCBIN "gfx/sprites/bird.2bpp"
SECTION "_DragonSpriteGFX", ROMX
DragonSpriteGFX::              INCBIN "gfx/sprites/dragon.2bpp"
SECTION "_BigOnixSpriteGFX", ROMX
BigOnixSpriteGFX::             INCBIN "gfx/sprites/big_onix.2bpp"
SECTION "_N64SpriteGFX", ROMX
N64SpriteGFX::                 INCBIN "gfx/sprites/n64.2bpp"
SECTION "_SudowoodoSpriteGFX", ROMX
SudowoodoSpriteGFX::           INCBIN "gfx/sprites/sudowoodo.2bpp"
SECTION "_SurfSpriteGFX", ROMX
SurfSpriteGFX::                INCBIN "gfx/sprites/surf.2bpp"
SECTION "_PokeBallSpriteGFX", ROMX
PokeBallSpriteGFX::            INCBIN "gfx/sprites/poke_ball.2bpp"
SECTION "_PokedexSpriteGFX", ROMX
PokedexSpriteGFX::             INCBIN "gfx/sprites/pokedex.2bpp"
SECTION "_PaperSpriteGFX", ROMX
PaperSpriteGFX::               INCBIN "gfx/sprites/paper.2bpp"
SECTION "_VirtualBoySpriteGFX", ROMX
VirtualBoySpriteGFX::          INCBIN "gfx/sprites/virtual_boy.2bpp"
SECTION "_OldLinkReceptionistSpriteGFX", ROMX
OldLinkReceptionistSpriteGFX:: INCBIN "gfx/sprites/old_link_receptionist.2bpp"
SECTION "_RockSpriteGFX", ROMX
RockSpriteGFX::                INCBIN "gfx/sprites/rock.2bpp"
SECTION "_BoulderSpriteGFX", ROMX
BoulderSpriteGFX::             INCBIN "gfx/sprites/boulder.2bpp"
SECTION "_SnesSpriteGFX", ROMX
SnesSpriteGFX::                INCBIN "gfx/sprites/snes.2bpp"
SECTION "_FamicomSpriteGFX", ROMX
FamicomSpriteGFX::             INCBIN "gfx/sprites/famicom.2bpp"
SECTION "_FruitTreeSpriteGFX", ROMX
FruitTreeSpriteGFX::           INCBIN "gfx/sprites/fruit_tree.2bpp"
SECTION "_GoldTrophySpriteGFX", ROMX
GoldTrophySpriteGFX::          INCBIN "gfx/sprites/gold_trophy.2bpp"
SECTION "_SilverTrophySpriteGFX", ROMX
SilverTrophySpriteGFX::        INCBIN "gfx/sprites/silver_trophy.2bpp"
SECTION "_KrisSpriteGFX", ROMX
KrisSpriteGFX::                INCBIN "gfx/sprites/kris.2bpp"
SECTION "_KrisBikeSpriteGFX", ROMX
KrisBikeSpriteGFX::            INCBIN "gfx/sprites/kris_bike.2bpp"
SECTION "_SuicuneSpriteGFX", ROMX
SuicuneSpriteGFX::             INCBIN "gfx/sprites/suicune.2bpp"
SECTION "_EnteiSpriteGFX", ROMX
EnteiSpriteGFX::               INCBIN "gfx/sprites/entei.2bpp"
SECTION "_RaikouSpriteGFX", ROMX
RaikouSpriteGFX::              INCBIN "gfx/sprites/raikou.2bpp"

SECTION "_FledglingSpriteGFX", ROMX
FledglingSpriteGFX::           INCBIN "gfx/sprites/fledgling.2bpp"
SECTION "_BirdKeeperSpriteGFX", ROMX
BirdKeeperSpriteGFX::          INCBIN "gfx/sprites/bird_keeper.2bpp"
SECTION "_SoldierSpriteGFX", ROMX
SoldierSpriteGFX::             INCBIN "gfx/sprites/soldier.2bpp"
SECTION "_FatGuySpriteGFX", ROMX
FatGuySpriteGFX::              INCBIN "gfx/sprites/fat_guy.2bpp"
SECTION "_SportsmanSpriteGFX", ROMX
SportsmanSpriteGFX::           INCBIN "gfx/sprites/sportsman.2bpp"
SECTION "_CamperSpriteGFX", ROMX
CamperSpriteGFX::              INCBIN "gfx/sprites/camper.2bpp"
SECTION "_HikerSpriteGFX", ROMX
HikerSpriteGFX::               INCBIN "gfx/sprites/hiker.2bpp"
SECTION "_GameboyGirlSpriteGFX", ROMX
GameboyGirlSpriteGFX::         INCBIN "gfx/sprites/gameboy_girl.2bpp"
SECTION "_MysticSpriteGFX", ROMX
MysticSpriteGFX::              INCBIN "gfx/sprites/mystic.2bpp"
SECTION "_KarenSpriteGFX", ROMX
KarenSpriteGFX::               INCBIN "gfx/sprites/karen.2bpp"
SECTION "_ManchildSpriteGFX", ROMX
ManchildSpriteGFX::            INCBIN "gfx/sprites/manchild.2bpp"
SECTION "_SchoolboySpriteGFX", ROMX
SchoolboySpriteGFX::           INCBIN "gfx/sprites/schoolboy.2bpp"
SECTION "_RockClimberSpriteGFX", ROMX
RockClimberSpriteGFX::         INCBIN "gfx/sprites/rock_climber.2bpp"
SECTION "_NieNieSpriteGFX", ROMX
NieNieSpriteGFX::              INCBIN "gfx/sprites/niechelle.2bpp"
SECTION "_LadySpriteGFX", ROMX
LadySpriteGFX::                INCBIN "gfx/sprites/lady.2bpp"
SECTION "_FirebreatherSpriteGFX", ROMX
FirebreatherSpriteGFX::        INCBIN "gfx/sprites/firebreather.2bpp"
SECTION "_JugglerSpriteGFX", ROMX
JugglerSpriteGFX::             INCBIN "gfx/sprites/juggler.2bpp"
SECTION "_ProdigySpriteGFX", ROMX
ProdigySpriteGFX::             INCBIN "gfx/sprites/prodigy.2bpp"
SECTION "_EngineerSpriteGFX", ROMX
EngineerSpriteGFX::             INCBIN "gfx/sprites/engineer.2bpp"

SECTION "_EeveeSpriteGFX", ROMX
EeveeSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/eevee.2bpp"
SECTION "_FarfetchdSpriteGFX", ROMX
FarfetchdSpriteGFX::		   INCBIN "gfx/sprites/pokemon/farfetch_d.2bpp"
SECTION "_ClefairySpriteGFX", ROMX
ClefairySpriteGFX::		       INCBIN "gfx/sprites/pokemon/clefairy.2bpp"
SECTION "_PikachuSpriteGFX", ROMX
PikachuSpriteGFX::             INCBIN "gfx/sprites/pokemon/pikachu.2bpp"
SECTION "_CharizardSpriteGFX", ROMX
CharizardSpriteGFX::           INCBIN "gfx/sprites/pokemon/charizard.2bpp"
SECTION "_BulbasaurSpriteGFX", ROMX
BulbasaurSpriteGFX::           INCBIN "gfx/sprites/pokemon/bulbasaur.2bpp"
SECTION "_IvysaurSpriteGFX", ROMX
IvysaurSpriteGFX::             INCBIN "gfx/sprites/pokemon/ivysaur.2bpp"
SECTION "_VenusaurSpriteGFX", ROMX
VenusaurSpriteGFX::            INCBIN "gfx/sprites/pokemon/venusaur.2bpp"
SECTION "_CharmanderSpriteGFX", ROMX
CharmanderSpriteGFX::          INCBIN "gfx/sprites/pokemon/charmander.2bpp"
SECTION "_CharmeleonSpriteGFX", ROMX
CharmeleonSpriteGFX::          INCBIN "gfx/sprites/pokemon/charmeleon.2bpp"
SECTION "_MeowthSpriteGFX", ROMX
MeowthSpriteGFX::              INCBIN "gfx/sprites/pokemon/meowth.2bpp"
SECTION "_RaichuSpriteGFX", ROMX
RaichuSpriteGFX::              INCBIN "gfx/sprites/pokemon/raichu.2bpp"
SECTION "_PersianSpriteGFX", ROMX
PersianSpriteGFX::             INCBIN "gfx/sprites/pokemon/persian.2bpp"
SECTION "_SquirtleSpriteGFX", ROMX
SquirtleSpriteGFX::            INCBIN "gfx/sprites/pokemon/squirtle.2bpp"
SECTION "_WartortleSpriteGFX", ROMX
WartortleSpriteGFX::           INCBIN "gfx/sprites/pokemon/wartortle.2bpp"
SECTION "_BlastoiseSpriteGFX", ROMX
BlastoiseSpriteGFX::           INCBIN "gfx/sprites/pokemon/blastoise.2bpp"
SECTION "_CaterpieSpriteGFX", ROMX
CaterpieSpriteGFX::            INCBIN "gfx/sprites/pokemon/caterpie.2bpp"
SECTION "_MetapodSpriteGFX", ROMX
MetapodSpriteGFX::             INCBIN "gfx/sprites/pokemon/metapod.2bpp"
SECTION "_ButterfreeSpriteGFX", ROMX
ButterfreeSpriteGFX::          INCBIN "gfx/sprites/pokemon/butterfree.2bpp"
SECTION "_WeedleSpriteGFX", ROMX
WeedleSpriteGFX::              INCBIN "gfx/sprites/pokemon/weedle.2bpp"
SECTION "_KakunaSpriteGFX", ROMX
KakunaSpriteGFX::              INCBIN "gfx/sprites/pokemon/kakuna.2bpp"
SECTION "_BeedrillSpriteGFX", ROMX
BeedrillSpriteGFX::            INCBIN "gfx/sprites/pokemon/beedrill.2bpp"
SECTION "_PidgeySpriteGFX", ROMX
PidgeySpriteGFX::              INCBIN "gfx/sprites/pokemon/pidgey.2bpp"
SECTION "_PidgeottoSpriteGFX", ROMX
PidgeottoSpriteGFX::           INCBIN "gfx/sprites/pokemon/pidgeotto.2bpp"
SECTION "_PidgeotSpriteGFX", ROMX
PidgeotSpriteGFX::             INCBIN "gfx/sprites/pokemon/pidgeot.2bpp"
SECTION "_RattataSpriteGFX", ROMX
RattataSpriteGFX::             INCBIN "gfx/sprites/pokemon/rattata.2bpp"
SECTION "_RaticateSpriteGFX", ROMX
RaticateSpriteGFX::            INCBIN "gfx/sprites/pokemon/raticate.2bpp"
SECTION "_SpearowSpriteGFX", ROMX
SpearowSpriteGFX::             INCBIN "gfx/sprites/pokemon/spearow.2bpp"
SECTION "_FearowSpriteGFX", ROMX
FearowSpriteGFX::              INCBIN "gfx/sprites/pokemon/fearow.2bpp"
SECTION "_EkansSpriteGFX", ROMX
EkansSpriteGFX::               INCBIN "gfx/sprites/pokemon/ekans.2bpp"
SECTION "_ArbokSpriteGFX", ROMX
ArbokSpriteGFX::               INCBIN "gfx/sprites/pokemon/arbok.2bpp"
SECTION "_ClefableSpriteGFX", ROMX
ClefableSpriteGFX::            INCBIN "gfx/sprites/pokemon/clefable.2bpp"
SECTION "_SandshrewSpriteGFX", ROMX
SandshrewSpriteGFX::           INCBIN "gfx/sprites/pokemon/sandshrew.2bpp"
SECTION "_SandslashSpriteGFX", ROMX
SandslashSpriteGFX::           INCBIN "gfx/sprites/pokemon/sandslash.2bpp"
SECTION "_NidoranFSpriteGFX", ROMX
NidoranFSpriteGFX::            INCBIN "gfx/sprites/pokemon/nidoran_f.2bpp"
SECTION "_NidorinaSpriteGFX", ROMX
NidorinaSpriteGFX::            INCBIN "gfx/sprites/pokemon/nidorina.2bpp"
SECTION "_NidoqueenSpriteGFX", ROMX
NidoqueenSpriteGFX::          INCBIN "gfx/sprites/pokemon/nidoqueen.2bpp"
SECTION "_NidoranMSpriteGFX", ROMX
NidoranMSpriteGFX::          INCBIN "gfx/sprites/pokemon/nidoran_m.2bpp"
SECTION "_NidorinoSpriteGFX", ROMX
NidorinoSpriteGFX::          INCBIN "gfx/sprites/pokemon/nidorino.2bpp"
SECTION "_NidokingSpriteGFX", ROMX
NidokingSpriteGFX::          INCBIN "gfx/sprites/pokemon/nidoking.2bpp"
SECTION "_GrimerSpriteGFX", ROMX
GrimerSpriteGFX::            INCBIN "gfx/sprites/pokemon/grimer.2bpp"

SECTION "_MukSpriteGFX", ROMX
MukSpriteGFX::               INCBIN "gfx/sprites/pokemon/muk.2bpp"
SECTION "_PonytaSpriteGFX", ROMX
PonytaSpriteGFX::            INCBIN "gfx/sprites/pokemon/ponyta.2bpp"
SECTION "_RapidashSpriteGFX", ROMX
RapidashSpriteGFX::          INCBIN "gfx/sprites/pokemon/rapidash.2bpp"
SECTION "_TangelaSpriteGFX", ROMX
TangelaSpriteGFX::           INCBIN "gfx/sprites/pokemon/tangela.2bpp"
SECTION "_VulpixSpriteGFX", ROMX
VulpixSpriteGFX::            INCBIN "gfx/sprites/pokemon/vulpix.2bpp"
SECTION "_NinetalesSpriteGFX", ROMX
NinetalesSpriteGFX::         INCBIN "gfx/sprites/pokemon/ninetales.2bpp"
SECTION "_WooperSpriteGFX", ROMX
WooperSpriteGFX::         	   INCBIN "gfx/sprites/pokemon/wooper.2bpp"
SECTION "_CelebiSpriteGFX", ROMX
CelebiSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/celebi.2bpp"
SECTION "_YanmaSpriteGFX", ROMX
YanmaSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/yanma.2bpp"
SECTION "_YanmegaSpriteGFX", ROMX
YanmegaSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/yanmega.2bpp"
SECTION "_ChikoritaSpriteGFX", ROMX
ChikoritaSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/chikorita.2bpp"
SECTION "_BlossomoleSpriteGFX", ROMX
BlossomoleSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/blossomole.2bpp"
SECTION "_BayleefSpriteGFX", ROMX
BayleefSpriteGFX:: 		       INCBIN "gfx/sprites/pokemon/bayleef.2bpp"
SECTION "_MeganiumSpriteGFX", ROMX
MeganiumSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/meganium.2bpp"
SECTION "_CyndaquilSpriteGFX", ROMX
CyndaquilSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/cyndaquil.2bpp"
SECTION "_QuilavaSpriteGFX", ROMX
QuilavaSpriteGFX:: 		  	   INCBIN "gfx/sprites/pokemon/quilava.2bpp"
SECTION "_TyphlosionSpriteGFX", ROMX
TyphlosionSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/typhlosion.2bpp"
SECTION "_TotodileSpriteGFX", ROMX
TotodileSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/totodile.2bpp"
SECTION "_CroconawSpriteGFX", ROMX
CroconawSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/croconaw.2bpp"
SECTION "_FeraligatrSpriteGFX", ROMX
FeraligatrSpriteGFX:: 		   INCBIN "gfx/sprites/pokemon/feraligator.2bpp"
SECTION "_KotoraSpriteGFX", ROMX
KotoraSpriteGFX::			   INCBIN "gfx/sprites/pokemon/kotora.2bpp"
SECTION "_CleflingSpriteGFX", ROMX
CleflingSpriteGFX::			   INCBIN "gfx/sprites/pokemon/clefling.2bpp"
SECTION "_ShuckleSpriteGFX", ROMX
ShuckleSpriteGFX::			   INCBIN "gfx/sprites/pokemon/shuckle.2bpp"
SECTION "_CoinpurSpriteGFX", ROMX
CoinpurSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/coinpur.2bpp"
SECTION "_GermifrostSpriteGFX", ROMX
GermifrostSpriteGFX::          INCBIN "gfx/sprites/pokemon/germifrost.2bpp"
SECTION "_SmujjSpriteGFX", ROMX
SmujjSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/smujj.2bpp"
SECTION "_VulpiiiSpriteGFX", ROMX
VulpiiiSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/vulpiii.2bpp"
SECTION "_BurgelaSpriteGFX", ROMX
BurgelaSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/burgela.2bpp"
SECTION "_CoaltaSpriteGFX", ROMX
CoaltaSpriteGFX:: 			   INCBIN "gfx/sprites/pokemon/coalta.2bpp"
SECTION "_SnouwrbunSpriteGFX", ROMX
SnouwrbunSpriteGFX::           INCBIN "gfx/sprites/pokemon/snouwrbun.2bpp"
SECTION "_VegelancheSpriteGFX", ROMX
VegelancheSpriteGFX::          INCBIN "gfx/sprites/pokemon/vegelanche.2bpp"
SECTION "_JigglypuffSpriteGFX", ROMX
JigglypuffSpriteGFX::          INCBIN "gfx/sprites/pokemon/jigglypuff.2bpp"
SECTION "_WigglytuffSpriteGFX", ROMX
WigglytuffSpriteGFX::          INCBIN "gfx/sprites/pokemon/wigglytuff.2bpp"
SECTION "_ZubatSpriteGFX", ROMX
ZubatSpriteGFX::               INCBIN "gfx/sprites/pokemon/zubat.2bpp"
SECTION "_GolbatSpriteGFX", ROMX
GolbatSpriteGFX::              INCBIN "gfx/sprites/pokemon/golbat.2bpp"
SECTION "_OddishSpriteGFX", ROMX
OddishSpriteGFX::              INCBIN "gfx/sprites/pokemon/oddish.2bpp"

SECTION "_GloomSpriteGFX", ROMX
GloomSpriteGFX::               INCBIN "gfx/sprites/pokemon/gloom.2bpp"
SECTION "_VileplumeSpriteGFX", ROMX
VileplumeSpriteGFX::           INCBIN "gfx/sprites/pokemon/vileplume.2bpp"
SECTION "_ParasSpriteGFX", ROMX
ParasSpriteGFX::               INCBIN "gfx/sprites/pokemon/paras.2bpp"
SECTION "_ParasectSpriteGFX", ROMX
ParasectSpriteGFX::            INCBIN "gfx/sprites/pokemon/parasect.2bpp"
SECTION "_ParasporSpriteGFX", ROMX
ParasporSpriteGFX::            INCBIN "gfx/sprites/pokemon/paraspor.2bpp"
SECTION "_OrefrySpriteGFX", ROMX
OrefrySpriteGFX::              INCBIN "gfx/sprites/pokemon/orefry.2bpp"
SECTION "_GoldeenSpriteGFX", ROMX
GoldeenSpriteGFX::             INCBIN "gfx/sprites/pokemon/goldeen.2bpp"
SECTION "_SeakingSpriteGFX", ROMX
SeakingSpriteGFX::             INCBIN "gfx/sprites/pokemon/seaking.2bpp"
SECTION "_DodaerieSpriteGFX", ROMX
DodaerieSpriteGFX::            INCBIN "gfx/sprites/pokemon/dodaerie.2bpp"
SECTION "_DoduoSpriteGFX", ROMX
DoduoSpriteGFX::               INCBIN "gfx/sprites/pokemon/doduo.2bpp"
SECTION "_DodrioSpriteGFX", ROMX
DodrioSpriteGFX::              INCBIN "gfx/sprites/pokemon/dodrio.2bpp"
SECTION "_VenonatSpriteGFX", ROMX
VenonatSpriteGFX::             INCBIN "gfx/sprites/pokemon/venonat.2bpp"
SECTION "_VenomothSpriteGFX", ROMX
VenomothSpriteGFX::            INCBIN "gfx/sprites/pokemon/venomoth.2bpp"
SECTION "_DiglettSpriteGFX", ROMX
DiglettSpriteGFX::             INCBIN "gfx/sprites/pokemon/diglett.2bpp"
SECTION "_DugtrioSpriteGFX", ROMX
DugtrioSpriteGFX::             INCBIN "gfx/sprites/pokemon/dugtrio.2bpp"
SECTION "_PsyduckSpriteGFX", ROMX
PsyduckSpriteGFX::             INCBIN "gfx/sprites/pokemon/psyduck.2bpp"
SECTION "_GolduckSpriteGFX", ROMX
GolduckSpriteGFX::             INCBIN "gfx/sprites/pokemon/golduck.2bpp"
SECTION "_MankeySpriteGFX", ROMX
MankeySpriteGFX::              INCBIN "gfx/sprites/pokemon/mankey.2bpp"
SECTION "_PrimeapeSpriteGFX", ROMX
PrimeapeSpriteGFX::            INCBIN "gfx/sprites/pokemon/primeape.2bpp"
SECTION "_FurretSpriteGFX", ROMX
FurretSpriteGFX::              INCBIN "gfx/sprites/pokemon/furret.2bpp"
SECTION "_HoppipSpriteGFX", ROMX
HoppipSpriteGFX::              INCBIN "gfx/sprites/pokemon/hoppip.2bpp"
SECTION "_MunchlaxSpriteGFX", ROMX
MunchlaxSpriteGFX::            INCBIN "gfx/sprites/pokemon/munchlax.2bpp"
SECTION "_MallodySpriteGFX", ROMX
MallodySpriteGFX::             INCBIN "gfx/sprites/pokemon/mallody.2bpp"
SECTION "_AriadosSpriteGFX", ROMX
AriadosSpriteGFX::             INCBIN "gfx/sprites/pokemon/ariados.2bpp"
SECTION "_KatuSpriteGFX", ROMX
KatuSpriteGFX::                INCBIN "gfx/sprites/pokemon/katu.2bpp"
SECTION "_SkiploomSpriteGFX", ROMX
SkiploomSpriteGFX::            INCBIN "gfx/sprites/pokemon/skiploom.2bpp"
SECTION "_WorfursSpriteGFX", ROMX
WorfursSpriteGFX::             INCBIN "gfx/sprites/pokemon/worfurs.2bpp"
SECTION "_WearlycanSpriteGFX", ROMX
WearlycanSpriteGFX::           INCBIN "gfx/sprites/pokemon/wearlycan.2bpp"
SECTION "_SphealSpriteGFX", ROMX
SphealSpriteGFX::              INCBIN "gfx/sprites/pokemon/spheal.2bpp"
SECTION "_PiplupSpriteGFX", ROMX
PiplupSpriteGFX::              INCBIN "gfx/sprites/pokemon/piplup.2bpp"
SECTION "_WailmerSpriteGFX", ROMX
WailmerSpriteGFX::             INCBIN "gfx/sprites/pokemon/wailmer.2bpp"
SECTION "_WailordSpriteGFX", ROMX
WailordSpriteGFX::             INCBIN "gfx/sprites/pokemon/wailord.2bpp"
SECTION "_SentretSpriteGFX", ROMX
SentretSpriteGFX::             INCBIN "gfx/sprites/pokemon/sentret.2bpp"
SECTION "_NorspruceSpriteGFX", ROMX
NorspruceSpriteGFX::		   INCBIN "gfx/sprites/pokemon/norspruce.2bpp"

